### ISSUE TITLE
In desktop entries: it separates args on space, not on new arg

### ISSUE THREAD

**Issue by es20490446e** [lxqt/qterminal#1008]
This happens in both `xterm` and `qterminal 1.1.0`, when set as default terminal emulator. Not in `konsole`.

If you execute a desktop entry with the line:
`Exec=script %F`

`qterminal` won't split the args in `%F` for each arg, but for each white space. This means you won't be able to launch applications with paths to multiple files, if those have white-spaces.

For example, we have these files:
```
file 1.txt
file 2.txt
```

This script:

```
#! /bin/bash

for arg in "${@}"; do

    echo "> ${arg}"

done

sleep 10
```

And this desktop entry:

```
[Desktop Entry]

Name=script

Exec=script %F

Type=Application

NoDisplay=true

StartupNotify=true

Terminal=true

MimeType=text/plain;
```

If I select both files and I select to open them with script, I get:

```
> file
> 1.txt
> file
> 2.txt
```

Quoting `%F` with `"` gives the result quoted, but split at every white-space anyway. Quoting with `'` gives the same result as above.

**Comment by tsujan** [comment]
Already fixed in https://github.com/lxqt/qterminal/commit/5605b8ce1c698b6d8f33c67f6f91cb7c2ce43721. With the latest git, I get:
```
> /home/pedram/file 1.txt
> /home/pedram/file 2.txt
```
V1.2.0 will be released soon.

**Comment by es20490446e** [comment]
Oki 👍
