### ISSUE TITLE
[Unimportant feature request] Changing the title of File menu-bar item?

### ISSUE THREAD

**Issue by tsujan** [lxqt/qterminal#1017]
I was searching for a good replacement for Qps' "Command" menu-bar item and saw that QTerminal had a "File" menu-bar item. Since there is no file operation under that title, I think we might want to change it.

I know that seeing "File" as the first menu-bar item is a sort of tradition, but sometimes it's too irrelevant ;)

IMHO, "Session" would be much more relevant than "File".

**Comment by stefonarch** [comment]
We need more items for a menu "File" than just "exit".
 QTerminal has the preferences there, so we could at least move that, so we'd have "exit" and "preferences".

Or we find some useful commands. Is there any draft in the code left for what it was thought for initially?

**Comment by tsujan** [comment]
> Or we find some useful commands

QPs shouldn't be for running commands. It's full of strange ideas and stranger codes. It should just be cleaned up, IMO.

Let's not make @yan12125 angry by talking about Qps here ;) This report is about "File" in QTerminal.

**Comment by stefonarch** [comment]
Oops, I completely misunderstood starting from your first line, thought it was about changing "command" in qps. 

"Session"  looks good to me.

**Comment by tsujan** [comment]
My fault. I meant that "File" in QTerminal was as bad as "Command" in Qps.

**Comment by yan12125** [comment]
File is indeed kind of strange, and Session sounds better.

As a record, here are actions added to the Filemenu.
