### ISSUE TITLE
When unmaximizing window, terminal often resizes itself to the size it was when maximized.

### ISSUE THREAD

**Issue by userse31** [lxqt/qterminal#1018]
##### Expected Behavior

Terminal window returns to the size it was previously when not maximized.

##### Current Behavior

Window briefly goes back to the size it was when not maximized, then quickly resizes itself and takes up the whole screen. 

##### Possible Solution

Option to force a default terminal size?

##### Steps to Reproduce (for bugs)

1.When not maximized, size the terminal to 80x25
2.Maximize the window.
3.Unmaximize the window.
4.Window gets resized to how it was when fullscreen.
5.Sometimes doesn't happen. I think it depends on what your running (perhaps vim?).

##### Context

UGH!!! This has been driving me MAD!

##### System Information

* QTerminal version: 0.16.1
* Distribution & Version: Debian 11.5
* Kernel:5.10.0-19
* Qt Version: 5.15.2

**Comment by tsujan** [comment]
Not reproducible.

> Option to force a default terminal size?

0.16.1 is totally outdated. QTerminal has this option: Preferences → Behavior → "Start with this size: ..."

**Comment by userse31** [comment]
What? 0.16.1 is outdated? But my machine is up to date!

**Comment by stefonarch** [comment]
Debian had a lack of maintainership, 0.16 was released 2 years ago.
Debian 12 testing has the actual version, 1.2.0

**Comment by userse31** [comment]
Oh, so its a debian package thing?
