### ISSUE TITLE
License specification conflict between qterminal.metainfo.xml and README.md

### ISSUE THREAD

**Issue by ArrayBolt3** [lxqt/qterminal#1032]
Problem noticed in the source code of QTerminal 1.2.0. I have verified that it still exists in the current Git master.

The README.md files specifies:

> This project is licensed under the terms of the [GPLv2](https://www.gnu.org/licenses/gpl-2.0.en.html) or any later version. See the LICENSE file for the full text of the license.

The qterminal.metainfo.xml file specifies:

> <project_license>GPL-2.0-only</project_license>

Whenever someone can get around to it, it would be great if one or the other of these files could be changed to match the license QTerminal is actually under. Because the README.md file seems to spell things out clearly, I assume that GPL-2+ is the correct license.

**Comment by yan12125** [comment]
The license was changed from `GPL-2` to `GPL-2.0-only` in https://github.com/lxqt/qterminal/pull/901. @stefonarch Do you remember the reason behind that change?

**Comment by stefonarch** [comment]
I think this was just a mistake from me, maybe the validator complained about `GPL-2`.

**Comment by yan12125** [comment]
The license field [uses SPDX](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license). Looks like this is what we need: https://spdx.org/licenses/GPL-2.0-or-later.html

By the way, bundled [libqxt](https://github.com/lxqt/qterminal/tree/master/src/third-party) (apparently used for dropdown shortcut) uses something like BSD. Not sure if it should be included in the metadata or not.

**Comment by yan12125** [comment]
From https://spdx.github.io/spdx-spec/v2.3/SPDX-license-expressions/,

> Another example is when a set of licenses is needed to represent a binary program constructed by compiling and linking two (or more) different source files each governed by different licenses (e.g., LGPL-2.1-only AND BSD-3-Clause).

So the license of libqxt should be included, and the result is `GPL-2.0-or-later AND BSD-3-Clause`. The license of libqxt is inferred from [this upstream commit](https://bitbucket.org/libqxt/libqxt/commits/fb557ea64f117378de606f99c72da6e1d905b3e0).
