### ISSUE TITLE
Clear history

### ISSUE THREAD

**Issue by Shinybro** [lxqt/qterminal#1036]
Is it possible to clear the history?

**Comment by stefonarch** [comment]
Use  `history -c`

**Comment by Shinybro** [comment]
This only works for the ongoing session.
When you close and reopen qterminal the history is back again.

**Comment by stefonarch** [comment]
> This only works for the ongoing session.
> When you close and reopen qterminal the history is back again.

True... I never clear it. Maybe others know more, but  `rm ~/.bash_history` seems working fine.

**Comment by tsujan** [comment]
@stefonarch, why did you reopen it? The question wasn't about QTerminal.

**Comment by stefonarch** [comment]
I've had no idea how other emulators handle this, I see in xterm it's the same.
