### ISSUE TITLE
Ctrl+Backspace for delete the previous word instead of using Alt+Backspace

### ISSUE THREAD

**Issue by VIUNDESIGN** [lxqt/qterminal#1038]
##### Expected Behavior

In "**Preferences > Terminal Settings > Shortcuts**" the option does not appear.
I added to  `~/.config/qterminal.org/qterminal.ini` >> `Ctrl+Backspace=SendEscape sequence=\033\177` but still not working and the file can't saved at all

Also I am looking for the "select all" shortcut too, with "ctrl+A"
`Ctrl+A=SelectAll`

##### Current Behavior

The shortcuts doesn't work.
The file `~/.config/qterminal.org/qterminal.ini` goes back to how it was after closing it

##### Possible Solution

Add the option in the Shortcut tab in "**Preferences > Terminal Settings > Shortcuts**"

##### Context

I want to work with "`Ctrl+Backspace`" for delete the previous word like other apps instead of "`Alt+Backspace`"

**Comment by VIUNDESIGN** [comment]
?

**Comment by tsujan** [comment]
That's a shell function, not related to terminals.

@yan12125 
Shouldn't this be closed?

**Comment by yan12125** [comment]
The mapping from special keys to escape sequences is indeed handled by qtermwidget. Check ```/usr/share/qtermwidget5/kb-layouts/default.keytab```.

**Comment by yan12125** [comment]
> Also I am looking for the "select all" shortcut too, with "ctrl+A"

The handle history feature, which is available since qterminal 0.15 (https://github.com/lxqt/qterminal/pull/580), should fit your need.

Above all, I believe existing features are enogh. Feel free to open a new issue or leave comments below if not.
