### ISSUE TITLE
Change scrollbar width

### ISSUE THREAD

**Issue by ZaWarudo111** [lxqt/qterminal#1054]
I am trying to change the vertical scrollbar width inside QTerminal. There are no settings related to it in Preferences.

'Im using theme `Kali-Dark`. I tried to change `/usr/share/themes/Kali-Dark/gtk-3.0/gtk.css`. I changed the `min-width` to 20px: `scrollbar slider { min-width: 20px; }`. After rebooting, nothing happens. 

In `/usr/share/themes/Kali-Dark/`, there are also folders `gtk-2.0` and `gtk-4.0`. I'm not sure which one of them should i change but I tried them all. Nothing works.

##### Expected Behavior
Vertical scrollbar width changes to 20px.

##### Current Behavior
Vertical scrollbar width won't change.

##### Possible Solution
Change some .css file or other config file to modify the scrollbar width

##### Steps to Reproduce (for bugs)
1. `sudo nano /usr/share/themes/Kali-Dark/gtk-3.0/gtk.css`
2. Search `scrollbar slider`
3. Edit `min-width` to 20px
4. `Ctrl+O` to save, `Ctrl+X` to exit.
5. Reboot

##### System Information
* QTerminal version: 1.2.0
* Distribution & Version: Kali Linux
* Kernel: 6.1.0-kali7-amd64
* Qt Version: 5.15.8

**Comment by tsujan** [comment]
Not related to the app but to the Qt style.

**Comment by ZaWarudo111** [comment]
> Not related to the app but to the Qt style.

Maybe, but I could not find any help online that solves my problem. That's why i asked here. I would like to get at least some guidance.

**Comment by tsujan** [comment]
> I would like to get at least some guidance.

We have [Discussions](https://github.com/lxqt/lxqt/discussions) for LXQt users.

Anyway, a short answer:

To change the look and feel of Qt apps, you need to change the Qt style. The default style of Qt is called Fusion, but there are other styles that you can install, like Breeze, Kvantum, QtCurve,... Some of them have detailed settings, some don't. If you use LXQt, you could easily change the Qt style in LXQt Appearance Configuration. If you don't use LXQt, you might want to consult forums of your distro or those of your DE.
