### ISSUE TITLE
QTerminal dropdown occasionally opens in a minimized state

### ISSUE THREAD

**Issue by isf63** [lxqt/qterminal#1066]
##### Expected Behavior
Activating dropdown QTerminal with a hotkey should never open it minimized.

##### Current Behavior
Pressing a hotkey to open QTerminal opens it in a minimized state once or twice randomly throughout the day.

##### Steps to Reproduce (for bugs)
1. Press the hotkey to open QTerminal, then minimize it from the taskbar. Upon pressing the hotkey to open it opens in a minimized state.
2. Press the hotkey to open QTerminal, then press the Show Desktop panel button. 50% of the time upon pressing the hotkey to reopen it opens in a minimized state.

##### System Information

.config/qterminal.org/qterminal.ini DropMode section:
```
[DropMode]
Height=45
KeepOpen=false
ShortCut=F12
ShowOnStart=false
Width=70
```
* QTerminal version: qterminal-git
* Distribution & Version: Arch Linux
* Kernel: 6.4.10
* Qt Version: 5.15.10+kde+r147

**Comment by tsujan** [comment]
Not reproducible with KWin. What's your WM?

**Comment by isf63** [comment]
My WM is Xfwm4; tested on Openbox and it's the same behavior as Xfwm4.

**Comment by stefonarch** [comment]
>Press the hotkey to open QTerminal, then minimize it from the taskbar.

The dropdown terminal shouldn't be show in the taskbar no?  Maybe I'm biased now by wayland where it isn't shown, but there is no need to have it in the taskbar.

**Comment by isf63** [comment]
@stefonarch, it also happens when you press Show Desktop sometimes. In that case it's helpful that you can reopen it with the taskbar, but I have no preference for it being in the taskbar.

**Comment by tsujan** [comment]
> it's helpful that you can refocus it by clicking the task item

Oh, if that's so, Xfwm4 has a serious problem, because the dropdown terminal should *hide* on losing its focus.

**Comment by isf63** [comment]
Unfortunately this was not fixed in the recent 4.20 release. XFCE has a slow release cycle for minor versions (~2 years), although they sometimes do point releases.

For sake of completeness, these are all the issues I've noticed with Xfwm4 (X11):
- Xfwm4 shows the task button for QTerminal dropdown _always_ when active (normally or minimized.) (But not when correctly hidden.)
- If you minimize the QTerminal task button, reopening QTerminal opens it in a minimized state (can get the window open by clicking the task button.)
- Pressing 'Show Desktop', half the time works correctly, otherwise upon reopening causes the same bugged minimized state as above.
- There may be other times when the minimized bug occurs randomly throughout daily use.

In addition
- Pressing Preferences -> Font -> Change..., causes the font window to appear _behind_ both the terminal and the preferences window. This doesn't happen when QTerminal is windowed.

**Comment by tsujan** [comment]
The code does the most it can do:
```c++
    setWindowFlags(Qt::Dialog | Qt::WindowStaysOnTopHint | Qt::CustomizeWindowHint);
```
An X11 WM may ignore it partially or completely; that's out of our control.

Ironically, Wayland WMs seem to be more consistent in this regard, although the above line isn't for Wayland.

**Comment by isf63** [comment]
@tsujan,

I found a workaround that fixes the issue for Xfwm4 and Openbox, adding `setWindowState(windowState() & ~Qt::WindowMinimized);` after https://github.com/lxqt/qterminal/blob/8ff487e566a3552299edfd5ca0eaefeaee887724/src/mainwindow.cpp#L833

I'm not sure if it's semantically correct (in all cases) though.
