### ISSUE TITLE
Live configuration changes from ini file

### ISSUE THREAD

**Issue by Peter774** [lxqt/qterminal#1070]
**Is your feature request related to a problem? Please describe.**
I'm unable to change QTerminal configuration by editing ~/.config/qterminal.org/qterminal.ini file (sed -i) when QTerminal is running.

**Describe the solution you'd like**
Current behavior:
On first startup app creates small configuration file.
On exit file is updated to reflect full configuration status.
I heed to exit app before performing qterminal.ini file edit.

Expected behavior:
Every time app sets configuration option in memory (even for default values) is should mark config dirty and write it after small delay (1s).
So on first launch, after ~1s ini file will be fully populated.
No ini write on exit (redundant operation).

Additional/optional/cool solution:
After setting default values (+ delayed write) or after initial config read app will monitor (inotify?) ini file and on its change QTerminal will reload configuration from ini file and use new/updated values.

##### Context
QTerminal 1.2.0 on Kali Linux.
I'm spinning VM with additional scripts to deploy/configure system faster.

**Comment by tsujan** [comment]
A live config change needs file watching, which may be good only for some system settings, not for individual apps. With most apps, if you want to edit their config files, you need to quit them first.

It's good practice to keep I/O low by putting config changes in the memory and writing/reading to/from the disk only when needed — even with SSD.
