### ISSUE TITLE
Braille symbols cause visual artefacts

### ISSUE THREAD

**Issue by serpent7776** [lxqt/qterminal#1075]
##### Expected Behavior
Braille symbols don't break layout of TUI apps.

##### Current Behavior
Braille symbols cause visual artefacts, e.g. in btop and bottom.
The issue disappears if braille symbols are disabled.

##### Possible Solution
Braille symbols rendering is probably buggy and should be fixed.

##### Steps to Reproduce (for bugs)
1. Launch btop ar btm with braille symbols enabled.

##### Context
This breaks TUI layouts.

##### System Information
* QTerminal version:  `1.3.0`
* Distribution & Version:  `Manjaro`
* Kernel:   `Linux arc 5.15.131-1-MANJARO #1 SMP PREEMPT Thu Sep 7 11:05:18 UTC 2023 x86_64 GNU/Linux`
* Qt Version:  `5.15.10`

![image](https://github.com/lxqt/qterminal/assets/3284364/ece98fc1-4466-41b6-a5c3-fbc3d73839ad)
![image](https://github.com/lxqt/qterminal/assets/3284364/7b848f79-9b45-4bf2-8b36-6f18e7d3c16e)

btop: https://github.com/aristocratos/btop
bottom: https://github.com/ClementTsang/bottom

**Comment by yan12125** [comment]
The same issue as https://github.com/lxqt/qterminal/issues/685. I have no idea how this can be properly fixed, though.

**Comment by serpent7776** [comment]
Thanks, I confirm that checking `Preferences -> Appearance -> Use box drawing characters contained in the font` helps with drawing the boxes, but I still see artefacts, e.g.
![image](https://github.com/lxqt/qterminal/assets/3284364/23566bbf-1a8f-4a03-b867-414b79e3dd6d)

I'm now at QTerminal 2, Qt version 6.7.1.

**Comment by correabuscar** [comment]
excellent! I see that you're now affected by https://github.com/lxqt/qterminal/issues/1143
