### ISSUE TITLE
[Feature request] --Tab ?

### ISSUE THREAD

**Issue by anffna** [lxqt/qterminal#1085]
Hi guys! This is the best terminal emulator! So, how about adding the tabs option to the command line? So we could create context menu commands to open multiple tabs in one instance, instead of multiple instances....That's it, thanks!

**Comment by tsujan** [comment]
I'm afraid this is like https://github.com/lxqt/qterminal/issues/796 and closed for the [same reason](https://github.com/lxqt/qterminal/issues/796#issuecomment-2445467150).
