### ISSUE TITLE
QTerminal failed with segfault

### ISSUE THREAD

**Issue by abourree** [lxqt/qterminal#1087]
##### Expected Behavior
Qterminal should start

##### Current Behavior
qterminal failed with "Segmentation fault"
$ sudo dmesg | tail
[ 1663.367542] qterminal[120172]: segfault at 7ffe2574eff8 ip 00007f9aaabe348e sp 00007ffe2574f000 error 6 in [ 1663.367555] Code: 48 8b 47 08 48 8b 78 08 e9 4f a4 00 00 90 66 66 2e 0f 1f 84 00 00 00 00 00 0f 1f 00 f3 0f 1e fa 55 48 8d 15 74 e9 ff ff 89 f5 <53> 48 89 fb 48 83 ec 08 48 8b 07 48 8b 80 78 02 00 00 48 39 d0 75

##### Steps to Reproduce (for bugs)
$qterminal

##### System Information
$ lxqt-about --version
lxqt-about 1.4.0
liblxqt   1.4.0
Qt        5.15.10

$ cat /etc/debian_version 
trixie/sid

$ qterminal --version
1.3.0

**Comment by tsujan** [comment]
Not reproducible if "Steps to Reproduce" consists of only `$ qterminal`.

```
$ qterminal --version
1.3.0
```

You can't have QTerminal 1.3.0 with liblxqt 1.4.0. Check whether you've upgraded everything correctly.

**Comment by abourree** [comment]
I never did more than apt update/upgrade for lxqt pakages
Should be something wrong on Debian dependency side
$lxqt-config --version
1.3.0
I think upgrade is in progress and I try update in between
I should wait

**Comment by tsujan** [comment]
It's a Debian problem: at this moment, libqtermwidget5-1 is 1.4.0-1 is in Debian Testing, but qterminal is still 1.3.0-1. Of course, a crash should happen immediately.
