### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ItaloHugoMDS** [lxqt/qterminal#1090]
I stopped a running a `fc` within a instance of qterminal, now the terminal doesn't start no matter where I try to run it from. I've installed xfce as a workaround and everything is back to normal. I've tried to remove using ´apt-get´ and install it again but I still get a segmentation fault when I try to start qterminal.  

##### Expected Behavior

A instance of qterminal should start running.  

##### Current Behavior

Segmentation Fault error is displayed. Instance doesn't start running.  

##### Possible Solution

As a workaround, I've downloaded xfce and now I have access to the terminal again.  

##### Steps to Reproduce (for bugs)

1. Run a `fc` command to try to get a previous command back.  
2. Send a Signal Interrupt using `Ctrl + c`.  
3. The instance stopped running and doesn't launch anymore.  

##### System Information

* QTerminal version: 1.3.0
* Distribution & Version: Kali GNU/Linux V.2023.4
* Kernel: 6.3.0-kali1-amd64
* Qt Version:

**Comment by muradabdullayev900** [comment]
Upgrade it. I had same issue 1.3.0 version gives segmentation fault. Now I use 1.4.0 and it's fine

**Comment by tsujan** [comment]
Yes, I'd suspected that the issue was inherited from Debian: https://github.com/lxqt/qterminal/issues/1087.
