### ISSUE TITLE
[Feature request] Option to customize set of semantic selection split characters

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/qterminal#1098]
**Is your feature request related to a problem? Please describe.**

It seems that the set in question is hardcoded to something like whitespaces and `=<>[]{}()#`, which makes doubleclick selections pretty greedy.

**Describe the solution you'd like**

An option in preferences to customize this set of characters.

**Describe eventual alternatives you've considered**

**Comment by yan12125** [comment]
I wanted this feature since 2017 but I'm too lazy to finish the patch! https://github.com/lxqt/qterminal/commits/set-word-characters/
