### ISSUE TITLE
Font can't be changed in QTerminal 1.3.0

### ISSUE THREAD

**Issue by ralf3u** [lxqt/qterminal#1103]
File, Preferences..., Appearance:
Font: click on 'Ubuntu Mono 14 pt'

Result
nothing happens

Expectation
I expect that I can change the font size.

System
Lubuntu 23.10
LXQt 1.3.0

If this issue does not exist in QTerminal 1.4.0, then I'm sorry for this report.

**Comment by ralf3u** [comment]
I found an alternative: I changed  the document `qterminal.ini` that is located in
`.config/qterminal.org/`
the value
`fontSize=14`
to
`fontSize=27`.

**Comment by isf63** [comment]
By any chance are you using Qterminal in dropdown mode, and Xfwm4 as your window manager? Xfwm4 has a bug that affects dropdown mode's font dialog where it goes behind the terminal and settings window.

**Comment by ralf3u** [comment]
>... are you using Qterminal in dropdown mode ...?

No.

>... Xfwm4 as your window manager?

No, I use openbox.

**Comment by ralf3u** [comment]
I just recognized that if I maximize the settings-window, I can  see that there is a button, called Change. That button was not visible before.
To avoid this situation in the future, what about to put the button Change directly on the right side of `Font`?
Now it is like this:
Font Ubuntu Mono 27 pt Change
It could be like this:
Font Change Ubuntu Mono 27 pt

Should I open a new issue for that?

**Comment by tsujan** [comment]
> Should I open a new issue for that?

Please do not.
