### ISSUE TITLE
Use layershell for dropdown terminal under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#1111]
Use layershell for positioning and layer, similar to lxqt-runner and lxqt-leave dialog windows.

##### Expected Behavior

Dropdown settings for size are working under wayland and do not show it in taskbars.
##### Current Behavior

* Position has to be manually fixed for centering and top panel by window rules and will affect all qterminal windows, e.g.
`<action name="MoveTo" x="80" y="38"/>` under labwc.

* Dropdown terminal shows up in taskbar

##### Possible Solution

 
Use similar code as we do in runner already:
https://github.com/lxqt/lxqt-runner/blob/3deaf15726c59c90f4a53c2d4678799d79889e26/dialog.cpp#L206

##### Context

Should be among wayland improvements in  LXQt 2.1  
Related issues are https://github.com/lxqt/qterminal/issues/1028 and https://github.com/lxqt/qterminal/issues/1059.

With a working single mode `qterminal -d`  can be used to reopen the existing dropdown QTerminal.

##### System Information

* QTerminal version: qt6

**Comment by marcusbritanicus** [comment]
@stefonarch I think this issue can be closed, now that #1113 is merged.
