### ISSUE TITLE
Preferences window opens below qterminal -d under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#1133]
A side effect of layershell overlay.

##### Expected Behavior

The window should be accessibile
##### Current Behavior

It's not, the best thing to do  is to press again the hotkey 
##### Possible Solution

Emit a "hide " signal when preferences window opens under wayland in dropdown modeor use also layershell for the preferences window in dropdown mode under wayland.

* QTerminal version: git

**Comment by tsujan** [comment]
Being a Wayland issue, this isn't limited to the Preferences window. For example, the paste prompt dialog is also opened behind the window.
