### ISSUE TITLE
Selection not cleared in bracketed paste mode

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#1137]
It happens quite often here.

##### Expected Behavior

Only one selected text should be shown and should clear
##### Current Behavior

Sometimes multiple selections are shown with one persistent that can't be cleared. There are several ways to make this happens.

##### Steps to Reproduce (for bugs)

One way to reproduce it is
1. Select a command like in the screenshot
2. Paste it
3. hit ctrl+c
4. the selection remains permanent and can be repeated while the "true" selection is `rocm-5.7.1`:

![immagine](https://github.com/lxqt/qterminal/assets/10681413/551277b4-bcb1-4a5e-85c4-e8be08805bb9)

##### System Information

* QTerminal version: 2.0 and older

**Comment by tsujan** [comment]
Maybe it's random, because I can't reproduce it here; tried more than 5 times.

**Comment by stefonarch** [comment]
With the described steps it's always reproducible. But beside the selection highlighting not reset: why is pasted text highlighted here? It is cleared on enter when the command is executed.

**Comment by stefonarch** [comment]
Just tested console, exact the same issue.

**Comment by tsujan** [comment]
> why is pasted text highlighted here?

Oh, that explains the different results. I check `Terminal settings → Behavior → Forcefully disable bracketed paste mode`. The bracketed paste mode started to be the default mode everywhere 4 years ago. As I disliked it, I added and used that option.

With the bracketed paste mode, I can reproduce the problem.

**Comment by tsujan** [comment]
> Just tested console, exact the same issue

When it's the same with XTerm too, I guess it's a "feature" of the bracketed paste mode.

Closing this?

**Comment by stefonarch** [comment]
xterm doesn't support pasting. Maybe it's inherited, but having multiple selections visible which can't be reset is an issue IMO.

**Comment by tsujan** [comment]
> xterm doesn't support pasting.

It does, by middle-clicking.

**Comment by tsujan** [comment]
> and I'm quite sure it happens in other circumstances

Just disable the bracketed paste mode and get rid of it. I had a reason to add that option 4 years ago ;) (→ https://github.com/lxqt/qtermwidget/pull/390 and https://github.com/lxqt/qterminal/pull/772)

**Comment by tsujan** [comment]
Although testing with XTerm seemed enough to me, I also installed gnome-terminal: exactly the same "feature" showed up there.

I really think this isn't our problem to solve. At least, we have an option for it.

**Comment by stefonarch** [comment]
Ok, changed the title.
