### ISSUE TITLE
Unable to change font to monospace

### ISSUE THREAD

**Issue by es20490446e** [lxqt/qterminal#1139]
#### System
* qterminal 2.0.0
* qt 6.7.1
* Arch Linux

#### Steps
 Try changing to monospace font.

#### Result
Font doesn't change, and instead the previous font is selected.

#### Info
Changing the font directly on qterminal.ini works.

**Comment by stefonarch** [comment]
Can't reproduce here. There is no dropdown terminal active while changing font in a normal window?

**Comment by es20490446e** [comment]
No dropdown terminal.

Removing the ini doesn't solve the problem either.

**Comment by tsujan** [comment]
> instead the previous font is selected.

Isn't the previous font monospace? You can check that with `fc-match monospace`.

Do you have a well defined monospace? See https://github.com/lxqt/qterminal/wiki#how-to-set-my-preferred-font-for-monospace

**Comment by es20490446e** [comment]
If I create `0-mono.conf` verbatim as in the [wiki](https://github.com/lxqt/qterminal/wiki#how-to-set-my-preferred-font-for-monospace), it works.

But if I substitute it for `Noto Sans Mono`, it doesn't.

Also `Noto Sans Mono` doesn't appear listed as selectable monospace font.

Here's the [`noto` package](https://gitlab.archlinux.org/archlinux/packaging/packages/noto-fonts), in case you see something.

---

If I launch `qterminal` within a terminal, with `monospace` as font and `noto` as monospace, it says three times:

> Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.

But if `Dejavu` is the font, it is only displayed once.

**Comment by tsujan** [comment]
> But if I substitute it for Noto Sans Mono, it doesn't.

Because Qt doesn't see Noto as a monospace font. I refer you to your own comment and the links it leads to: https://github.com/lxqt/qterminal/issues/1088#issuecomment-1883896450.

**Comment by es20490446e** [comment]
Yeah, but not being able to select `monospace` is new... I guess due to `Qt6`.
