### ISSUE TITLE
Segmentation Fault on Launch

### ISSUE THREAD

**Issue by itsrainingshells** [lxqt/qterminal#1147]
##### Expected Behavior
I expect QTerminal to launch via the GUI.

##### Current Behavior
Current behavior is a crash on launch.  I downloaded another terminal emulator and tried to run QTerminal.

QWidget::setMinimumSize: (mainWindow/MainWindow) The largest allowed size is (16777215,16777215)
QWidget::setMinimumSize: (BookmarksDockWidget/QDockWidget) Negative sizes (524289,-1) are not possible
QWidget::setMaximumSize: (BookmarksDockWidget/QDockWidget) Negative sizes (524287,-1) are not possible
qt.qpa.xcb: xcb_shm_create_segment() can't be called for size 17179344900, maximumallowed size is 4294967295
zsh: segmentation fault  qterminal

##### Possible Solution
When booting without a docking station QTerminal launches without issue.

##### Steps to Reproduce (for bugs)
1. Plug laptop into docking station
2. Power on and start Linux 
3. Login and launch QTerminal
4. Segmentation fault

##### Context
As the terminal will not launch I'm unable to use it for regular tasks.

##### System Information
* QTerminal version: 1.4.0
* Distribution & Version: Kali Rolling
* Kernel: 6.8.11-amd64
* Qt Version: Qt6

**Comment by tsujan** [comment]
I'm afraid a segfault report needs to be accompanied by a backtrace. 1.4.0 isn't supported either, but I don't think the problem you've encountered is in it.

**Comment by itsrainingshells** [comment]
It looks like a coredump wasn't generated with the segfault.  Is there anything else I can provide to help with debugging?

└─$ coredumpctl gdb qterminal 
           PID: 53410 (qterminal)
           UID: 1000 (x)
           GID: 1000 (x)
        Signal: 11 (SEGV)
     Timestamp: Sat 2024-06-29 12:45:10 MDT (14s ago)
  Command Line: qterminal
    Executable: /usr/bin/qterminal
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (x)
       Boot ID: f4825b36523841bd88b5b2c2bb897ce3
    Machine ID: f00a08bcbec044a4b7b2b2e32a68eab7
      Hostname: x
       Storage: none
       Message: Process 53410 (qterminal) of user 1000 terminated abnormally without generating a coredump.

**Comment by tsujan** [comment]
> It looks like a coredump wasn't generated with the segfault.

If so, the crash may not be in QTerminal 1.4.0 or caused by it.

>  Is there anything else I can provide....

I have no idea. It may be better to report it Kali or ask in a Kali forum.

The only thing that caught my attention is that you wrote `Qt Version: Qt6`, while QTerminal 1.4.0 is based on Qt5.

**Comment by itsrainingshells** [comment]
Closed to take to another forum.
