### ISSUE TITLE
Add info to shortcut settings for dropdown terminal under wayland

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#1148]
##### Expected Behavior

GUI should work or give information
##### Current Behavior

Shortcut settings applies only to X11 and has no effect under wayland.
##### Possible Solution

Add a similar note as done for power keys in `lxqt-config-powermanagement`:

```
 if (QGuiApplication::platformName() == QStringLiteral("wayland"))
    {
        mUi->waylandLabel->setText(tr("Note: Under Wayland a shortcut for "qterminal -d" has to be configured in the compositor instead. "));
    }
```
Not sure if also add an info about dialog windows appearing below.
##### System Information

* QTerminal version: all

**Comment by tsujan** [comment]
Yes, I noticed it too, among other small problems, when testing https://github.com/lxqt/qterminal/pull/1146.

**Comment by stefonarch** [comment]
Done in https://github.com/lxqt/qterminal/pull/1151
