### ISSUE TITLE
MS font / .ttf font not show up in font selection setting

### ISSUE THREAD

**Issue by tloc241** [lxqt/qterminal#1162]
I try to have `MS DGothic font` for terminal but it not showing up (it does show up in gimp)

i have try adding it to` ~/.local/share/fonts` and `~/.fonts` and `/usr/share/font` but none of them want to show up in terminal (already try `fc-cache`)

##### Possible Solution
much of `.ttf` font i have also don't show up in setting, so maybe have a support for it in the future?

##### System Information                                            
* QTerminal version: 1.4.0
* Distribution & Version: Ubuntu 24.04
* Kernel: 6.9.12-2-liquorix-amd64
* Qt Version:5.15.13

**Comment by tsujan** [comment]
Terminal fonts should be monospace.
