### ISSUE TITLE
qterminal in virtual machine seems a little slow

### ISSUE THREAD

**Issue by sunbo2001** [lxqt/qterminal#1167]
qterminal version 1.4.0
os: debian sid
description: When I open qterminal, it always cost 1 second. When I open xfce4-terminal, it just opened in no time.
I have test it in bare metal, and qterminal is fast as xfce4-terminal.
But I install qterminal in my debian virtual machine, it will be a little slow.(vmware)

**Comment by sunbo2001** [comment]
Addition : When I disable 3D Acceleration in VMWARE, qterminal will be fast. But then I enable 3D Acceleration , xfce4-terminal also is fast! Why?

**Comment by tsujan** [comment]
I'm afraid there's nothing we could do here. It isn't about QTerminal itself, but about rendering.

> When I disable 3D Acceleration in VMWARE, qterminal will be fast... Why?

Perhaps because QTerminal supports translucency and VMWARE has a problem with it.

You could also use https://github.com/lxqt/lxqt/discussions.
