### ISSUE TITLE
[Feature request] Options to enable copy on select and right click paste. 

### ISSUE THREAD

**Issue by big-edd** [lxqt/qterminal#1172]
A checkbox/switch in the settings to enable each of these?

**Comment by tsujan** [comment]
Copying on selection exists everywhere and isn't specific to QTerminal.

Also, there are already two items for pasting in the right click menu.

**Comment by tsujan** [comment]
> And I found that text is not copied to clipboard upon being selected QTerminal.

Perhaps you don't know about the difference between the usual clipboard and the selection clipboard, and how each one can be pasted.

**Comment by tsujan** [comment]
> An option for copy to clipboard on select is what I meant.

As I mentioned, this topic has nothing to do with a specific app like QTerminal. It's controlled by the *clipboard manager* (which GNOME may lack).

I don't have GNOME, but apparently (https://wiki.gnome.org/Initiatives/Wayland/PrimarySelection), it doesn't support the selection clipboard (also called "primary").

In a nutshell:
 * If you select text from anywhere, you should be able to paste it by *middle clicking* into any text entry (primary/selection clipboard); and
 * You can explicitly copy and paste texts, like in MS Windows ((usual) clipboard).
 * Of course, you can use both simultaneously (one of benefits of having two kinds of clipboard).

I have three Wayland sessions and can do these in all of them, like I do under X11.

Clipboard managers provide users with fine-tuning — like putting the content of the primary into the usual clipboard, and vice versa.

**Comment by tsujan** [comment]
Add these to the list:

 * Select text from QTerminal and past it into a text entry by middle clicking.
 * Select text from anywhere and paste it into QTerminal by middle clicking.

That's called primary selection or primary/selection clipboard.

> Maybe I am comparing apples and oranges...

It's about different approaches. Some devs let their apps do jobs of another apps (we have terminal emulators that play video!), some don't; or some devs add as many options as possible, some don't; etc.

**Comment by tsujan** [comment]
> ... and it is using X11.

BTW, this isn't limited to X11. I'm typing from LXQt+Labwc, which an LXQt Wayland session. I can do all the above-mentioned kinds of copy-pasting here, including the primary ones.
