### ISSUE TITLE
[Feature request] New tab goes to current directory

### ISSUE THREAD

**Issue by Liteb0t** [lxqt/qterminal#1174]
Often I need multiple tabs in similar directory locations. When i make a new tab on **QTerminal** i always have to `cd` all the way there.

On **xfce4-terminal** making a new tab sends you to the same directory you where on when making the new tab command. This saves time because, assuming i want to go to the same directory 50% of the time, it is much quicker to `cd ~` than to `cd Documents/code_projects/project/...`. 
In reality it's higher than 50% because if I wanted to work in a completely different directory i would open a new terminal instance anyway, in which case starting from the home directory is sensible.

**Comment by tsujan** [comment]
New tabs are opened in the current directory. Which version of QTerminal do you have?

**Comment by Liteb0t** [comment]
Thank you, it was in preferences. I thought i checked there but i guess i'm blind lol.

**Comment by tsujan** [comment]
At least with recent versions of QTerminal, it's checked by default.

**Comment by Liteb0t** [comment]
That makes sense. I use Debian so my packages are prehistoric, next time I'll check the latest version
