### ISSUE TITLE
Small problem with URL highlighting

### ISSUE THREAD

**Issue by tsujan** [lxqt/qterminal#1184]
A valid report mysteriously disappeared from QTerminal's bug tracker. Fortunately I had it in Thunderbird. This is a copy-pasting of the original report (the images also belonged to that report):

If two adjacent URLs are separated by a space, but they are on different lines in the terminal due to wrapping, both URLs will be highlighted when hovering over only one of them.

![1](https://github.com/user-attachments/assets/9330eea3-baa2-4e01-a6b7-2556c5960295)

![2](https://github.com/user-attachments/assets/df68c297-13cd-4fd9-bd2e-d01dd1cfa724)

**Comment by DrinkDregs** [comment]
For some reason, now all of my reports and posts for my previous account "InnateLotion" are invisible. They are only visible to me if I log in using that account. I've had to create a new account.

These two screenshots show the difference between being signed in and not being signed in.
![a](https://github.com/user-attachments/assets/48ad14b8-6670-4af6-b3bd-d75cdfe2e51d)
![b](https://github.com/user-attachments/assets/bebb111c-dcce-427a-a169-3b505c00f920)

**Comment by tsujan** [comment]
@DrinkDregs
In case you can test it, the fix is here: https://github.com/lxqt/qtermwidget/pull/564
