### ISSUE TITLE
[Feature request]Implement 'focus follows mouse' in multi terminal session

### ISSUE THREAD

**Issue by stv-t** [lxqt/qterminal#1187]
I often have multiple terminal windows open within a single QTerminal session, each of which may be connected via _'ssh'_ to different servers.  
I tend to move the mouse from one terminal window to another within the same QTerminal session and start typing, as my DE is set up to use _'focus follows mouse'_.

My problem is that the pointer the window is in does accept input until I select the window with a button click. 

This often results in commands being typed into the wrong terminal window, and possibly on the wrong server.
I have previously started scripts and run commands on the wrong server, or in the wrong directory, due to this issue.

I would like to see a settings option, preferably in the _'Behaviour' section of the 'File|Preferences'_ menu, that allows me to select a _'focus follows mouse'_ option that would direct keyboard input to the terminal window that the mouse is currently in, without needing to select the window with a mouse button.

**Comment by tsujan** [comment]
This is the job of the WM. Apps shouldn't interfere with it. Particularly on Wayland, only the WM/compositor can do it.

**Comment by stefonarch** [comment]
> within the same QTerminal session

IMO this setting would be useful, if you use the splitted terminals. I'm using focus-follow-mouse too (on Hyprland).

**Comment by stefonarch** [comment]
> my DE is set up to use 'focus follows mouse'.

So it's not really clear, it should affect Qterminal windows too.

**Comment by tsujan** [comment]
When the window is activated by the WM, the view should get focused. Doesn't it when you use the "'focus-follows-mouse" of you Wayland compositor?

**Comment by stv-t** [comment]
Appears to be a terminology misunderstanding.

To clarify:
My system, Mageia 9, is still currently using X.
I have one QTerminal **session** running a single tab which is split into four terminal sub-windows as shown below.

<img width="581" alt="qterminal_window" src="https://github.com/user-attachments/assets/5d83cf1c-b609-4e4f-9f98-1380871093bc">

Moving the mouse from one terminal sub-window to another in the **same** QTerminal session does not direct the keyboard input to the terminal sub-window below the cursor but continues to sent it to the previously selected sub-window.  I am **not** moving from one QT session to another or from one tabbed session to another.

If I use 'Konsole' as my terminal emulator and split a terminal then the sub-window under the cursor receives the keyboard input. Unfortunately I prefer the look and functionality of QTerminal 
 
<img width="521" alt="konsole" src="https://github.com/user-attachments/assets/e7a7f177-a33b-4e4f-b3b9-a280f012bb56">

**Comment by tsujan** [comment]
Now, *that* is a valid feature.

This report was misleading. I'll open a new one for the requested feature.

**Comment by stefonarch** [comment]
So I was right about the "split view" :)

**Comment by tsujan** [comment]
> Btw: how do you set different colors for the splitted terminals?

"Show a border around the current terminal"

> So I was right about the "split view" :)

I haven't honed my telepathic power for a while ;)

**Comment by stv-t** [comment]
> Btw: how do you set different colors for the splitted terminals?
It is the 'Color Scheme' setting in the 'Preferences|Appearance' settings window, I have 'Black on Random' selected

<img width="386" alt="options" src="https://github.com/user-attachments/assets/630cc62f-e146-420c-8998-92e066676953">

**Comment by stefonarch** [comment]
Didn't know that, thanks. Nice,` Black on RandomDark' is missing...
