### ISSUE TITLE
[Feature request] flatpak version of qterminal

### ISSUE THREAD

**Issue by dfwdraco76** [lxqt/qterminal#1190]
**Is your feature request related to a problem? Please describe.**
The Ubuntu repositories contain an ancient version of qterminal.  I've spent weeks (off and on) trying to compile 2.1.0 on my Linux Mint 22 system, dealing with Qt6 issues and one thing after another.  At one point I gave up and resolved myself to just using GNOME Terminal, but it's lacking features, so I'm back at it again.  I'm still running into all kinds of problems trying to compile/build/install/get this dang thing to run.

**Describe the solution you'd like**
A flatpak version would be simple to install on any and all Linux systems.  How difficult would it be to do such a thing?

**Comment by tsujan** [comment]
Please don't request packaging upstream; we don't do any packaging here.

**Comment by dfwdraco76** [comment]
How/where would I request a flatpak version?

**Comment by tsujan** [comment]
Downstream — your distro, Flatpak, or wherever such packages are made.

**Comment by stefonarch** [comment]
Probably building a  snap package would be a better choice for Ubuntu, no idea.
