### ISSUE TITLE
Do we need app transparency?

### ISSUE THREAD

**Issue by tsujan** [lxqt/qterminal#1192]
App transparency seems a little weird, because we have terminal transparency, and I haven't seen app transparency elsewhere. Moreover, it can't work on Wayland.

If there's no objection, the plan is to remove it from QTerminal.

**Comment by tsujan** [comment]
Silence means consent?

**Comment by Chiitoo** [comment]
I don't think I've seen it elsewhere either, aside from Window Manager effects, and though in a way kind of fun, can see it a bit dangerous too (try setting it to 99% for example...).
