### ISSUE TITLE
After OS update: Hyperlinks disabled. [SOLVED, Notabug]

### ISSUE THREAD

**Issue by themanyone** [lxqt/qterminal#1195]
Qterminal uses `xdg-open` to open hyperlinks. If after OS update, hyperlinks no longer work, read on.

You can run `xdg-open http://github.com` or some such. The error displayed will be  "no method available for opening '$url'"

You can add 'set -x' at the top of the `/usr/bin/xdg-open` script on your system and run it again to trace flow.

In my case, after much searching to no avail, and almost writing unnecessary bug reports, I just needed to install  `qtxdg-mat` to make hyperlinks work again.

What could be improved: `qterminal` could issue some kind of error message if `xdg-open` doesn't work properly.

**Comment by tsujan** [comment]
Qterminal uses `QDesktopServices::openUrl()`, which calls `xdg-open` on Linux. Having a correct file association isn't the job of QTerminal.
