### ISSUE TITLE
Set Icon

### ISSUE THREAD

**Issue by nPHYN1T3** [lxqt/qterminal#1199]
**Is your feature request related to a problem? Please describe.**

Identifying terminals would be the problem.

**Describe the solution you'd like**

I'd like to be able to set an icon as a launch parameter. Something like:
for color coded SSH session
qterminal -i ssh-green -e ssh me@greenmachine
or for opening a term in a specific folder from a filemanager
qterminal -i  folder-term
or for my term that shows dmesg/journal logs
qterminal -i journalctl-radar -e journalctl
or for a term use for playing music
qterminal -i 45-record-clip -e play.sh thatcoolsong
or if I'm doing a lot of system stuff and have a term or to with sudo -s
qterminal -i root-term -e sudo -s

**Describe eventual alternatives you've considered**

A terrible hacky way to do this is launch with a --title or --class then target it with xseticon...but qterm doesn't have either --title or --class options. ;p

##### Context

I do a lot of stuff where terminals are specific to a task or role. If I launch an SSH session to a specific machine it's color coded. So I know when fishing through all the crap on my task bars or alttab menu to say look for my purple SSH icon...or the yellow one...you get the picture. Same goes when opening a terminal from a filemanager, I have an icon for that as well so I know when I see in the list THAT term with the folder with a term in it is the one launched to do the task I was doing in that one directory. I've made all kinds of icons to denote tasks and purposes and they are used with the terminal I've used for years...however GTK is just too broken on multi GPU anymore so I've transitioned to Qt options. Frankly I really like Qterminal, but it lacks the ability to set the icon on launch so I can tell one running instance from another.

**Comment by tsujan** [comment]
I doubt that this feature is worth an implementation, for two reasons, at least: Wayland will ignores the window icon, and we already have "Change window title based on the current terminal".

**Comment by nPHYN1T3** [comment]
Wayland strikes again...As for the title that doesn't work so well in matching icons to tasks given the tasks in the term can/will change.

**Comment by tsujan** [comment]
> Wayland strikes again.

It always does, willy-nilly.

Personally, I don't have motivation to work on new features that might work only on X11. But PRs will be reviewed.

**Comment by marcusbritanicus** [comment]
This idea is quite interesting.. I like the idea that I can know my "terminal context" based on some visual cue.

@nPHYN1T3 @tsujan How about this: why not add a tint to the qtermwidget itself based on the context? For example, the root terminal could be tinted red, or when opened in a specific folder, the terminal could be tinted blue, and so on. We could also extend it further: Automatic context cues. For example, we can tint the qtermwidget gray when in a folder the user cannot write or tint it red, when the command invoked is `sudo <something>`.

This would be a very unique feature to have. I doubt if any terminals out there in the wild have this.

At this stage, I would like to add that I have near to zero idea where or how this can be done. But I am willing to work on this feature some time in the future . . . :)

**Comment by nPHYN1T3** [comment]
I kinda already do the "tint" bit with my window manager. I have used Sakura for years which allows you to set your icon on launch but I also set a class so my icon denotes task for fast visual acquisition but my window manager also sets the border color based on the class so the window matches the icon.

**Comment by tsujan** [comment]
> How about this: why not add a tint to the qtermwidget

Tinting the terminal view may easily make its colored text unreadable, and I don't know of any other place.

**Comment by tsujan** [comment]
> root terminal could be tinted red

Any terminal can become root. You mean we should suddenly change its view color?

> when opened in a specific folder, the terminal could be tinted blue

Again, any terminal may be opened in a specific folder. There's nothing specific about that ;)

> we can tint the qtermwidget gray when in a folder the user cannot write

That seems to me rather like a file manager job.

A terminal emulator may be made do extra jobs — for example, I remember that Terminology (Enlightenment's terminal) played video and audio — but I'll be alarmed if an app's development goes in that direction.

**Comment by marcusbritanicus** [comment]
> Tinting the terminal view may easily make its colored text unreadable, and I don't know of any other place.

I do not mean a strong tint. Very light tinting: 10% opacity or less upon the existing color scheme. Another place is "border" of a terminal. We can change the border color of the terminal widget, instead of tinting. 

> Any terminal can become root. You mean we should suddenly change its view color?

I would say, yes. If a "root" command (like `su -c` or `sudo`) is running tint it red. 

> Again, any terminal may be opened in a specific folder. There's nothing specific about that ;)

I meant to say, opened in a folder, as opposed to just opened from menu.

> That seems to me rather like a file manager job.

You can always `cd` into something like `/usr/`, for example.

**Comment by tsujan** [comment]
Even if there's no problem (and I think there is), it seems like adding lots of codes to make the app fancy (→ last paragraph of my previous comment), without a real use.

**Comment by nPHYN1T3** [comment]
Well this went kinda sideways. I just wanted to set the icon via launch arg. You can set fonts, colors, themes, so why not the icon. As for the tint, sure it doesn't help if you launch as a normal user and sudo run0 (whatever) but I just set themes as root so when I launch as root I know the red stuff means Danger Will Robinson! I just wanted an icon arg. One teeny tiny icon arg. ;p

**Comment by nPHYN1T3** [comment]
Well this went kinda sideways. I just wanted to set the icon via launch arg. You can set fonts, colors, themes, opascities so why not the icon. One teeny tiny icon arg. ;p

Peer Pressure, old URXVT can do it why can't Qterm. ;p

I know you said motivation is nill, trust me I'm there too. Too many years of API rug pulls and various BS has me burned out so I'm just being cheeky. URXVT (with some fancy patching) has been doing just fine. Seems the more time passes the more I go back to stuff from my 1990's BSD era.
