### ISSUE TITLE
Wrong icon with Openbox

### ISSUE THREAD

**Issue by fturco** [lxqt/qterminal#143]
I use QTerminal with the Openbox window manager. I noticed that QTerminal windows don't have the right icon in the top-left corner; they just have the default icon that Openbox uses for applications having no custom icon.
![qterminal](https://cloud.githubusercontent.com/assets/5459866/6885945/83bf4980-d62c-11e4-93a7-20fcaf8b4eaf.png)
The right icon is `/usr/share/pixmaps/qterminal.png`:
![qterminal](https://cloud.githubusercontent.com/assets/5459866/6885950/bd33e8f6-d62c-11e4-8c3d-56e8dee4b3f4.png)

**Comment by pvanek** [comment]
well, what version and what binary package do you use, please? I see correct icon everywhere (3 machines, opensuse, qt5 package for qterminal 0.6)

**Comment by fturco** [comment]
My operating system is Parabola GNU/Linux-libre (an Arch Linux derivative) and I'm using the git version from the AUR:

    $ pacman -Qi qterminal-git | grep Version
    Version        : 0.6.0.42.g0856b29-1

**Comment by pmattern** [comment]
Whenever the apparently correct icon gets displayed it seems in fact to be icon 'utilities-terminal' according to freedesktop's [Icon Theme Specification](http://www.freedesktop.org/wiki/Specifications/icon-theme-spec) as is strongly suggested by deleting all corresponding files in /usr/share/icons while leaving /usr/share/pixmaps/qterminal.png as is.

Icon 'utilities-terminal' probably gets displayed if the choice is related to key 'Icon' in /usr/share/applications/qterminal.desktop somehow. This seems to apply to e. g. LXQt and Xfce.
Openbox in turn doesn't seem to consider that key and displays the fallback icon as a consequence. But the vast majority of applications do have their correct icon displayed in Openbox, too. Btw. this comprises applications placing their icons in /usr/share/pixmaps *only* as well which I first had suspected of being the reason of the issue.

So all in all this looks like there's indeed a problem regarding the interaction QTerminal - window manager. Maybe QTerminal is missing some of the stuff defined in those ["Extended Window Manager Hints"](http://standards.freedesktop.org/wm-spec/latest/), e. g. _NET_WM_ICON[_NAME]?

Same package as used by fturco compiled against Qt 5.4.1 on both Arch Linux i686 and x86_64.

**Comment by pmattern** [comment]
Neither 11799d3 nor 0df5672 (why those two commits?) fix this issue.

I still think what I tried to explain in my previous post should be valid.

**Comment by fturco** [comment]
I rebuild qterminal-git but the problem hasn't been fixed yet.

```
$ pacman -Qi qterminal-git | grep Version
Version        : 0.6.0.65.g7f2c9e0-1
```

**Comment by agaida** [comment]
anyways - far outdated

**Comment by bdantas** [comment]
Ancient as it might be, I was having the same problem. For me, this fixed the issue:

`sudo cp /usr/local/share/icons/gnome-colors-common/24x24/apps/utilities-terminal.png /usr/local/share/icons/hicolor/24x24/apps/utilities-terminal.png`

It seems openbox knows qterminal's icon is named utilities-terminal (bc that's what is in qterminal's .desktop file) but can't find the icon because it doesn't know where to look except in the default "hicolor" icon theme.
