### ISSUE TITLE
qterminal does not display Japanese

### ISSUE THREAD

**Issue by gauthma** [lxqt/qterminal#150]
Almost by chance, I discovered that if I paste Japanese characters into qterminal (or in any editor opened, eg vim), these are simply _not shown_. For example the Japanese word [sayonara](https://en.wiktionary.org/wiki/%E3%81%95%E3%82%88%E3%81%86%E3%81%AA%E3%82%89#Japanese) (さようなら). But I also tried Sanskrit, and these however, _are_ shown. 

Note that as far as I can tell, UTF8 is working properly: accents and other foreign characters are shown. So far the only thing that does not show seems to be Japanese... I am using the latest version from git.

**Comment by jleclanche** [comment]
it works here.

**Comment by pvanek** [comment]
hmm, how to test it, please? I just tried to sopypaste part of word you used with this result:
```
pvanek@spongebob:/opt/pvanek/stsplitter> さような
If 'さような' is not a typo you can use command-not-found to lookup the package that contains it, like this:
    cnf さような
```

**Comment by gauthma** [comment]
OK this is a really weird issue... It's not (just) about qterminal: for some reason it seems to affect all editors using QT!

Before using lxqt, I used KDE. Then I switched to lxqt, but I still use Kwin as a window manager. From what I can see, Japanese characters are not being shown in any terminal or text editor that uses QT: neither in qterminal, nor konsole, nor kate, nor kwrite. But Japanese characters *are* shown in, for instance, gedit, and uxterm! (Even more weird, it does display those characters in Dolphin's (KDE's file manager) address bar...)

I have a vague recollection that it used to work in konsole back when I only had KDE, although I have no idea of what could have changed that would affect Japanese display...

At any rate, this shows that the problem is not with qterminal, which means the bug should be closed, but before doing that, I would really appreciate any suggestions on how to further tackle this issue. Thanks!

**Comment by jleclanche** [comment]
Getting some issues with cjk in qterminal now. Seems like individual character width is not getting calculated correctly.

![screenshot](https://cloud.githubusercontent.com/assets/235410/9609867/66414e88-50d6-11e5-8b96-79f8cb8251ea.png)
![screen01 png](https://cloud.githubusercontent.com/assets/235410/9609890/85bdfefa-50d6-11e5-8028-aec42eaedb5a.jpg)

**Comment by agaida** [comment]
^^ same for me
![screenshot](http://i.imgur.com/3PK9qNw.png)

**Comment by u-ho-bros** [comment]
Same as agaida even in my environment.
It occurred when the latest qtermwidget.
In qtermwidget 0.6.0 was no problem.

**Comment by yan12125** [comment]
Closing as no feedback and no one can reproduce it other than the original poster.
