### ISSUE TITLE
qterminal -d gets invisible when the mouse touches another window

### ISSUE THREAD

**Issue by cjaone** [lxqt/qterminal#153]
1. qterminal -d
2. move the mouse pointer from qterminal directly to a position above the desktop background
   => nothing happens, qterminal is still visible
3. move the mouse pointer to another window
   => qterminal gets invisible

My expectation about this was qterminal staying visible until explicitely making it invisible by pressing F12.

**Comment by stefonarch** [comment]
Could not reproduce -it always stays open until you click on another window or desktop.
