### ISSUE TITLE
new windows opened at same position

### ISSUE THREAD

**Issue by pmattern** [lxqt/qterminal#162]
New windows are always placed at the position of the first window that came up after launching QTerminal, auto-placement mechanisms of window managers aren't taken into account.

Problem can be seen using KWin, Openbox or Xfwm4. Other programs like Konsole, Xfce Terminal, Firefox or LibreOffice aren't affected but place new windows offset.
As it affects the communication between QTerminal and window managers it could somehow be related to #143.

Seen on Arch Linux i686 and x86_64 running QTermWidget and QTerminal from latest Git checkouts, all other components as provided by the distribution's official repositories.

**Comment by pvanek** [comment]
yes, and is it a bug? I wrote it so to keep it opening in the place where I left it last time. And also I don't open more than 1 qterminals as I'm using more tabs and sub-terminals.
So for me it looks like a feature ;)

**Comment by pmattern** [comment]
How to spread a bunch of sessions over tabs and windows and whatsoever may very well be a matter of taste but opening new application windows is a very basic functionality that QTerminal supports as well for a reason.
And if it provides that feature I still can't see any real benefit if it does so in a way different from virtually all other applications.
