### ISSUE TITLE
Extended close confirmation

### ISSUE THREAD

**Issue by Vladimir-csp** [lxqt/qterminal#173]
Hi!
Please extend close confirmation:

Ask confirmation when closing:
- never
- always
- if process is running in terminal

**Comment by jleclanche** [comment]
A confirmation should only ever happen if a process is running, so the config item is unnecessary. Is it possible to do?

**Comment by worblehat** [comment]
This is related to #144.

**Comment by jleclanche** [comment]
Not really.

**Comment by worblehat** [comment]
I  referred to my comment:

> Is there a way to figure if there is a running foreground-process in a tab? We could add an additional confirmation dialog if there is an active process.

If we have a way to figure if there is a running process, we can create a confirmation dialog that can be used for both issues.

**Comment by pvanek** [comment]
this is the problem - how to get running process info for various platforms...

**Comment by Vladimir-csp** [comment]
> this is the problem - how to get running process info for various platforms...

[Sakura](https://launchpad.net/sakura) has a reliable implementation that works on Linux and FreeBSD.

Also #509 is related. Maybe exit warning option could be made into a checklist:
```
Warn on exit when:
[ ] child process(es) running
[ ] multiple tabs open
[ ] always
```
Is 'always' option really needed?

**Comment by mhd-jalilvand** [comment]
And also the prompt do not show when closing the tabs, the prompt is rised only for the first tab or main window.

**Comment by tsujan** [comment]
I don't use close prompt but if it's useful, it should be shown:

 1. When closing the main window; *and*
 2. When closing a tab; *and*
 3. When collapsing sub-terminals.

However, this report is about showing the prompt when a process is running.

**Comment by mhd-jalilvand** [comment]
I have some free time now, let me try to do it

**Comment by mhd-jalilvand** [comment]
> I don't use close prompt but if it's useful, it should be shown:
> 
> 1. When closing the main window; _and_
> 2. When closing a tab; _and_
> 3. When collapsing sub-terminals.
> 
> However, this report is about showing the prompt when a process is running.

I have change the behavior form so the askOnExit is more configurable but not sure how to check out that a process is running or not.
I guess it needs that [a qtermwidget issue](https://github.com/lxqt/qtermwidget/issues/245) must be resolved to achievement the goal.

**Comment by tsujan** [comment]
I think this can be after https://github.com/lxqt/qterminal/pull/1200 is approved and merged. The previous closing prompt didn't make sense without a running process.

**Comment by tsujan** [comment]
Closed in https://github.com/lxqt/qterminal/commit/ff152737c49ec8a0a8e8ea4c6d28646d83defd02
