### ISSUE TITLE
Splitter between bookmarks bar and main pain is always fully transparent

### ISSUE THREAD

**Issue by SchweinDeBurg** [lxqt/qterminal#213]
![transparent-splitter](https://cloud.githubusercontent.com/assets/2083917/14231999/aa456926-f9a9-11e5-9fec-43828e8e9490.png)
1. Linux distro is up-to-date CentOS release 6.7 (Final) 32-bit
2. GCC version 5.3 built by myself from Red Hat release branch
3. Qt RPM packages version 5.5.1-11.el6 are installed from the EPEL repo
4. QTerminal and QTermwidget RPM packages are built by myself from Git master branch
5. Hardware is HP ProBook 4340s with Core i3 CPU, integrated Intel graphics and 8 GB RAM

**Comment by f2404** [comment]
Same as #201
