### ISSUE TITLE
qterminal settings should be modal and always on the top

### ISSUE THREAD

**Issue by agaida** [lxqt/qterminal#217]
one should try to change qterminal settings in drop-down mode - its impossible because the settings are behind the drop-down. It's also impossible to close the settings - same reason.

**Comment by agaida** [comment]
hmm - seems to be modal, but not on top

**Comment by f2404** [comment]
For me, the settings and the menus are shown on top: http://imgur.com/yahqC7b

**Comment by yan12125** [comment]
Works fine in drop down mode with Qt 5.11.2 + git-master of qtermwidget and qterminal.
