### ISSUE TITLE
Split package into a QWidget library and application.

### ISSUE THREAD

**Issue by Levi-Armstrong** [lxqt/qterminal#236]
Hello,

I have currently develop a Qt Creator terminal plugin using the QTermWidget but I would like to implement the QTerminal because of all the extra features. I believe to accomplish this, QTerminal would need to be split into a QWidget library which contains all of the features associated to the tabWidget. Then the application would use the library with add features specific to an application.

To provide a little history, this is to support a [ROS](http://www.ros.org/) project manager Qt Creator plugin that we are currently developing.

Would the developers be open to such a change?

**Comment by jleclanche** [comment]
What's missing from qtermwidget? This is where any needed feature should go.

**Comment by Levi-Armstrong** [comment]
The features I am interested in is the tabWidget with the right click menu's, copy & past capability, splitters, setup dialog, etc. Basically I would like to insert the QTerminal into another application and have the ability to add tabs, change working directory, change environment, ect. from cpp.

**Comment by F1ash** [comment]
it will be nice to have QTerminal as a library. I'm developing qt-virt-manager, which uses QTerminal to manage LXC containers, so I have to copy the code.
