### ISSUE TITLE
Storing terminal properties in a singleton instance

### ISSUE THREAD

**Issue by f2404** [lxqt/qterminal#238]
... which is common for all windows might not be a good idea: apart from possible [segfault](https://github.com/lxde/qterminal/issues/126) after the last opened window is closed, is also makes the settings look incorrectly in the UI after they'd been changed in another window which was closed afterwards.

Example:
- open qterminal window,
- open another window, change the color scheme - it will be changed for the 2nd window, the 1st window's scheme won't change,
- close the 2nd window,
- go to the 1st window's preferences - the color scheme will show the one from the closed window, not the actual one.

I can imagine that there are more that one example of such improper behavior.

**Comment by r-a-v-a-s** [comment]
I support the removal of any or all singletons... ;-]

`Properties::Instance()->actions[CLEAR_TERMINAL]`

Is there any reason the action map can't be a member of the main window?
Writing `Properties::Instance()->` seems to make things much less convenient...
might as well just use QObject's `findChild` if we are going to write that much... >_<

**Comment by f2404** [comment]
Another problem with the Properties singleton is that it's actually not destroyed, and the memory leaks.

**Comment by agaida** [comment]
@yan12125 - is that still an issue?

**Comment by tsujan** [comment]
This was fixed in https://github.com/lxqt/qterminal/commit/78755a23f00e87bd8f126e56492a76127c21f71b
