### ISSUE TITLE
bash_history issues

### ISSUE THREAD

**Issue by f2404** [lxqt/qterminal#248]
qterminal seems to have erased my entire bash history. I've been running it for several days with multiple windows and tabs opened, and at one point I noticed that `~/.bash_history` became empty.
Now (I haven't restarted the terminal) it's not appending to the history anymore.
Looks like a really serious thing here.

**Comment by jleclanche** [comment]
qterminal can't write to that file. your shell's probably messed up.

**Comment by f2404** [comment]
When I run xfce4-terminal, it's able to append to the file.

**Comment by f2404** [comment]
I've closed all qterminal windows. The history is lost.
Newly opened windows are able to append to the history file.

**Comment by yan12125** [comment]
Should have been fixed in https://github.com/lxqt/qtermwidget/pull/171
