### ISSUE TITLE
Is the blue border around Qterminal intentional?

### ISSUE THREAD

**Issue by sudhirkhanger** [lxqt/qterminal#249]
Hi,

Is the blue border around Qterminal intentional? How do I get rid of it? I am using Breeze theme but changing GUI style doesn't do anything.

![screenshot_20160618_221743](https://cloud.githubusercontent.com/assets/841656/16172263/a7a28bb0-35a2-11e6-8e87-de274e2e24aa.png)

**Comment by yan12125** [comment]
Those borders are used to differentiate different sub-terminals. They can be disabled by File -> Preferences -> Appearance -> Show a border around the current terminal.

**Comment by igor-astsakhov** [comment]
I have an issue with tmux, when its launched the bottom keeps updating is there anyway to fix it?

![screenshot from 2016-08-25 12-21-47](https://cloud.githubusercontent.com/assets/2022397/17977161/900df01a-6abe-11e6-99e5-20a65963c346.png)

**Comment by yan12125** [comment]
@igor-astsakhov My QTerminal works fine with tmux. What's the content in your tmux.conf?

**Comment by igor-astsakhov** [comment]
bind r source-file ~/.tmux.conf
source
"~/.local/lib/python2.7/site-packages/powerline/bindings/tmux/powerline.conf"
set-option -g set-titles on
set-option -g set-titles-string 'tmux' # window number,program name,
active(or not)
set -g history-limit 100000
setw automatic-rename off
setw allow-rename off
unbind h
bind h select-pane -L
unbind j
bind j select-pane -D
unbind k
bind k select-pane -U

unbind l # normally used for last-window

bind l select-pane -R

unbind Left

bind -r Left resize-pane -L 5

unbind Right

bind -r Right resize-pane -R 5

unbind Down
bind -r Down resize-pane -D 5
unbind Up
bind -r Up resize-pane -U 5
bind ^a last-window
set -g clock-mode-colour blue
set -g clock-mode-style  24
set -g status-utf8 on
set -g status-bg black
set -g status-fg white
set -g renumber-windows on
set -g default-terminal "xterm-256color"
set -g status on
set -g status-utf8 on
set -g status-interval 2
set -g status-left-length 20
set -g status-right '#(eval $POWERLINE_COMMAND tmux right -R pane_id=`tmux
display -p "#D"`)'
set -g status-right-length 150
set -g window-status-format
"#[$_POWERLINE_WINDOW_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER_SPACES#I
#[$_POWERLINE_WINDOW_DIVIDER_COLOR]$_POWERLINE_LEFT_SOFT_DIVIDER#[default]#W
$_POWERLINE_LEFT_HARD_DIVIDER_SPACES"
set -g window-status-current-format
"#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#[$_POWERLINE_WINDOW_CURRENT_COLOR]#I
$_POWERLINE_LEFT_SOFT_DIVIDER#[$_POWERLINE_WINDOW_NAME_COLOR]#W
#[$_POWERLINE_WINDOW_CURRENT_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER"
set -g status-left "#[$_POWERLINE_SESSION_COLOR] #S
#[$_POWERLINE_SESSION_HARD_DIVIDER_NEXT_COLOR]$_POWERLINE_LEFT_HARD_DIVIDER#(eval
\$POWERLINE_COMMAND tmux left)"
if-shell 'test -z "$POWERLINE_CONFIG_COMMAND"' 'set-environment -g
POWERLINE_CONFIG_COMMAND powerline-config'
run-shell 'eval $POWERLINE_CONFIG_COMMAND tmux setenv'
run-shell 'eval $POWERLINE_CONFIG_COMMAND tmux source'
set-option -qg status-style "$_POWERLINE_BACKGROUND_COLOR"
set-option -qg window-status-last-style
"$_POWERLINE_ACTIVE_WINDOW_STATUS_COLOR"
set-window-option -qg window-status-style "$_POWERLINE_WINDOW_STATUS_COLOR"
set-window-option -qg window-status-activity-style
"$_POWERLINE_ACTIVITY_STATUS_COLOR"
set-window-option -qg window-status-bell-style
"$_POWERLINE_BELL_STATUS_COLOR"
setw automatic-rename off
setw allow-rename off

- I use powerline you think its causing the issue?

**Comment by yan12125** [comment]
>  - I use powerline you think its causing the issue?

Maybe. In my experience qterminal doesn't handle special characters well, and powerline uses them intensively.

**Comment by igor-astsakhov** [comment]
I see, wanted to experience another terminal, and I liked the way it
rendered fonts but it appears that it has the issue with the line
continuously redrawing and not staying at the bottom like it suppose to for
powerline, I like the way powerline looks makes the terminal a bit cooler +
it gives a few apps that can be used. Will play around with it maybe I can
figure it out, I encountered something like this before but I forgot how I
fixed it.

**Comment by mike-pt** [comment]
I've just bumped into the tmux/poweline issue... Is there any plan to fix it?

Should I oepn a separate GHI for the issue?

**Comment by yan12125** [comment]
As far as I can tell @sudhirkhanger's observation is expected. A new issue should be better. I'm not a qterminal, though, so I'm not sure about their conventions.

**Comment by jcc242** [comment]
Looks like there might be an issue with the border on the Find widget? I turned off the border in the settings as mentioned by yan12125. Despite that, you can see in the attached screenshot that there is a thick blue "border" in the Find widget of the focused terminal. I compiled this from github last night.

![qterminal-border](https://cloud.githubusercontent.com/assets/2275469/19010477/1332dea6-873e-11e6-98c2-de6193323cb7.png)

**Comment by jcc242** [comment]
Alright, the thick border on the Find widget annoyed me enough to fix it, see PR #266. Here is a picture with the border option enabled:
![border-after](https://cloud.githubusercontent.com/assets/2275469/19022528/a937a238-8897-11e6-8762-b339339f1f18.png)

And here it is with the border option disabled:
![noborder-after](https://cloud.githubusercontent.com/assets/2275469/19022529/b8a40978-8897-11e6-8641-5f7421251156.png)

**Comment by agaida** [comment]
@jcc242 the marker line for the active window don't has to be blue - but there should be a marker for an active window. (Maybe the line color set by system and/or settings)

**Comment by jcc242** [comment]
@agaida The active window line folros the system theme color, I didn't change anything about that in my patch. The only thing my patch does is decrease the border thickness on the SearchBar widget so it matches the border thickness around the rest of the active terminal, and if the user unchecks the "Show a border around the current terminal" option, then the border will not be drawn on the SearchBar widget. Prior to this patch, even if the "Show a border..." option was unchecked, the border was being drawn on the SearchBar anyway.

**Comment by agaida** [comment]
@yan12125 - what do you think - shall we (1) live with the blue border or (2) use a color frome the activated terminal colors - if (2) - how to achive?

**Comment by tsujan** [comment]
There are 2 wrong things with that search-bar (I had never used it before): those down arrows are senseless and... see:

![qterminal](https://user-images.githubusercontent.com/981076/46581087-72f14e00-ca3e-11e8-9d26-5b915bb1d34d.png)

I resized the left terminal. The blue color mentioned in this report is just related to Breeze.

I'll investigate them if I find time.

**Comment by agaida** [comment]
i know that i (or felixsh) made the "blue border" thinner years ago - it was 4px, now is 2px and it should be hard coded. Must be a commit back in 2012-2014, i guess it was when razor-qt was a relative new project :)

**Comment by yan12125** [comment]
I turn the border off on all my machines. Not sure if it's really necessary.

**Comment by tsujan** [comment]
https://github.com/lxqt/qtermwidget/pull/219 fixes all GUI issues here:

![fixed](https://user-images.githubusercontent.com/981076/46587377-8af5bb80-ca98-11e8-945d-4c1aced96a81.png)


Please see if it also removes the mysterious blue from Breeze!

**Comment by tsujan** [comment]
By "mysterious blue" I mean what's in the screenshot of https://github.com/lxqt/qterminal/issues/249#issuecomment-250882130 , not the focused border.
