### ISSUE TITLE
Windows key in shortcuts

### ISSUE THREAD

**Issue by gauthma** [lxqt/qterminal#258]
I'm not sure that this is a qterminal (rather than lxqt) problem, but here goes: I want to use the windows key for shortcuts; specifically to change back and forth between tabs. However, I am unable to get this to work, even (ab)using xmodmap...

I use lxqt with i3, and if I configure the windows key as the default shortcut, it works as expected -- which means that both win keys are properly recognised. My (tentative...) conclusion is that this must mean that the problem is a qterminal limitation, and hence this ticket. Could make it possible? Thank you.

**Comment by mro** [comment]
same issue here. @jleclanche I looked into https://github.com/lxde/qterminal/blob/master/src/third-party/qxtglobalshortcut_x11.cpp but can't make sense of it.

My question: is the "Windows" key (left of alt) supposed to be supported?

Hardware: PineBook
Os: Ubuntu 16.04.3 LTS (Xenial Xerus)
Window Manager: i3
qterminal: 0.6.0

**Comment by mro** [comment]
@ypnos maybe related to #89 #81 or #51?
