### ISSUE TITLE
Missing configuration to disable alt+fn for dropdown menus

### ISSUE THREAD

**Issue by alive4ever** [lxqt/qterminal#264]
Currently, there is no known way to disable alt+fn to open dropdown menus. This breaks emacs keybinding (notably alt+f to move the cursor to next word and alt+v to scroll page up).

Qterminal should have a configuration to disable parsing alt as modifier to open dropdown menus. The legacy lxterminal has such option, so it doesn't break emacs keybinding.

**Comment by f2404** [comment]
xfce4-terminal still has this ability :)

**Comment by 0xR** [comment]
This seems like a regression, I didn't have this issue before

**Comment by gburnett** [comment]
This is still a problem.  Is it likely to be fixed?

**Comment by agaida** [comment]
ok - these things are called menu accelerators and it is implemented now.
