### ISSUE TITLE
Misleading Translation in Settings - AskOnExit=true|false

### ISSUE THREAD

**Issue by agaida** [lxqt/qterminal#269]
Terminaleinstellungen/Verhalten:
AskOnExit=true|false - (DE) Beim Schließen eines Fensters nachfragen - NÖ!

Möglich wäre die direkte Übersetzung: 
- Vor Beenden des Programs fragen. 
- Beenden von Programm/qterminal bestätigen - würde ich favorisieren

**Comment by stefonarch** [comment]
Would break translations and is clear enough as it is.
