### ISSUE TITLE
Script to open several tabs and execute commands?

### ISSUE THREAD

**Issue by dbautistadecabo** [lxqt/qterminal#283]
In Konsole I can do something like this to open a tab and execute a command (and even set its title):

local session_num=$(qdbus org.kde.konsole /Windows/1 newSession)
qdbus org.kde.konsole /Sessions/$session_num setTitle 0 'myName'
qdbus org.kde.konsole /Sessions/$session_num setTitle 1 'myName'
qdbus org.kde.konsole /Sessions/$session_num sendText 'ssh server'
qdbus org.kde.konsole /Sessions/$session_num sendText $'\n'

Is there a way to acomplish the same in qterminal? I've tried this (with no success):

xdotool key ctrl+shift+t
ssh server

It opens the new tab, but the command executes in the first tab.

Any ideas?

Thanks in advance.

**Comment by yan12125** [comment]
Well, DBus functionalities are removed when QTerminal was initially forked from Konsole due to unknown reasons.

By the way, usually I use tmux for controlling shells.

**Comment by yan12125** [comment]
D-Bus integration reborn in version 0.13! https://github.com/lxqt/qterminal/pull/307

**Comment by yan12125** [comment]
There is an example is a newer related issue: https://github.com/lxqt/qterminal/issues/812. Please move on there for further discussions, thanks!
