### ISSUE TITLE
Default terminal size (not saved at exit)

### ISSUE THREAD

**Issue by sleeksorrow** [lxqt/qterminal#284]
I'd love to be able to set a static default terminal size.

As of now I can either have the default size, which I find a bit too small for my taste and screen setup, or to have it saved at exit, which sometimes leads to having a new terminal showing up in fullscreen just because that was the last size I used.

**Comment by yan12125** [comment]
xfce4-terminal has a --geometry option that overrides default size/position. That may be useful in this case.

**Comment by YoshiRulz** [comment]
While I wouldn't consider this a _solution_ to the mess that is qterminal's window geometry, the (undocumented) -geometry flag is recognized by qterminal. For example, `qterminal --geometry 816x476+275+146` centers a 80x25 terminal on my screen, accounting for the dock.

**Comment by yan12125** [comment]
Thanks that's interesting. I didn't know that option. It is actually handled by Qt [1]:

> -qwindowgeometry geometry, specifies window geometry for the main window using the X11-syntax. For example: -qwindowgeometry 100x100+50+50

And:

> The following standard command line options are available for X11:
> -geometry geometry, same as -qwindowgeometry.

[1] http://doc.qt.io/qt-5/qguiapplication.html

**Comment by tsujan** [comment]
Please follow https://github.com/lxqt/qterminal/issues/492
