### ISSUE TITLE
Feature Req.: automatic selection copy

### ISSUE THREAD

**Issue by mlopezgva** [lxqt/qterminal#296]
I'm used to use a `Terminator`'s feature: if I copy a text, it is automatically copied to the system's clipboard.
It's not hardcoded: it can be toggled in the Preferences (and is on a per-profile basis).

Could be possible to get that...?

**Comment by yan12125** [comment]
Currently copied texts always enter the system's clipboard. Do you want to make copied texts affect QTerminal only?

**Comment by mlopezgva** [comment]
Currently, I have to <kbd>Shift</kbd><kbd>Ctrl</kbd><kbd>C</kbd> to copy selected text to the clipboard. What I am asking for is that the selected text gets copied to the clipboard without intervention, just like **Terminator** does when "Copy on Select" option is enabled.

**Comment by yan12125** [comment]
I've never used Terminator. Here's my guess on what you want:

There are at least two clipboards, namely PRIMARY and CLIPBOARD. When selecting texts in QTerminal, they are copied to PRIMARY and can be pasted to other applications with middle mouse click. When you hit Shift+Ctrl+C, texts are copied to CLIPBOARD and can be pasted with Ctrl+V (in most other applications) or Shift+Ctrl+V (most terminal emulators, including QTerminal).

Seems you want to make selected texts copied to CLIPBOARD, too? That's indeed a useful feature.

**Comment by agaida** [comment]
thats a built-in in qlipper - one could handel p and s separated - it's in the options

**Comment by yan12125** [comment]
@agaida How to do that with qlipper? I see only contents of PRIMARY and CLIPBOARD in qlipper but not options for swapping them.

**Comment by yan12125** [comment]
Aha I found it. That option is in qlipper-git but not in stable qlipper.

@mlopezgva Could you have a try?

**Comment by mlopezgva** [comment]
The goal is to have selected text automatically copied to the "clipboard" (that is, available to other programs) without using the Shift+Ctrl+C sequence.

I don't know about qlipper, I use Cinnamon (work) and XFCE (at home). But if I understand correctly, it will work AFTER I press Shift+Ctrl+C OR swap P <-> S, so it's not very useful.

So, yes, I'm asking for "selected" text  to be immediately copied to the **clipboard** without further intervention, so the selected text becomes immediately available. :-) Also, it would not need to add another program (namely _qlipper_), since I already have _glipper_ installed. :-D

In fact, it seems they do the same thing.

BUT, re-reading your answers, seems like I've been missing the "middle button" feature all these years... It works OUTSIDE the terminal. :worried: 

So may be my request is not as interesting as it sounds at first.

**Comment by yan12125** [comment]
> it will work AFTER I press Shift+Ctrl+C OR swap P <-> S, so it's not very useful.

Just tried it. If you enable instant synchronization in qlipper's options, S are always copied immediately to P without further actions.

I guess glipper may provide similar features :)

**Comment by felixsanz** [comment]
So now i sign up for the request because in my laptop i don't have middle click xD

**Comment by agaida** [comment]
every normal clipboard manager should support this - i'm against implementing it  applicationwise

**Comment by tsujan** [comment]
> every normal clipboard manager should support this - i'm against implementing it applicationwise

+1

**Comment by porjo** [comment]
> @yan12125 wrote:
> There are at least two clipboards, namely PRIMARY and CLIPBOARD. When selecting texts in QTerminal, they are copied to PRIMARY and can be pasted to other applications with middle mouse click. 

I just tried this on Fedora 31 - selecting text in Qterminal and middle click paste into another applciation - doesn't work.

Should select and paste with middle mouse click work _within_ Qterminal? (it doesn't for me)

**Comment by yan12125** [comment]
Did you use wayland?

**Comment by porjo** [comment]
> Did you use wayland?

Yes

**Comment by yan12125** [comment]
Thanks. https://github.com/lxqt/qtermwidget/issues/278 is a better place for discussing middle click under Wayland. Don't forget to include details about your environment (e.g., Qt version/Desktop environment/Wayland compositor/Xwayland enabled or not/what's "another application"/...).

**Comment by pveentjer** [comment]
I would also like to see the feature 'copy on select' that is provided by Terminator. So if you select a piece of text in a terminal, it automatically gets copied to the clipboard. I frequently need to copy ip addresses and open them in a browser and currently there are too many interactions needed.
