### ISSUE TITLE
Untranslated strings

### ISSUE THREAD

**Issue by Chocimier** [lxqt/qterminal#298]
Some strings are untranslated, look at the bottom bar, size popup and action names:
Also title of window for selecting background image is wrong, now says about bookmarks.
![screenshot_20170210_093451](https://cloud.githubusercontent.com/assets/2065803/22820032/42ca9182-ef75-11e6-8571-2919bd07da3a.png)
![screenshot_20170210_093541](https://cloud.githubusercontent.com/assets/2065803/22820033/42cb296c-ef75-11e6-973e-c4bbfdf97991.png)
![screenshot_20170210_093914](https://cloud.githubusercontent.com/assets/2065803/22820031/429796ce-ef75-11e6-9894-d50925636470.png)

**Comment by yan12125** [comment]
Thanks for all of those findings! Now the size hint and search options are translatable. The last part is shortcut names.

> Also title of window for selecting background image is wrong, now says about bookmarks.

You got it. Fixed in 49d57a7.

**Comment by stefonarch** [comment]
> Now the size hint and search options are translatable.

Why  don't I see them in .ts files with
option(UPDATE_TRANSLATIONS "Update source translation translations/*.ts files" ON) ?

**Comment by agaida** [comment]
if such things are noticed - use weblate - if the strings are not translateable - file a bug about needed source changes
