### ISSUE TITLE
Qterminal 0.7.1 dropdown, crash on font changing

### ISSUE THREAD

**Issue by Nhoya** [lxqt/qterminal#314]
Step to reproduce:
Open qtterminal dropdown, open settings, and change the font (i used fira-code) press apply and it crash. 

This issue will not affect the non-dropown terminal

**Comment by klundry** [comment]
Confirmed.  I can open qterminal and change the font, then the dropdown terminal will accept it.  Trying to change it within the dropdown terminal preferences crashes it.

**Comment by yan12125** [comment]
Confirmed. As the terminal exits without any error, it's somewhat tricky to debug...

**Comment by agaida** [comment]
thats one of the know glitches in the Drop-Down-Implementation. I filed a bug about modal setting windows and so on times ago.

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/qterminal/commit/004f1ddb8ca828399aa6f9b56b608199f9dddc8b
