### ISSUE TITLE
Qterminal 0.7.1 dropdown is buggy

### ISSUE THREAD

**Issue by Nhoya** [lxqt/qterminal#316]
I'm using Qterminal with KDE5 on arch, i use the dropdown and sometimes pressing the key to make it disappear it will just flash, i'v to press the key multiple times, i'm not sure if the issue is related to Qterminal or KDE5

**Comment by yan12125** [comment]
Could you try with the latest commit? (for example qterminal-git and qtermwidget-git in AUR) The latest commit works fine here on Arch with LXQt.

**Comment by Nhoya** [comment]
same issue with qterminal-git

**Comment by yan12125** [comment]
Sounds I have to install KDE to test it. I guess the key difference between KDE and LXQt is the global shortcut listener, KGlobalAccel and lxqt-globalkeys.

**Comment by pmattern** [comment]
I can reproduce this in a virtual machine featuring LXQt as the only desktop environment with lxde/qtermwidget@1f7f9f8 and lxde/qterminal@d454a00 assigning `F12` as key to toggle the drop-down terminal. Didn't figure out when exactly the problem takes place yet.

**Comment by yan12125** [comment]
@pmattern Does that use Openbox? My next guess is KWin.

**Comment by Nhoya** [comment]
The issue is not related to the key pressed (has the dame behavior with alla the `F[1-12]` keys

**Comment by pmattern** [comment]
My findings were under Openbox. Meanwhile I made the same findings running the commits as mentioned [above](https://github.com/lxde/qterminal/issues/316#issuecomment-289580781) "bare metal" as well.
Btw. a roughly similar issue affecting lxqt-runner has been addressed in lxde/lxqt-runner#43.

**Comment by klundry** [comment]
I can confirm that I experience this as well.  It seems sporadic almost like it is detecting multiple keypresses of the shortcut key.  I believe the flash is it quickly closing and reopening.

**Comment by DennPo** [comment]
Confirm. Gentoo + LXQt

**Comment by monetaryabyss** [comment]
This has also been observed in [Lubuntu 18.10](https://bugs.launchpad.net/ubuntu/+source/qterminal/+bug/1795998)

**Comment by yan12125** [comment]
Merged into the newer bug report #491 - there are more details there.
