### ISSUE TITLE
Parameter to assign WM_CLASS

### ISSUE THREAD

**Issue by felixsanz** [lxqt/qterminal#334]
I'm using i3 as WM and i'd like to auto-launch htop inside qterminal (for example). And also assign it to the workspace 10 by default.

I can do the first with `qterminal -e htop`. The problem is that the title doesn't change, it remains at "qterminal". So i can't target the window inside i3 so it's moved to the workspace 10. Example i3 config: `assign [instance="htop"] $ws10`.

It would be useful a parameter like `-n --name` so i can use it like `qterminal -e htop -n htop`, and then i'd be able to inspect the window using `xprop` and get `WM_CLASS(STRING) = "htop", "qterminal"` instead of `WM_CLASS(STRING) = "qterminal", "qterminal"`.

**Comment by yan12125** [comment]
Seems WM_CLASS is different than the window title? In zsh with oh-my-zsh, the title is updated when a command is run, but the WM_CLASS string is still "qterminal", "qterminal".

Here's what I got from xprop if I run htop in zsh. WM_NAME looks good here.
```
$ xprop
_NET_WM_USER_TIME(CARDINAL) = 4549968
_NET_WM_ICON_GEOMETRY(CARDINAL) = 782, 719, 216, 49
WM_STATE(WM_STATE):
                window state: Normal
                icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_SHADE, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_MOVE, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW, _OB_WM_ACTION_UNDECORATE
_KDE_NET_WM_FRAME_STRUT(CARDINAL) = 0, 0, 25, 0
_NET_FRAME_EXTENTS(CARDINAL) = 0, 0, 25, 0
_NET_WM_STATE(ATOM) = _NET_WM_STATE_MAXIMIZED_VERT, _NET_WM_STATE_MAXIMIZED_HORZ
_OB_APP_TYPE(UTF8_STRING) = "normal"
_OB_APP_TITLE(UTF8_STRING) = "Shell No. 1"
_OB_APP_GROUP_CLASS(UTF8_STRING) = 
_OB_APP_GROUP_NAME(UTF8_STRING) = 
_OB_APP_CLASS(UTF8_STRING) = "qterminal"
_OB_APP_NAME(UTF8_STRING) = "qterminal"
_OB_APP_ROLE(UTF8_STRING) = 
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "htop"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "htop"
_NET_WM_ICON(CARDINAL) =        Icon (22 x 22):
                              
                              

                            
          
          
          
          
          
          
          
          
          
          
          
          
          
                            


          
                              

        Icon (32 x 32):
                                        
                                        
                                        
                                        
             
           
                                      
             
             
             
             
             
             
             
             
             
             
             
             
             
             
             
             
             
             
                                      
           
           
           
            
                                        
                                        

        Icon (24 x 24):
                                
                                
                                
          
                              
            
            
            
            
            
            
            
            
            
            
            
            
            
                              
          
          
            
                                
                                

        Icon (16 x 16):
                        

                      
          
          
           
           
           
          
          
          
          
          
                      

                        


_NET_WM_ICON_NAME(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
WM_NAME(STRING) = "htop"
_NET_WM_NAME(UTF8_STRING) = "htop"
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x3, 0x3e, 0x7e, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_XEMBED_INFO(_XEMBED_INFO) = 0x0, 0x1
WM_CLIENT_LEADER(WINDOW): window id # 0x2200007
WM_HINTS(WM_HINTS):
                Client accepts input or input focus: True
                Initial state is Normal State.
_NET_WM_PID(CARDINAL) = 7460
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 35651590
WM_CLASS(STRING) = "qterminal", "qterminal"
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_NORMAL_HINTS(WM_SIZE_HINTS):
                user specified location: 0, 0
                user specified size: 1366 by 693
                program specified minimum size: 127 by 67
                window gravity: NorthWest
```

**Comment by felixsanz** [comment]
Mmm yeah, i meant `WM_CLASS`

**Comment by yan12125** [comment]
Apparently it requires X11-specific codes. It should be possible but I'm reluctant to add it as the whole world is moving to Wayland.

**Comment by felixsanz** [comment]
Wayland won't be ready within the next years, so...

**Comment by concatime** [comment]
I'm using Sway which uses Wayland, and facing the same issue. This have nothing to do with X11/Wayland.

**Comment by yan12125** [comment]
Do you know how Sway uses WM_CLASS? Is XWayland involved?

**Comment by concatime** [comment]
Sway/i3 use WM_CLASS to identify a window and assign it a workspace. For example, each time your run Firefox, it will automatically launch in the X'th workspace.

**Comment by concatime** [comment]
Also, when setting `QT_QPA_PLATFORM=wayland`, `WM_CLASS` is null, and `app_id` is `qterminal`.

**Comment by paoloschi** [comment]
> It would be useful a parameter like `-n --name` so i can use it like `qterminal -e htop -n htop` [...]


I adopted _qterminal_ for the first time a few weeks ago -by the way, I really like it!!- and I was in a similar situation.
I'm on Void Linux and I run qterminal 0.14 installed from the official repository.
I wanted to create window rules using the program _ruler_ for the window-manager _windowchef_ and I couldn't do that accurately as title and/or property WM_NAME, according to `qterminal -h`, do not seem to have dedicated options...
Insisting on my attempts, __I've figured out how to do it now__! The solution, from the point of view of a developer, I imagine is trivial but I don't see it reported in previous posts, so I thought I'd report that in fact a `--name` option __can already be set__! And not only that...

```
qterminal --name foo --title bar [OPTION]...
```

or with a single dash also works

```
qterminal -name foo -title bar [OPTION]...
```

__both works for me__: now I can set both the WM property and the title of the window qterminal that I'm opening! :-)
It seems that there are therefore global options that qterminal assumes. I tried to use the same launching another Qt application: `featherpad -name foo -title bar` but in this case, although there is no warning or error, the properties remain unchanged.
Finally, I specify that I have not experienced if all this also applies to Wayland too.

**Comment by yan12125** [comment]
Awesome findings!

The `-name` argument is processed in Qt's XCB plugin [1]. Clearly it's for X11 only and there are no side effects other than overriding `WM_CLASS`.

On Wayland apparently another property `app_id` plays a similar role [2]. That propoerty can't be overwritten at runtime, though [3].

Closing this ticket as there are nothing to do for qterminal. Feel free to leave a comment or open a new issue once qtwayland supports overriding `app_id`.

[1] https://github.com/qt/qtbase/blob/v5.12.3/src/plugins/platforms/xcb/qxcbintegration.cpp#L161
[2] https://github.com/jwilm/alacritty/blob/v0.3.2/src/window.rs#L284-L287
[3] https://github.com/qt/qtwayland/blob/v5.12.3/src/client/qwaylandwindow.cpp#L156-L176
