### ISSUE TITLE
Strange space between wide characters and box-drawing characters

### ISSUE THREAD

**Issue by redbug312** [lxqt/qterminal#344]
##### Expected Behavior

On gnome-termnal and konsole, when typing:
```
$ 1234567890     2> /dev/null
$ 中文││││││     2> /dev/null
$ Engl││││││     2> /dev/null
```
It shows:
![gnome-terminal-test](https://user-images.githubusercontent.com/11537681/28617097-9d302ac6-7231-11e7-9ee0-296b1dc3ccd7.png)

##### Current Behavior

On qterminal, it shows a strange space only between them:
![qterminal-test](https://user-images.githubusercontent.com/11537681/28617152-d5a9f13e-7231-11e7-9c7d-340d15c5a942.png)
But it goes well in reverse order as `││││││中文`

##### Possible Solution

I’m not sure if this problem related to #150 issue

##### Steps to Reproduce (for bugs)

Type the 3 strings below in qterminal:
```
$ 1234567890     2> /dev/null
$ 中文││││││     2> /dev/null
$ Engl││││││     2> /dev/null
```

##### Context

In Vim, my seperator is set to the box-drawing character `│`
If there’s wide characters (Mandarin in my case) on left, it lefts a black hole on the seperator
![qterminal-vim](https://user-images.githubusercontent.com/11537681/28617360-a28be446-7232-11e7-8859-6ab5103a5b72.png)

##### System Information

* Distribution & Version: Ubuntu 17.04
* Kernel: 4.10.0-28-generic
* Package version: 0.7.1

**Comment by yan12125** [comment]
Hello, could you try recompiling qtermwidget with this branch https://github.com/lxde/qtermwidget/tree/fix-irregular-text-width? That fixes the layout of 3 strings mentioned in steps to reproduce.

**Comment by yan12125** [comment]
By the way, layout is still broken with CJK and tig: https://github.com/jonas/tig/issues/748. As the bug reproduces on at least xterm, konsole and xfce4-terminal (vte3), I guess it not a qterminal issue.

**Comment by RedBug312** [comment]
Hi, I tried recompiling the branch but now it shows
```
$ qterminal
qterminal: symbol lookup error: qterminal: undefined symbol: _ZN11QTermWidget22setKeyboardCursorShapeEN7Konsole9Emulation19KeyboardCursorShapeE
```
I've installed `libqt5x11extras5-dev` and `libglib2.0-dev`, compiled `lxqt-build-tools`, the branch of `qtermwidget` and `qterminal` for it.

**Comment by yan12125** [comment]
Hmm, maybe there are some old qtermwidget libraries? Check with this:
```
ldd $(which qterminal) | grep qtermwidget
```
Make sure that path points to the just built qtermwidget.

**Comment by RedBug312** [comment]
I opened qterminal on `$ env LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" gnome-terminal`.
The library path is changed and it ran, but not fixed the bug.

**Comment by yan12125** [comment]
Did you mean pasting the following three lines:
```
$ 1234567890     2> /dev/null
$ 中文││││││     2> /dev/null
$ Engl││││││     2> /dev/null
```
into vim still results in strange spaces? That would be strange as the simple test case works fine for me. If this works but vertical lines in your vim is still broken, could you share your ```.vimrc```? I'd like to test a more complicated usage.

**Comment by RedBug312** [comment]
It happened on both bash and vim in qterminal with`.vimrc` removed.
Maybe I just failed on compiling qterminal. 😕

**Comment by tsujan** [comment]
Sadly, good reports like this are buried under lots of unimportant ones.

I tested https://github.com/lxde/qtermwidget/tree/fix-irregular-text-width (after adapting it to the latest code). It didn't fix the problem.
