### ISSUE TITLE
appstream metadata format and location are legacy

### ISSUE THREAD

**Issue by agaida** [lxqt/qterminal#346]
##### Expected Behavior
No warnings or bugs from lintian

##### Current Behavior
```
W: qterminal: appstream-metadata-in-legacy-location usr/share/appdata/qterminal.appdata.xml
E: qterminal: appstream-metadata-legacy-format usr/share/appdata/qterminal.appdata.xml
```
##### Context And Possible Solution
> Hi, some lintian whining - unfortunately lintian is right most of the time: https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html

**Comment by stefonarch** [comment]
Fixed in https://github.com/lxqt/qterminal/pull/901
