### ISSUE TITLE
Shift+Up/Down/Right/Left not working as expected in Emacs/OrgMode

### ISSUE THREAD

**Issue by fturco** [lxqt/qterminal#348]
I'm using QTerminal 0.7.1 on a Gentoo Linux system. I noticed an issue with Emacs/OrgMode under QTerminal. I cannot use the Shift+Up/Down/Right/Left keyboard shortcuts for selecting a date in the Emacs calendar. When I try to do that nothing happens. I tried both the "default" and "linux" emulation types. Their behaviour seems identical. What else can I try? Is this a bug or expected behavior?

* Qt version: 5.9.1
* qtermwidget version: 0.7.1

Edit: the same problem happens with qterminal/qtermwidget latest git version, too.

**Comment by pvanek** [comment]
These shortcuts are used for switching splitted terminal subwindows or tabs

**Comment by fturco** [comment]
I tried disabling all shortcuts in QTerminal but Shift+Up and Shift-Down still don't work in Emacs.

**Comment by yan12125** [comment]
Shift+Up/Down doesn't work in neovim 0.2.0.r685.g1f9c139fd, either. Sounds like a bug.

**Comment by yan12125** [comment]
I created a possible fix at https://github.com/lxde/qtermwidget/tree/implement-keyboard-command-handling.

**WARNING:** I haven't verified that my changes won't break other things. If you found anything strange, please tell me, thanks!

**Comment by fturco** [comment]
@yan12125: I can't build qterminal anymore after having switched to the `implement-keyboard-command-handling` branch in qtermwidget.

```
[ 61%] Building CXX object CMakeFiles/qterminal.dir/src/mainwindow.cpp.o
/usr/bin/x86_64-pc-linux-gnu-g++ -DHAVE_QDBUS -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_GUI_LIB -DQT_NO_DEBUG -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_X11EXTRAS_LIB -DSTR_VERSION=\"0.7.1\" -DTRANSLATIONS_DIR=\"/usr/share/qterminal/translations\" -I/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999 -I/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src -I/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999_build -I/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src/third-party -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtCore -isystem /usr/lib64/qt5/mkspecs/linux-g++ -isystem /usr/include/qtermwidget5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtDBus -isystem /usr/include/qt5/QtX11Extras   -DNDEBUG -O2 -march=native -pipe -fno-exceptions -Wall -std=c++11 -fvisibility=hidden -fvisibility-inlines-hidden   -fPIC -std=gnu++11 -o CMakeFiles/qterminal.dir/src/mainwindow.cpp.o -c /var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src/mainwindow.cpp
In file included from /usr/include/qtermwidget5/qtermwidget.h:25:0,
                 from /var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src/termwidget.h:22,
                 from /var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src/termwidgetholder.h:23,
                 from /var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999/src/mainwindow.cpp:33:
/usr/include/qtermwidget5/Emulation.h:39:10: fatal error: KeyboardTranslator.h: No such file or directory
 #include "KeyboardTranslator.h"
          ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/qterminal.dir/build.make:279: CMakeFiles/qterminal.dir/src/mainwindow.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory '/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999_build'
make[1]: *** [CMakeFiles/Makefile2:68: CMakeFiles/qterminal.dir/all] Error 2
make[1]: Leaving directory '/var/tmp/portage/x11-terms/qterminal-9999/work/qterminal-9999_build'
make: *** [Makefile:130: all] Error 2
```

**Comment by yan12125** [comment]
Thanks for the feedback. I've updated that branch and it should be fixed now.

**Comment by fturco** [comment]
It seems to work now. Thanks for the fix!

**Comment by david-tamar** [comment]
It's 11 March 2020, on Debian Sid, QTerminal interferes with Midnight Commander's Shift+Up/Down file selection.

**Comment by hsandor** [comment]
I have the same problem with micro editor, text selection with shift+up/down/left/right arrows doesn't work. xfce4-terminal works, qterminal blocks shift keys. Void Linux, Qt 5.15.0, qterminal 0.15.0.
