### ISSUE TITLE
Preconfiguration setting does not work

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#351]
In Preferences: selecting "Start with preset: none, 2 horizontally, 2 vertically" and so on has no effect, always one single terminal is opened.

##### Expected Behavior

In preferences dialog when  "Start with preset: 2 terminals horizontally|vertically|4 terminals " is chosen a new window should open with the selected preset.

##### Current Behavior

   Preset stays "none" always

##### Steps to Reproduce (for bugs)

1. Open preferences, go to "Start with preset:"
2. Select one of the  options with  2 or 4 terminals
3. Save and exit
4. Open a new window

##### System Information

* Distribution & Version: arch up to date
* Qt Version: 5.9.1-3
* libqtxdg Version:  latest git 
* qtermwidget Version: latest git 
* lxqt-build-tools Version: latest git 
* Package version: latest git 
issue is the same with official arch packages.

**Comment by yan12125** [comment]
#352 should have fixed this bug. Could you give it a try?

**Comment by stefonarch** [comment]
Works perfectly, I've just compiled the branch, thanks you're fast ;)

**Comment by stefonarch** [comment]
PS: I just saw now that for 4 terminals it doesn't split regularly as it does  in "new tab with preset-4 terminals"
![schermata-29-17-33-14](https://user-images.githubusercontent.com/10681413/29829741-794b434c-8ce0-11e7-9ffb-9cf15b7bd0bc.png)
.
See picture

**Comment by yan12125** [comment]
I got wrong 4-subterminal layouts, too. Mysterious :/

**Comment by stefonarch** [comment]
Better like that than nothing :)
No idea if this is related but focus with 2 terminals spli horizontally is on the bottom one, would be nice to have it in the upper one.

**Comment by lukebakken** [comment]
For what it's worth, this issue is still present using QTerminal `0.14.0`. It would be nice to be able to open a new terminal with at least one split. Fixing the four-terminal case can wait in my opinion.

**Comment by deathtrip** [comment]
There's pull request #352 waiting for so long :/

**Comment by Endoisshy** [comment]
Still doesn't work in 0.16.0. Please fix this would be really nice to have as I always split into 4 terminals.
