### ISSUE TITLE
Make active tab somehow darker/lighter than the non active tabs (make active noticeable)

### ISSUE THREAD

**Issue by je-vv** [lxqt/qterminal#356]
I'm currently using Arch, and I'm using qterminal under fluxbox + compton + qt5c + arc-gtk-theme, and one annoying thing is that it's hard to make a difference by looking at the tabs which is the active one.

Granted using the "windows" widget style makes the "closing tab button" red on active, but the difference should be noticed regardless of the style, and perhaps darker/lighter is an easy approach, :)

##### System Information

* Distribution & Version:  Arch GNU/Linux (up to date)
* Kernel:   4.12.13
* Qt Version:  5.9.1
* libqtxdg Version:  2.0.0 
* qtermwidget Version:  0.7.1
* lxqt-build-tools Version:  0.3.2 (not installed)
* Package version:  0.7.1

**Comment by yan12125** [comment]
Could you paste a screenshot like this? Not quite sure what qterminal looks like under your configuration.
![default](https://user-images.githubusercontent.com/1937689/30631452-d326b3e6-9e16-11e7-91a8-e6ed02edbef6.png)

**Comment by je-vv** [comment]
![image](https://user-images.githubusercontent.com/10799432/30632032-e0d545c0-9da3-11e7-8a61-42906c0b82bf.png)

**Comment by je-vv** [comment]
Just in case, the .config/qterminal.org/qterminal.ini file:

[General]
AskOnExit=false
BookmarksFile=/home/general/.config/qterminal.org/qterminal_bookmarks.xml
BookmarksVisible=true
Borderless=false
ChangeWindowIcon=true
ChangeWindowTitle=true
HideTabBarWithOneTab=false
HistoryLimited=true
HistoryLimitedTo=1024
KeyboardCursorShape=0
MenuVisible=false
MotionAfterPaste=0
SavePosOnExit=true
SaveSizeOnExit=true
ScrollbarPosition=2
TabBarless=false
TabsPosition=0
TerminalBackgroundImage=
TerminalTransparency=25
TerminalsPreset=0
UseBookmarks=false
UseCWD=false
colorScheme=WhiteOnBlack
emulation=default
font=@Variant(\0\0\0@\0\0\0\x1a\0x\0o\0s\0\x34\0 \0T\0\x65\0r\0m\0i\0n\0u\0s@ \0\0\0\0\0\0\xff\xff\xff\xff\x2\x1\0\x32\x10)
guiStyle=qt5ct-style
highlightCurrentTerminal=false
version=0.7.1

[DropMode]
Height=50
KeepOpen=false
ShortCut=F12
ShowOnStart=true
Width=99


[MainWindow]
ApplicationTransparency=5
pos=@Point(0 0)
size=@Size(1360 718)
state=@ByteArray(\0\0\0\xff\0\0\0\0\xfd\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\xfc\x2\0\0\0\x1\xfb\0\0\0&\0\x42\0o\0o\0k\0m\0\x61\0r\0k\0s\0\x44\0o\0\x63\0k\0W\0i\0\x64\0g\0\x65\0t\0\0\0\0\0\xff\xff\xff\xff\0\0\0\x9b\0\xff\xff\xff\0\0\x5P\0\0\x2\xb6\0\0\0\x4\0\0\0\x4\0\0\0\b\0\0\0\b\xfc\0\0\0\0)

[Sessions]
size=0

[Shortcuts]
Add%20Tab=Ctrl+Shift+T
Clear%20Active%20Terminal=Ctrl+Shift+X
Close%20Tab=Ctrl+Shift+W
Collapse%20Subterminal=
Copy%20Selection=Ctrl+Shift+C
Find=Ctrl+Shift+F
Fullscreen=F11
Hide%20Window%20Borders=
Move%20Tab%20Left=Alt+Shift+Left|Ctrl+Shift+PgUp
Move%20Tab%20Right=Alt+Shift+Right|Ctrl+Shift+PgDown
New%20Window=Ctrl+Shift+N
Next%20Subterminal=Shift+Up
Next%20Tab=Shift+Right|Ctrl+PgDown|Ctrl+Tab
Paste%20Clipboard=Ctrl+Shift+V
Paste%20Selection=Shift+Ins
Preferences...=Ctrl+Shift+P
Previous%20Subterminal=Shift+Down
Previous%20Tab=Shift+Left|Ctrl+PgUp|Ctrl+Shift+Tab
Quit=
Rename%20Session=Alt+Shift+S
Show%20Tab%20Bar=
Split%20Terminal%20Horizontally=
Split%20Terminal%20Vertically=
Toggle%20Bookmarks=Ctrl+Shift+B
Toggle%20Menu=Ctrl+Shift+M
Zoom%20in=Ctrl++
Zoom%20out=Ctrl+-
Zoom%20reset=Ctrl+0

**Comment by yan12125** [comment]
I haven't investigated a lot. Maybe a custom QSS stylesheet at ```~/.config/qterminal.org/style.qss``` can help.

**Comment by agaida** [comment]
done
