### ISSUE TITLE
Impossible to open the Bookmarks panel

### ISSUE THREAD

**Issue by dglent** [lxqt/qterminal#377]
##### Expected Behavior
With Ctrm+Shift+B or with the menu <Show><Toggle Bookmarks> the panel with Bookmarks should open

##### Current Behavior
Nothing happens

##### Steps to Reproduce (for bugs)
Reproducible always.

##### System Information
* Distribution & Version: Mageia 6
* Kernel: 4.9.56-desktop-1.mga6
* Qt Version: 5.6.2
* libqtxdg Version:  3.1.0
* qtermwidget Version: 0.8.0
* lxqt-build-tools Version: 0.4.0
* Package version: 0.8.0

**Comment by poikilos** [comment]
@agaida  I have this issue in GNOME 3.30.2 on Fedora 29 (it worked in Xfce).
Qt version 5.11.3
QTerminal version 0.9.0

**Comment by yan12125** [comment]
To toggle the boomarks panel, right click on the menu bar. There's an option in the popup menu.

It's far from intuitive IMO. I suggest moving the option under the View menu (and optionally bind it with Ctrl+Shift+B).

**Comment by poikilos** [comment]
@yan12125 thanks for pointing that out. I'll be sure to use that for now. The view menu already says Ctrl+Shift+B is the shortcut but it doesn't work and neither does that menu item--I'm just letting you know.

**Comment by yan12125** [comment]
Aha, this turns out a simple bug, which will be fixed after https://github.com/lxqt/qterminal/pull/584.
