### ISSUE TITLE
F1–F5 keys is blocked

### ISSUE THREAD

**Issue by unclechu** [lxqt/qterminal#38]
In the terminal can't use F1–F5 keys, in any application (vim, midnight commander, etc).

**Comment by yan12125** [comment]
All of F1-F12 work with the git-master of qtermwidget and qterminal using the default emulation. You can check it by hitting Ctrl+V and then one of F1-F12 to see raw escape sequences in zsh.

**Comment by tanius** [comment]
For anyone experiencing the same symptoms still: it is probably a mismatch between the emulation type and $TERM settings in qterminal (under "File → Preferences → Behavior").

For example, by default emulation type was `linux` for me but $TERM was set to `xterm-256color`. The two differ in the escape codes assigned to F1-F5. So an application with hotkeys in the F1-F5 range (like `byobu`) will expect escape codes as defined for `xterm-256color` but get those for `linux` (which it would not understand, and consequently do nothing). See #551 for more details and a proposed solution.
