### ISSUE TITLE
Parts of the screen that should be cleared aren't; only in tmux

### ISSUE THREAD

**Issue by dubhater** [lxqt/qterminal#393]
##### Current Behavior
![2018-01-26-111205_1280x755_scrot](https://user-images.githubusercontent.com/1739488/35435610-141a6bae-0294-11e8-9e71-5a019bd7db6c.png)

##### Expected Behavior
![2018-01-26-123142_1280x755_scrot](https://user-images.githubusercontent.com/1739488/35435869-fd64b314-0294-11e8-8ad5-c49919dc9bc3.png)

##### Steps to Reproduce
1. Open QTerminal
2. Start tmux
3. Open some file with vim
4. Press Page Down then Page Up

This doesn't happen if tmux isn't used.

I didn't see anything relevant in the list of commits since 0.8.0, so I didn't try to compile from git.

##### System Information
* Distribution & Version: Arch Linux
* Kernel: 4.14.13
* Qt Version: 5.10.0
* libqtxdg Version: ?? Can't find it. 
* qtermwidget Version: 0.8.0
* lxqt-build-tools Version: 0.4.0
* Package version: 0.8.0

**Comment by yan12125** [comment]
Most likely this is already fixed in https://github.com/lxde/qtermwidget/commit/8a3a9a40cb071ca001f79e0192e0934e19628bd1.

**Comment by yan12125** [comment]
Closing as no response for a long time. Please leave a comment if this is still an issue in the latest git-master of qterminal/qtermwidget.
