### ISSUE TITLE
Wrong rendering of bitmap font "terminus"

### ISSUE THREAD

**Issue by tojamrok** [lxqt/qterminal#407]
##### Current Behavior
There are visual glitches at the right edge and bottom edge of every glyph of Terminus bitmap font.
[image]https://user-images.githubusercontent.com/16987182/36926940-b3519e20-1e7a-11e8-8c4e-5400f6a1a6c8.png

##### Steps to Reproduce (for bugs)
1. Install terminus font from https://sourceforge.net/projects/terminus-font/files/ 
2. Run `fc-cache -fv`.
3. In qterminal change font to terminus.

##### System Information
* Distribution & Version: Xubuntu 14.04.5 and Xubuntu 14.04.
* Kernel: 4.4.0-116-generic but a lot of others as well
* Qt Version: 5.2.1
* libqtxdg Version:  ?
* qtermwidget Version: ?
* lxqt-build-tools Version: ?
* Package version: 0.6.0

**Comment by agaida** [comment]
Current version is 0.9 - and there is a new LTS
