### ISSUE TITLE
Vertical tabs are not usable

### ISSUE THREAD

**Issue by aramazano** [lxqt/qterminal#409]
Upgraded to qterminal 0.8.1~36-g1a4452a-1 and the tabs have become very large (plus statically sized as before). 

Each tab is like half the width of fullscreen size. Only 2 tabs can fit in the tab bar, 3rd tab overflows it. It gets worse when the tab bar is located on right or left of the window: Tabs keep their enormous widths, but they also get very deep, and neighboring tab titles get superimposed on one another when scrolling through tab-bar downwards.

Before the upgrade (qterminal_0.8.0-4) statically sized tabs were already an inconvenience (opening 5 tabs were enough to overflow the tab bar). Now with gigantic tab sizes the terminal has become barely usable.

I would like to use this opportunity to ask please also make the tabs dynamically sized. With statically sized tabs, it becomes inconvenient to use more than 5 tabs here. (Now it is dropped to 2). I know it is possible scroll through tabs, but it is an inconvenient hassle.

Thank you and regards.

##### System Information
* Distribution & Version:  LXQt experimental-snapshots on top of Debian Testing
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~13-gb5ddbd4-1
* qtermwidget Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* Package version: 0.8.1~36-g1a4452a-1 (About dialog: 0.8.0)

**Comment by aramazano** [comment]
My bad. I did look into the settings but missed that one somehow. Nevertheless, I would suggest making this option unchecked by default.

BTW the other, "opportunistic" request (re dynamic/squeezing tab sizes) still pending. :)

**Comment by aramazano** [comment]
Hmm there is still this issue;

> It gets worse when the tab bar is located on right or left of the window: Tabs keep their enormous widths, but they also get very deep, and neighboring tab titles get superimposed on one another when scrolling through tab-bar downwards.

There are 3 problems with "vertical" tabs.

1) Normally, the width of vertical tab bar should always be slim (like the height of horizoltal bar) and "Limit tab width" should affect its vertical width (depth). Actually it works as;

a) the -vertical- width (depth) of vertical tabs are always *fixed* (apparently equal to the length of horizontal tabs as if "limit tab width" unchecked), and

b) "Limit tab width" affects the horizontal width of vertical tab bar, while it should have affected the depth (vertical width).

2) Tab titles in vertical bars are still laid in horizontal axis. So titles don't fit in the horizontal space.

3) All the titles of tabs are shown in the topmost tab, superimposed on one another, and the rest of tabs have no title. Possibly related somehow to (2).

**Comment by tsujan** [comment]
Oh, I think no one had used vertical tabs. THEY ARE TERRIBLE. Let's change the title and make this like a real bug report.

**Comment by aramazano** [comment]
I think vertical tabs can have a very good use case, provided that;

1) Tab titles are still laid out in horizontal axis,
2) "Tab width" still means horizontal length,
3) Tab heights are slim and fixed (as in horizontal tabs).

This is like running featherpad in side-pane mode. Tens of terminal sessions can be handled easily this way.

Current practice of rotated vertical tabs are not very useful IMHO. But, it would be a really useful feature, if laid out like side-pane of fpad.

**Comment by tsujan** [comment]
@aramazano This is definitely a bug but, maybe, not in the way you see it:

> This is like running featherpad in side-pane mode

There's no "side-pane mode" with QTerminal. A side-pane is a list-view, not a list of tabs. This bug is about vertical tab labels. If you want a side-pane mode with QTerminal, please open a separate feature request for it.

**Comment by tsujan** [comment]
GitHub is great in showing connections. If you add a link to report Y in report X, GitHub will add a link to X in Y.
