### ISSUE TITLE
Interpretation of "Limit tab width:" setting

### ISSUE THREAD

**Issue by aramazano** [lxqt/qterminal#411]
Currently the aforementioned setting actually works as "fixed tab width". For instance, when set to 500px, then even if I rename the session as "i" (minimal horizontal space needed) the tab is still 500 pixels in length.

Instead, I would suggest a behavior like this:

There is no enable/disable option (always enabled), but just a limit setting (always effective).

##### With top/bottom horizontal tab bar:

It places a LOWER limit to dynamically sized tabs *unless* there is free space in the tab bar. I.e. if there is free space on the tab bar, then the tabs occupy whatever space they need. If there is space shortage in the tab bar, then it dynamically squeezes the tabs until the limit set with this setting is reached. So, all the tabs are guaranteed to fit in the tab bar as long as space and this setting permits. Tab bar overflowing (scrolling) only occurs after hitting this lower limit. IOW, it behaves the other way around: For dynamically sized tabs, instead of setting the upper bound, it sets the lower bound.

##### With left/right vertical tab bar (or list view):

Re: https://github.com/lxqt/qterminal/issues/410

It places an UPPER(*) limit to dynamically sized tabs.

(*) In order to have a stable (not varying) terminal size, this can alternatively be a FIXED limit for vertical tab bar. Or, an option can be introduced to specify whether to make it fixed or adaptive.

E.g.

[*] Adaptive/Fixed tab width

Limit tab width to: [___ px]

Note that these two settings are independent of each other. That is, checking or unchecking "Adaptive width" doesn't disable "Limit tab width" setting.

PS: I didn't like the idea of introducing another option (Adaptive width). Mentioned here for the sake of completeness. I would rather interpret "Limit tab width" simply as fixed size for vertical tab bar.

Thanks and regards.

##### System Information
* Package version: 0.8.1~36-g1a4452a-1

**Comment by agaida** [comment]
@aramazano - please add that you use lxqt.debian.net and the experimental-snapshots - ok, i know my versions but others might not :D 

BTW, 0.8.1~ ( < 0.8.1-x ) means close to 0.8.1 - that because  the original plan was to release some point releases. We we will do a full release soon instead.

**Comment by tsujan** [comment]
I agree that it wasn't a good idea in the first place. However, I don't agree about removing that option -- its disabled state is what I use.

"Limit tab width:" can be kept with its real meaning, i.e the max. tab width. Currently it's a fixed width, which is wrong, as @aramazano mentioned.

After that's fixed, if needed, another option could be added for "Fix tabs inside the tab-bar".

**Comment by agaida** [comment]
Full Ack for kept it as max tab width

**Comment by tsujan** [comment]
There's also another way I preferred in FeatherPad: If the tab is too long, make it half the tabbar size and elide its text. In other words, half the tabbar width can severe as a dynamic max. width, instead of a fixed max. width.

**Comment by agaida** [comment]
also possible - btw, thanks for the changed window title in featherpad - works good

**Comment by tsujan** [comment]
You're welcome.

As for QTerminal, the option could choose between 1, ½, ⅓ and ¼ tabbar width but *not more than that*.
