### ISSUE TITLE
Settings dialog window is too large

### ISSUE THREAD

**Issue by aramazano** [lxqt/qterminal#412]
It is 958x979 pixels here (including window decoration) which exceeds the height of my 1152x864 monitor (minus lxqt task bar).

I would suggest launching it with something like 800x600 or lower, so that it would fit in even a lowly 1024x768 monitor. Alternatively, last dimension of settings window can be saved and reused on the next launch of it.

Thanks and regards.

##### System Information
* Package version: 0.8.1~36-g1a4452a-1

**Comment by tsujan** [comment]
It can even remain large but should not exceed the monitor size; that's a bug to fix.

**Comment by aramazano** [comment]
Here is my full system info.

##### System Information
* Distribution & Version: lxqt.debian.net experimental-snapshots on top of Debian Testing (Buster)
* Kernel: 4.9.0-4-amd64
* Qt Version: 5.10.1
* libqtxdg Version: libqt5xdg3 / 3.1.1~13-gb5ddbd4-1
* qtermwidget Version: 0.8.1~24-g4cc05f9-1
* lxqt-build-tools Version: Not installed
* Package version: 0.8.1~36-g1a4452a-1

**Comment by mezklador** [comment]
Me too,

- Archlinux
- Kernel: 4.14.53-1-lts
- Qt Version: 5.11.1
- Qterminal: 0.9.0

**Comment by tsujan** [comment]
The fix should be very easy; I just didn't have time but will make a simple PR tomorrow.
