### ISSUE TITLE
QTerminal "escapes" from the window manager

### ISSUE THREAD

**Issue by asomers** [lxqt/qterminal#414]
Sometimes QTerminal seemingly escapes from the window manager's control.  This never happens the first time I open a new terminal in any given session, but frequently happens after a few hours' or days of use when opening new terminals.  I have only seen this bug with QTerminal, not with any other application.  Once the bug triggers, there is no way to correct it but to restart X.  In the buggy state, QTerminal:
* Has no border
* Cannot be resized or moved
* Is always the topmost window
* Does not respect focus-follows-mouse (but does take focus on click).

##### Steps to Reproduce (for bugs)
1. Start Lumina
2. Work for a few hours, opening multiple QTerminal instances on multiple virtual desktops
3. Eventually new QTerminal windows will all display the buggy behavior.  I can't reproduce it on demand, but It never takes more than a few hours.

##### System Information
* Distribution & Version:  TrueOS-Desktop-201803131015
* Kernel: FreeBSD 12.0-CURRENT fa797a5a3(trueos-master)
* Qt Version: 5.9.4
* libqtxdg Version: 3.1.0  
* qtermwidget Version: 0.8.0
* lxqt-build-tools Version: 0.4.0
* Package version: 0.8.0
* Desktop Environment: Lumina 1.4.2

**Comment by asomers** [comment]
Screenshot showing a QTerminal in the buggy state, without borders.
![terminal_without_borders](https://user-images.githubusercontent.com/129721/39314557-bc5f97b0-4931-11e8-86fe-9b60d86b71cb.png)

**Comment by agaida** [comment]
looks like a bug in the window manager - so i guess that the Lumina bug tracker is a better place for this bug.

**Comment by asomers** [comment]
It's not Lumina's fault, because Lumina is just a DE; it doesn't have its own Window Manager.  It uses Fluxbox, and this bug seems to be related: https://sourceforge.net/p/fluxbox/bugs/1140/ .  Nonetheless, most applications don't have this problem.  The bug seems to be related to client-side window decorations.  Is there any way to disable the use of client-side window decorations in QTerminal?

**Comment by tsujan** [comment]
> It's not Lumina's fault, because Lumina is just a DE; it doesn't have its own Window Manager. 

OK, so it's a fluxbox bug.

> Is there any way to disable the use of client-side window decorations in QTerminal?

As far as I know, CSD is a Gnome concept.

**Comment by jsm222** [comment]
Sorry to say it happens on openbox as well..

**Comment by stefonarch** [comment]
> Sorry to say it happens on openbox as well..

Version LXQt/Qterminal, Distro ecc?

**Comment by jsm222** [comment]
Apparently just an user error, I had borderless true in my config.
