### ISSUE TITLE
Where are the make files? How do I compile this?

### ISSUE THREAD

**Issue by chrissound** [lxqt/qterminal#420]

**Comment by yan12125** [comment]
Please checkout https://github.com/lxqt/qterminal#compiling-sources. Makefiles will be generated by cmake.

**Comment by chrissound** [comment]
I've certainly read through that

Running `make` or `cmake` in the project unfortunately does not seem to do anything useful.

**Comment by yan12125** [comment]
Could you paste command line outputs?

**Comment by chrissound** [comment]
```
make
make: *** No targets specified and no makefile found.  Stop.

cmake
Usage

  cmake [options] <path-to-source>
  cmake [options] <path-to-existing-build>

Specify a source directory to (re-)generate a build system for it in the
current working directory.  Specify an existing build directory to
re-generate its build system.

Run 'cmake --help' for more information.

```

**Comment by yan12125** [comment]
Well, I suggest to have a look at some tutorials for basic cmake usages. Note that this project requires out-of-source builds.
