### ISSUE TITLE
Hitting Ctrl buffers a scroll-to-bottom event

### ISSUE THREAD

**Issue by jleclanche** [lxqt/qterminal#43]
When you hit "Ctrl", or "Alt" or similar modifier keys, the next scroll event will scroll all the way to the bottom. This is very annoying as it means that if you do something like Ctrl+Shift+C to copy some text and then scroll up, it'll scroll all the way back down.

**Comment by worblehat** [comment]
I guess this is the reason:
https://github.com/qterminal/qtermwidget/blob/master/lib/TerminalDisplay.cpp#L2634-L2658

Actually I don't really understand the purpose of that `if(event->modifiers().testFlag(Qt::ShiftModifier)...` branch. Appearently it always scrolls the screen as specified in the "motion after pasting"-setting whenever a modifier key is pressed.

**Comment by worblehat** [comment]
What should the "Action after paste"-setting actually do? I see no difference when pasting no matter what option of the setting I choose...
