### ISSUE TITLE
wrong color

### ISSUE THREAD

**Issue by johndoe71rus** [lxqt/qterminal#442]
##### Expected Behavior
right color in terminal window

##### Current Behavior
i don't know which version now in git, but i have issue with 0.7.1. Calculate linux 17.12.2
What is wrong with color?  
https://i.imgur.com/NijKbKd.jpg
https://i.imgur.com/J1GOu4b.jpg

##### Steps to Reproduce (for bugs)
1.  just install calculate linux lxqt 17.12.2
2. open qterminal
3. run mc
4. 

##### System Information

* Calculate Linux Desktop 17.12.2 LXQt
* Kernel: 4.14.52-calculate x86_64
* Qt Version:  5.9.4
* libqtxdg Version:  2.0.0 
* qtermwidget Version: 0.7.1
* lxqt-build-tools Version: not install
* Package version: x11-terms/qterminal 0.7.1

**Comment by tsujan** [comment]
Not reproducible with the latest QTerminal:

![mc](https://user-images.githubusercontent.com/981076/42375978-bcb8b38e-8132-11e8-872b-97ca13306db6.png)

**Comment by agaida** [comment]
Only a hint - most applications work as to be expected in qterminal - mc included.

![](https://i.imgur.com/A8xn1tk.png) $TERM=xterm-256 - Terminal colors: BreezeModified - Skin: Default

![](https://i.imgur.com/TAeyydD.png) $TERM=xterm - Terminal colors: WhiteOnBlack - Skin: Default

![](https://i.imgur.com/nyjZwMU.png) - $TERM=xterm-256 Terminal colors: BreezeModified - Skin: ^^

**Comment by johndoe71rus** [comment]
it's good.
I first decided that this is a new skin for mc. But then I saw that the console tty colors are normal. And I decided to try lxterminal.
I get acquainted with calculate linux 2 weeks. Unfortunately gentoo has only lxqt 0.11

**Comment by johndoe71rus** [comment]
installed version 0.9.0. Started and got the same color problems. then I renamed the old qteminal.ini settings. launched with new settings and colors are normal. then something in the old settings file.
https://paste.ubuntu.com/p/5VwVBj7vq2/

**Comment by yan12125** [comment]
> colorScheme=Calculate

From the name, I guess the color scheme comes from Calculate Linux.

**Comment by johndoe71rus** [comment]
yes. i don't know why they do this
