### ISSUE TITLE
no matching function for call.... Fresh clone

### ISSUE THREAD

**Issue by Arefu** [lxqt/qterminal#443]
When downloading the current commit, it errors out on build citing:

> /home/johnathon/Downloads/qterminal-master/src/termwidget.cpp:140: error: no matching function for call to ‘TermWidgetImpl::filterActions(const QPoint&, QMenu*)’
>      QList<QAction*> extraActions = filterActions(pos, &menu);

##### Expected Behavior
It compiles?

##### Current Behavior
It does not.

##### Possible Solution
Seems more than happy to remove &menu from the list of parameters.

##### Steps to Reproduce (for bugs)
Download, build, error?

##### Context
This issue has upset me deeply? No really it just can't compile.

##### System Information
* Distribution & Version: Gnu/Loonix Arch Linux 
* Kernel: 4.17.4-1
* Qt Version: N/A?
* libqtxdg Version: N/A?  
* qtermwidget Version: N/A?
* lxqt-build-tools Version: N/A?
* Package version: 18da8aceaf14cc6bd9dd870258fac79fc7eea7ef

**Comment by yan12125** [comment]
FYI: You need the latest git-master of qtermwidget to compile the latest qterminal.

**Comment by Arefu** [comment]
It compiles fine when removing the &pos, but 'ightio. Thanks

**Comment by tsujan** [comment]
@Arefu Of course, you could have your own version of qterminal but if you compile the latest git qterminal against an older version of qtermwidget after making changes to the code, you might encounter bugs that don't really exist. I think that's why @yan12125 said, "Don't do that!"

**Comment by Arefu** [comment]
I figured that's what he was warning about, any future issues, I just don't forsee them with what I wanted to do with it :)
