### ISSUE TITLE
add configuration to prevent tabs to auto-rotate when moving tabs bar to the left (vertical tabas bar)

### ISSUE THREAD

**Issue by je-vv** [lxqt/qterminal#470]
When moving the tabs far to the left, making the bar vertical, the tabs text can't be read because it has been rotated.

The problem is that it seems there's no option to prevent tabs to be rotated when making the tabs bar vertical.  Or at least not on the current version of qterminal on Arch.

Attached an image illustrating what has been described.

![my_window](https://user-images.githubusercontent.com/10799432/44632926-98b80d00-a940-11e8-93da-94f38aa113ff.png)

##### System Information

Current (up to date Arch)
Linux <hostnema> 4.18.5-arch1-1-ARCH #1 SMP PREEMPT Fri Aug 24 12:48:58 UTC 2018 x86_64 GNU/Linux
qt5-base 5.11.1-2
libqtxdg 3.2.0-3
qtermwidget 0.9.0-1
lxqt-build-tools 0.5.0-1
qterminal 0.9.0-1

**Comment by agaida** [comment]
https://github.com/lxqt/qterminal/issues/410 - so i guess this won't be done

**Comment by je-vv** [comment]
@agaida, that's pretty sad, since there's already offered a limit on the tabs size, as well LXQT already offering that in general of anything related to vertical panel...
