### ISSUE TITLE
Weird characters issue with weechat, possible encoding issue?

### ISSUE THREAD

**Issue by ryanrms** [lxqt/qterminal#471]
![screenshot](https://user-images.githubusercontent.com/2936638/44810803-20e02180-ab90-11e8-8197-b3afae26aa02.png)

##### Expected Behavior

Expected behavior:  Weechat displays correctly
##### Current Behavior

Current Behavior:  Weechat in qterminal displays buggy characters, mostly stray letter "d", sometimes "/d" "s" "u" 

Sometimes appears to be characters left over when switching screens in weechat, as I'll switch to another window and the s is in the same position but being correctly displayed

##### Possible Solution

Possible reason is due to my encoding settings, or my weechat settings, but it doesn't seem to happen with other terminal emulators, including uxterm
##### Steps to Reproduce (for bugs)

1. Install qterminal 
2. install weechat
3. connect to a server in weechat, notice stray characters

I've tried the Linux, macbook, and default emulation modes

##### Context

Just an annoyance 
##### System Information

* Distribution & Version: Debian buster testing
* Kernel: Linux azusa 4.17.0-3-amd64 #1 SMP Debian 4.17.17-1 (2018-08-18) x86_64 GNU/Linux
* Qt Version: 5.11.1
* libqtxdg Version:  0.13.0-1
* qtermwidget Version: 0.9.0
* lxqt-build-tools Version: not installed?
* Package version: 
apt-cache show qterminal
Package: qterminal
Version: 0.9.0-3

**Comment by agaida** [comment]
looks like a problem with wrong terminal/language settings

![](https://i.imgur.com/PGjcyzt.png) - this is a sid with latest builds from git - one might have a look at the printed lines, the ncurses ui and so on. So i guess setting up the system right would fix it.

**Comment by ryanrms** [comment]
Going to close this, it appears to be some sort of conflict with my weechat config and qterminal.  default weechat config is working fine.  weird since my customized config displays fine in other terminals.  time to start over from scratch.  thanks
