### ISSUE TITLE
Don't work keys HOME/END in zsh

### ISSUE THREAD

**Issue by sr-tream** [lxqt/qterminal#482]
Press HOME -> notching<br>
Press END -> print '~'

##### Expected Behavior
Press HOME -> beginning-of-line<br>
Press END -> end-of-line

##### Possible Solution

Not found. Attempts to use bindkey were unsuccessful

##### Steps to Reproduce (for bugs)

1. Press HOME or END

##### System Information

* Distribution & Version: Archlinux
* Kernel: 4.18
* Qt Version: 5.11.2
* qtermwidget Version: 0.9.0

**Comment by agaida** [comment]
works fine for me - wrong emulation chosed?

**Comment by white-hat** [comment]
@sr-tream switching from `linux` to `default` emulation fixed this issue for me
