### ISSUE TITLE
Qterminal should ask for explicit permissions to close when more than one tab is open in terminal. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#496]
This probably is a bit related with #395 but it would be much nicer if in the behavior there is a check-box, clicking on it will make sure that if there are more than one tabs open in qterminal, it will ask for permission to close the tabs instead of closing the tabs by themselves.  I have lost too many qterminal sessions due to current behavior :(

I saw this with the 0.9.0 as well as with the experimental-snapshots ( in fact, it might have become a bit worse than before but that's just a feeling .) 

This feature can be seen in guake preferences so will be nice if something similar can be here.

**Comment by tsujan** [comment]
The close prompt is different now (see https://github.com/lxqt/qterminal/commit/ff152737c49ec8a0a8e8ea4c6d28646d83defd02): it appears only when a process is running in any tab or subterminal, such that nothing is lost.
