### ISSUE TITLE
qterminal either quits or crashes and have no way to know what is happening. 

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#498]
Qterminal either crashes or quits at the most inappropriate of times. 

I tried to figure out what is happening. 

One thing I want to discount is it's not the combo shortcut which is happening . I don't see a way to turn off quitting qterminal by keyboard combo. Is there such a way ?
![qterminal-keyboard-shortcuts-quit](https://user-images.githubusercontent.com/727626/47055528-6eaef880-d1d5-11e8-828b-b113f5b7a1e5.png)

To be clear, is there way so that closing/quitting via keyboard combo is disabled, i.e doesn't work before I try to figure out whether it's qterminal at fault or I am. 

I have small keyboards so if there's a way please let me know before I debug if further using gdb to see what happens. Sharing all the info. needed by way of reportbug. 

```
Package: qterminal
Version: 0.14.0~really~0.9.1~156-ga968cc4-1
Severity: grave

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages qterminal depends on:
ii  libc6              2.27-6
ii  libqt5core5a       5.11.1+dfsg-9
ii  libqt5dbus5        5.11.1+dfsg-9
ii  libqt5gui5         5.11.1+dfsg-9
ii  libqt5widgets5     5.11.1+dfsg-9
ii  libqt5x11extras5   5.11.1-2
ii  libqtermwidget5-0  0.14.0~really~0.9.1~71-g871d069-1
ii  libstdc++6         8.2.0-7
ii  libx11-6           2:1.6.7-1

Versions of packages qterminal recommends:
ii  qterminal-l10n  0.14.0~really~0.9.1~156-ga968cc4-1

qterminal suggests no packages.

-- no debconf information

```

**Comment by tsujan** [comment]
I don't know if I've understood what you need but if you want to clear a shortcut, double click its box, press any modifier key (`Ctrl`, for example, and then press `Enter`.

Is that what you want?

**Comment by shirishag75** [comment]
aha, @tsujan thank you for sharing the way - 

>  I don't know if I've understood what you need but if you want to clear a
>  shortcut, double click its box, press any modifier key (`Ctrl`, for example,
>  and then press `Enter`

I just did that and it works. Now I will surely triage it in case it gets crashed again using gdb.

**Comment by tsujan** [comment]
Please attach the backtrace in case of any crash:
```
coredumpctl gdb qterminal
where
```

BTW, GitHub is a mess right now. I could sign in only with Chromium -- Firefox and Falkon didn't work.

**Comment by agaida** [comment]
@tsujan - you are not alone: https://status.github.com/messages

**Comment by tsujan** [comment]
@agaida Yes, I read your comment at https://forum.lxqt.org/t/migrating-to-gitlab/425. Thanks for the link!

**Comment by shirishag75** [comment]
> Please attach the backtrace in case of any crash:
> 
> ```
> coredumpctl gdb qterminal
> where
> ```
> 
> BTW, GitHub is a mess right now. I could sign in only with Chromium -- Firefox and Falkon didn't work.

Curiouser, Curiouser . I get the following when I run the command - 

```
$ coredumpctl gdb qterminal
No match found.
```

**Comment by tsujan** [comment]
@shirishag75 

No QTermina coredump means it hasn't crashed yet -- provided that you have `coredumpctl`; Debian splits systemd into several packages and it is inside `systemd-coredump`, which you've installed.

Since some crashes may happen randomly, `coredumpctl` is the best way to hunt them. With it, if a crash happens, a coredump will be created in `/var/lib/systemd/coredump`. Mine is empty. You could open it and see if any crash has happened in any app.

If you know the app binary name, the above-mentioned command (especially after `where`) gives a clean backtrace for the latest crash. Sometimes, the app names are truncated in their coresumps, so it's better to take a look at the folder `/var/lib/systemd/coredump`.

**Comment by stefonarch** [comment]
> I don't know if I've understood what you need but if you want to clear a shortcut, double click its box, press any modifier key (`Ctrl`, for example, and then press `Enter`.


Added to the wiki
