### ISSUE TITLE
Have either a qterminal-doc or yelp  

### ISSUE THREAD

**Issue by shirishag75** [lxqt/qterminal#502]
qterminal should have a documentation package or something similar to yelp or some other way. 

http://yelp.io/

qterminal is not documented at all. Currently if I want to clear a keyboard shortcut there is neither a hint nor any sort of documentation as a user to know what to do. 

I had to go to https://github.com/lxqt/qterminal/issues/498#issuecomment-431752887 and remember that each time. 

And even then it's not complete. For instance to keep the shortcut clear, you have to double-click the shortcut, click Shift and then click Enter. This I had to learn from trial and error method. Not good :(

As a user this is not efficient use of my time.  A much preferable usage would be to have such documentation either in a document package or something similar to what yelp gives for mate-terminal . 

![yelp-mate-terminal-documentation](https://user-images.githubusercontent.com/727626/47630517-3dd0ab00-db67-11e8-969c-e7ec21edb4eb.png)

The documentation in yelp is much more, I have just shared the tit-bit about what interests me atm but it would be useful to have something similar. 

Package: qterminal
Version: 0.14.0~really~0.9.1~157-gee250b4-1
Severity: normal

-- System Information:
Debian Release: buster/sid
  APT prefers testing
  APT policy: (990, 'testing'), (500, 'unstable-debug'), (500, 'testing-debug'), (500, 'unstable'), (1, 'experimental-debug'), (1, 'experimental')
Architecture: amd64 (x86_64)

Kernel: Linux 4.18.0-2-amd64 (SMP w/4 CPU cores)
Locale: LANG=en_IN, LC_CTYPE=en_IN (charmap=UTF-8), LANGUAGE=en_IN:en (charmap=UTF-8)
Shell: /bin/sh linked to /bin/dash
Init: systemd (via /run/systemd/system)
LSM: AppArmor: enabled

Versions of packages qterminal depends on:
ii  libc6              2.27-6
ii  libqt5core5a       5.11.2+dfsg-3
ii  libqt5dbus5        5.11.2+dfsg-3
ii  libqt5gui5         5.11.2+dfsg-3
ii  libqt5widgets5     5.11.2+dfsg-3
ii  libqt5x11extras5   5.11.2-2
ii  libqtermwidget5-0  0.14.0~really~0.9.1~73-gb17add8-1
ii  libstdc++6         8.2.0-8
ii  libx11-6           2:1.6.7-1

Versions of packages qterminal recommends:
ii  qterminal-l10n  0.14.0~really~0.9.1~157-gee250b4-1

qterminal suggests no packages.

-- no debconf information

**Comment by tsujan** [comment]
Yelp belongs to Gnome. The GUI itself should guide the user as far as possible.

In Qt, explanations can be added as "WhatsThis", as tooltips, or as labels. "WhatsThis" is the best option for complex GUIs and we shoudl start to use it, IMO, but if the app is much more than what it seems to be (like pcmanfm-qt), a help can be added inside a dialog with a scrollable view. In the last case, the problem is just who is going to write it...

I think all you might want here is an explanation in the GUI about clearing shortcuts. Is there anything else? If we think in terms of a detailed doc, it might never happen but WhatsThis/tooltips/labels can be added in a small PRs.

**Comment by shirishag75** [comment]
yeah, explanation in the GUI about clearing shortcuts will be welcome.

**Comment by yan12125** [comment]
I think most of qterminal is self-explaining, while there are indeed some tricks. I think a Wiki is a better place for some notes, so I enabled GitHub Wiki for both https://github.com/lxqt/qterminal and https://github.com/lxqt/qtermwidget. Feel free to add contents to it!
