### ISSUE TITLE
.desktop files with Terminal=true do not launch

### ISSUE THREAD

**Issue by wxl** [lxqt/qterminal#510]
##### Steps to Reproduce (for bugs)
 1. Create a .desktop file to be run in the terminal, e.g.:
```
      [Desktop Entry]
      Name=top
      Type=Application
      Exec=top
      Terminal=true
```
 2. (double) Click it to launch it
 3. Click "execute" when asked to open or execute

##### Expected Behavior
A terminal window with `top` in it should open.

##### Current Behavior
No terminal window opens. `top` is not running.

##### Context
Occasionally, someone wants to make an entry on their desktop or menu for a terminal program. `top` is a pretty classic example.

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0
* Qt Version: 5.11.1
* libqtxdg Version: 3.2.0  
* qtermwidget Version: 0.9.0
* lxqt-build-tools Version: 0.5.0
* Package version: 0.9.0-3ubuntu3

**Comment by tsujan** [comment]
Ubuntu problem.

![top](https://user-images.githubusercontent.com/981076/48462800-f3019500-e7ee-11e8-8e62-c7684ee6824c.png)

**Comment by wxl** [comment]
…except that I also see this in Debian.

**Comment by agaida** [comment]
oh - in this special case it is picnic (want not to use pebcak)

**Comment by wxl** [comment]
If you wish to use an acronym, it helps to know what the appropriate arrangement of letters. That said, what is the problem here? Or rather where exactly does it lie?

**Comment by agaida** [comment]
https://en.wiktionary.org/wiki/PEBCAK
https://en.wiktionary.org/wiki/PICNIC

maybe in a missed package. Can't reproduce

**Comment by tsujan** [comment]
![term](https://user-images.githubusercontent.com/981076/48513083-29cbbf80-e870-11e8-8ec7-13c017c72a11.png)

**Comment by wxl** [comment]
@agaida I just installed stock Debian with the LXQt desktop environment option in the installer. Nothing special. Is there something inherently missing from it?

@tsujan same settings.

**Comment by tsujan** [comment]
Do you have xterm?

**Comment by agaida** [comment]
xterm is not really needed  - but would be the a simple way to get this work.  And i have real problems to answer questions about Lubuntu - simple reason, i don't know the packages codewise and the installation.

**Comment by agaida** [comment]
i tested sparky linux first time a few days ago - just for fun. Surprise, surprise - the "missed" Lubuntu functionality works out of box in Sparky linux. And they are damn near to a pure debian.
https://youtu.be/SxeffyxcacQ

**Comment by tsujan** [comment]
Same here with htop:

![htop](https://user-images.githubusercontent.com/981076/48517581-0575e000-e87c-11e8-91ff-e10f27ef19ea.png)

**Comment by wxl** [comment]
So xterm is the requirement here? The point was about it not working in qterminal. Sounds like you're saying it doesn't.

**Comment by tsujan** [comment]
The real point was that it had nothing to do with qterminal, so that even if it was reproducible -- which wasn't -- it should be closed. Files are launched by pcmanfm-qt.

**Comment by wxl** [comment]
Maybe I misunderstand then: is it not possible to open with your terminal of choice with `Terminal=true` or it's always xterm only?

**Comment by tsujan** [comment]
Reread your first comment.

**Comment by agaida** [comment]
terminal of choice - you can reproduce it
     
open the session settings and set the terminal in default applications -  we are always glad to do downstream work.

**Comment by wxl** [comment]
Sigh. You know it would be really nice if you two could just be nice for once. Or at least communicate effectively. Do you think it might be too hard to ask that while you are typing things you just try to type the things that actually answer the issue rather than skirting around it?

**Comment by tsujan** [comment]
If you report an issue that's related to my area, I'll reply in the way I reply to any report. I make no exception for you, of course.

**Comment by agaida** [comment]
@wxl - as mentioned before - we was more than nice. As several times ago. Maybe you should research **your** issues a bit better before you trying to let us do your work. It migth help a lot.

**Comment by wxl** [comment]
I *still* don't understand what you're trying to communicate despite having researched it. And when being told I'm mistaken in my understanding, I *still* don't understand how. I would love to. It would certainly help going forward.

**Comment by tsujan** [comment]
> I still don't understand

And that's your problem.

**Comment by tsujan** [comment]
@wxl Whether we can have an effective communication or not and although launching desktop files isn't related to QTerminal, I really think you for this report -- I mean it! Your repport started a long discussion between @agaida and me, which finally resulted in finding an issue in GLib and applying PCMan's fix for it to libfm-qt and pcmanfm-qt (the commits will come soon). With the next release, Lubuntu users won't have to install xterm for using `Terminal=true`.

**Comment by wxl** [comment]
@tsujan @agaida I see https://github.com/lxqt/libfm-qt/commit/9af480812bdef4a7cca7db7416b24d96b179ebf1 https://github.com/lxqt/pcmanfm-qt/commit/f0598698b7ee3a870aa19563bc38426dea4c0da0 which seems like it should be what you're referring to. Glad we figured it out in the end.

**Comment by tsujan** [comment]
Yes! There are other places outside LXQt, where similar problems are reported. In short, that's how GLib works -- or an issue in GLib, because of a hard-coded terminal list. PCMan's had made a workaround for it a long time ago but his solution wasn't used in the new code.

**Comment by tsujan** [comment]
An example of such reports outside LXQt: https://github.com/mate-desktop/mate-panel/issues/57.
