### ISSUE TITLE
Support entering Unicode via Ctrl+Shift+U

### ISSUE THREAD

**Issue by PanderMusubi** [lxqt/qterminal#529]
##### Expected Behavior
Using Ctrl+Shift+U normally allow for entering Unicode via codepoint. This works in other apps in Lubuntu such as Firefox and Gedit.

##### Current Behavior
Ctrl+Shift+U does not trigger anything.

##### Steps to Reproduce (for bugs)
1. Open qterminal
2. Ctrl+Shift+U
3. `i` `i` `ENTER`
4. should show `ĳ`

##### System Information
* Distribution & Version: Lubuntu 18.10
* Kernel: 4.18.0-13.14
* Qt Version: 5.11.1-6
* libqtxdg Version:  n/a
* qtermwidget Version: 0.9.0-1ubuntu2
* lxqt-build-tools Version: n/a
* Package version: 0.9.0-3ubuntu3

**Comment by yan12125** [comment]
Did you enable any input methods? (ibus, fcitx, scim, ...) This features sounds like from an IME rather than from applications.

**Comment by yan12125** [comment]
If you have ibus running, `pgrep ibus` will show the process ID number of ibus. The case is similar for scim and fcitx.

**Comment by PanderMusubi** [comment]
No result of all three.

**Comment by yan12125** [comment]
Well, as I got nothing with Ctrl+Shift+U and then i i in Firefox on my machine, I believe it's a feature provided by another program, but who knows.

**Comment by PanderMusubi** [comment]
I think it is part of Xorg/Wayland/GTK/xinput or something similar. Most applications support it, even most other terminal applications. So I suspect it is catched/blocked somewhere in qterminal? If not, that it would be a missing feature.

**Comment by yan12125** [comment]
Good point. How about other Qt applications?

**Comment by PanderMusubi** [comment]
As far as I can check, also not supported.

**Comment by yan12125** [comment]
Googling "Ctrl-Shift-U" takes me to two places - GTK+ and iBus. I got nothing special with Ctrl+Shift+U i i in all tried GTK+ application - Firefox, Gedit, Evince and Seahorse. With iBus I can type ĳ with Ctrl+Shift+U 0133 following a space in both Qt and GTK+ applications.

> Distribution & Version: Lubuntu 18.10

@tsimonq2, could you help on checking whether it's a Lubuntu-specific feature or not?

**Comment by PanderMusubi** [comment]
Ctrl+Shift+U is pretty standard for many Linux window managers, I have used it also in plain vanilla Ubuntu and Debian.

**Comment by agaida** [comment]
@PanderMusubi - how many is many?

**Comment by PanderMusubi** [comment]
At least GNOME, KDE, LXDE, MATE and Xfce. It does work on Lubuntu, only not in Qt applications in Lubuntu. Not sure where the support is implemented and also not sure where it is kept out regarding qterminal e.g.

Your link is not particularly helpful, but thanks anyway.

**Comment by agaida** [comment]
erm, no further comments from my side

**Comment by agaida** [comment]
Hmm - maybe the last comment from my side - Input methods should be systemwide, not only for a terminal. The thread opener refuses to answer some questions about installed or activated input methods - so closing this now,

**Comment by PanderMusubi** [comment]
Sorry, but I did answer, there are none running.

**Comment by PanderMusubi** [comment]
If you want, I can make screenshots of all keyboard relates configuration apps, but ibus, scim or fcitx is not running.

**Comment by PanderMusubi** [comment]
So evince, thunderbird, firefox, gedit, gimp, inkscape, etc. use soemthing else that supports this, probably from gtk(?). Because of that, probably, I never needed an input method? What is the default/recommended input method for LXQt in English with some other European languages?

**Comment by tsujan** [comment]
> What is the default/recommended input method for LXQt in English....

There's something called "Google". You could "search" it and find something called ibus (ibus-qt). This is `Ctrl+Shift+U` and then `266A` in QTerminal:

![qterminal](https://user-images.githubusercontent.com/981076/50522152-b0fe8b00-0ade-11e9-9f36-2118788f994e.png)

**Comment by PanderMusubi** [comment]
Lubunt 18.10 only has ibus-qt4, not sure is that is the one to use, since all the rest is QT5. Especially since Lubuntu has changed a lot of tooling and configuration applications in the transition from 18.04 to 18.10.

Also `lxqt-config-input` warns about using an input method in combination with LXQt. Most quick fix for me is to use gnome-terminal.

**Comment by tsujan** [comment]
Report Lubuntu problems to Lubuntu! We don't maintain Lubuntu (or any other distro) here.

**Comment by PanderMusubi** [comment]
Thanks. For me this is unfamiliair terrain. I will look a bit further into input methods.

**Comment by tsujan** [comment]
So, [the lack of a qt5 deb package](https://packages.debian.org/search?keywords=ibus-qt) for ibus-qt is a Debian issue? Who uses Qt4 anymore?

**Comment by tsujan** [comment]
Oh, my mistake: there's no Qt5 based iBus.

**Comment by agaida** [comment]
no bug - there is only libqt5gui5 needed - only a guess

**Comment by tsujan** [comment]
No! I removed ibus-qt and left only ibus here (on Manjaro) and `Ctrl+Shift+U` worked with QTerminal again. Just `QT_IM_MODULE` should be set to `ibus` (as the GUI explains).

So, I shouldn't have installed ibus-qt in the first place.

**Comment by tsujan** [comment]
OK, apparently, Qt5 supports ibus module with `export QT_IM_MODULE=ibus`. I also tried it in FeatherPad and it worked. Even Arch wiki seems not up-to-date in this regard.

**Comment by yan12125** [comment]
Thanks @tsujan. I tried it more and find that fcitx also supports Ctrl-Shift-U. I can use Ctrl-Shift-U 0133 space/enter to get ĳ in ibus/fcitx respectively. Still have no idea how to get the same symbol with i i.

**Comment by tsujan** [comment]
> Still have no idea how to get the same symbol with i i.

As far as I know, it shouldn't work because it isn't a hexadecimal ([0-9a-f]).

BTW, GTK3 has `GtkIMContextSimple`, so that `Ctrl-Shift-U` should work with GTK3 apps without needing ibus, fcitx or similar programs. I tried `gtk3-widget-factory` and `Ctrl-Shift-U` worked in its input widgets. I don't think Qt has a similar functionality but I'm not sure.
