### ISSUE TITLE
Revive qterminal on macOS

### ISSUE THREAD

**Issue by yan12125** [lxqt/qterminal#533]
##### Expected Behavior
qterminal works fine on macOS

##### Current Behavior
It doesn't even build

##### Possible Solution
Land macOS-specific patches from https://gitlab.com/yan12125/macports-overlay/commit/f266c2d0a8d6813a25e0675a6ba5c2b4b0276086

##### Steps to Reproduce (for bugs)
1. Try to build qtermwidget and qterminal on macOS Mojave

##### Context
A requirement of https://github.com/lxqt/qtermwidget/issues/240

##### System Information
* Distribution & Version: macOS Mojave 10.14.2
* Kernel: xnu-4903.231.4~2/RELEASE_X86_64
* Qt Version: 5.12.0
* qtermwidget Version: git-master
* lxqt-build-tools Version: 0.5.0
* Package version: git-master

**Comment by apjanke** [comment]
I've got qterminal building on macOS 10.13.6 against Qt 5.12, using Homebrew.

https://github.com/octave-app/homebrew-octave-app-bases/blob/bcb4c5a2b7eb6158bbbcee52a575cf9ed09a5bec/Formula/qterminal.rb
https://github.com/octave-app/homebrew-octave-app-bases/blob/bcb4c5a2b7eb6158bbbcee52a575cf9ed09a5bec/Formula/qtermwidget.rb
https://github.com/octave-app/homebrew-octave-app-bases/blob/bcb4c5a2b7eb6158bbbcee52a575cf9ed09a5bec/Formula/lxqt-build-tools.rb

```
brew tap octave-app/octave-app-bases
brew install qterminal
```

It's not working, though. I can launch it and the terminal comes up, but it doesn't display any text in the terminal or respond to keystrokes.

```
$ qterminal
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/local/Cellar/qterminal/0.9.0/share/qterminal/translations
load success: false
Canot open file "/Users/janke/.config/qterminal.org/qterminal_bookmarks.xml"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/local/Cellar/qtermwidget/0.9.0/share/qtermwidget5/translations"
Translations found in "/usr/local/Cellar/qtermwidget/0.9.0/share/qtermwidget5/translations"
Can't open a pseudo teletype
default KB_LAYOUT_DIR:  "/usr/local/Cellar/qtermwidget/0.9.0/share/qtermwidget5/kb-layouts"
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
loadAllColorSchemes
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
Shell program: "/bin/zsh"
("/bin/zsh")
Unable to set terminal attributes.
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
QIODevice::write (KPtyDevice): device not open
QIODevice::write (KPtyDevice): device not open
QIODevice::write (KPtyDevice): device not open
QIODevice::write (KPtyDevice): device not open
QIODevice::write (KPtyDevice): device not open
```

One of those `QIODevice::write (KPtyDevice): device not open` messages is issued each time I press a key.

I'm interested in seeing QTerminal run on macOS to help with hacking on Octave. (Even though I know there's discussion of dropping QTerminal from it.)

**Comment by apjanke** [comment]
I partially take that back: the head of the repo for QTermWidget is not building on macOS.

```
[100%] Linking CXX shared library libqtermwidget5.dylib
/usr/local/Cellar/cmake/3.13.2/bin/cmake -E cmake_link_script CMakeFiles/qtermwidget5.dir/link.txt --verbose=1
/usr/local/Homebrew/Library/Homebrew/shims/mac/super/clang++ -DNDEBUG -dynamiclib -Wl,-headerpad_max_install_names -current_version 0.14.0 -o libqtermwidget5.0.14.0.dylib -install_name libqtermwidget5.0.dylib CMakeFiles/qtermwidget5.dir/lib/BlockArray.cpp.o CMakeFiles/qtermwidget5.dir/lib/ColorScheme.cpp.o CMakeFiles/qtermwidget5.dir/lib/Emulation.cpp.o CMakeFiles/qtermwidget5.dir/lib/Filter.cpp.o CMakeFiles/qtermwidget5.dir/lib/History.cpp.o CMakeFiles/qtermwidget5.dir/lib/HistorySearch.cpp.o CMakeFiles/qtermwidget5.dir/lib/KeyboardTranslator.cpp.o CMakeFiles/qtermwidget5.dir/lib/konsole_wcwidth.cpp.o CMakeFiles/qtermwidget5.dir/lib/kprocess.cpp.o CMakeFiles/qtermwidget5.dir/lib/kpty.cpp.o CMakeFiles/qtermwidget5.dir/lib/kptydevice.cpp.o CMakeFiles/qtermwidget5.dir/lib/kptyprocess.cpp.o CMakeFiles/qtermwidget5.dir/lib/Pty.cpp.o CMakeFiles/qtermwidget5.dir/lib/qtermwidget.cpp.o CMakeFiles/qtermwidget5.dir/lib/Screen.cpp.o CMakeFiles/qtermwidget5.dir/lib/ScreenWindow.cpp.o CMakeFiles/qtermwidget5.dir/lib/SearchBar.cpp.o CMakeFiles/qtermwidget5.dir/lib/Session.cpp.o CMakeFiles/qtermwidget5.dir/lib/ShellCommand.cpp.o CMakeFiles/qtermwidget5.dir/lib/TerminalCharacterDecoder.cpp.o CMakeFiles/qtermwidget5.dir/lib/TerminalDisplay.cpp.o CMakeFiles/qtermwidget5.dir/lib/tools.cpp.o CMakeFiles/qtermwidget5.dir/lib/Vt102Emulation.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_Emulation.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_Filter.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_HistorySearch.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_kprocess.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_kptydevice.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_kptyprocess.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_Pty.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_qtermwidget.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_ScreenWindow.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_SearchBar.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_Session.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_TerminalDisplay.cpp.o CMakeFiles/qtermwidget5.dir/lib/moc_Vt102Emulation.cpp.o /usr/local/opt/qt/lib/QtWidgets.framework/QtWidgets /usr/local/opt/qt/lib/QtGui.framework/QtGui /usr/local/opt/qt/lib/QtCore.framework/QtCore
Undefined symbols for architecture x86_64:
  "KPtyPrivate::chownpty(bool)", referenced from:
      KPty::close() in kpty.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [libqtermwidget5.0.14.0.dylib] Error 1
make[1]: *** [CMakeFiles/qtermwidget5.dir/all] Error 2
make: *** [all] Error 2
```

I don't know if that's a Mac-specific problem or not.

But the latest releases are building.

**Comment by yan12125** [comment]
Great to see more efforts on this topic! As current qterminal is far from usable on macOS, I'd like to target the latest git-master and bring necessary patches into the main repo first. After that the following stable release will be working on macOS. You can find some patches in the GitLab commit above. Those patches are a few months old, so they might not work with the current repo, though.

**Comment by apjanke** [comment]
Reported the QTermWidget build issue at https://github.com/lxqt/qtermwidget/issues/250.

**Comment by apjanke** [comment]
Hey, I think this is doable. Just a few fixes needed to get it up and running on Mac again, if not fully functional:

* https://github.com/lxqt/qtermwidget/pull/252 – HAVE_OPENPTY handling
* https://github.com/lxqt/qtermwidget/pull/254 – Fix removed Q_WS_MAC macro
* https://github.com/lxqt/qterminal/pull/560 – Remove Qt5X11Extras dependency on Mac
* https://github.com/lxqt/qterminal/issues/561 – Fix libqtermwidget5.0.dylib path

**Comment by apjanke** [comment]
A couple more to get it working correctly once it's compiling:

* https://github.com/lxqt/qterminal/pull/563 – Fix default font on Mac
* https://github.com/lxqt/qterminal/pull/562 – Fix key mappings on Mac

**Comment by apjanke** [comment]
Okay, one more, to get the build running after all these other patches have been merged:

* [ ] https://github.com/lxqt/qterminal/pull/565 – Fix `PASTE_SELECTION_SHORTCUT` build failure

Hopefully that's it.

**Comment by apjanke** [comment]
Looks like that's it. QTerminal and QTermWidget now compile and run on macOS, from `master` with no patches.

```
$ brew install qterminal --HEAD
==> Installing qterminal from octave-app/octave-app
==> Cloning https://github.com/lxqt/qterminal.git
Updating /Users/janke/Library/Caches/Homebrew/qterminal--git
From https://github.com/lxqt/qterminal
   a84d356..aefdf8e  master     -> origin/master
==> Checking out branch master
Already on 'master'
Your branch is behind 'origin/master' by 1 commit, and can be fast-forwarded.
  (use "git pull" to update your local branch)
HEAD is now at aefdf8e Fix missing PASTE_SELECTION_SHORTCUT on macOS
==> cmake .. -DCMAKE_C_FLAGS_RELEASE=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE=-DNDEBUG -DCMAKE_INSTALL_PREFIX=/usr/local/Cellar/qterminal/HEAD-aefdf8e -DCM
==> make install
🍺  /usr/local/Cellar/qterminal/HEAD-aefdf8e: 40 files, 937.7KB, built in 16 seconds
[~]
$
```

<img width="640" alt="Screen Shot 2019-03-09 at 3 53 53 AM" src="https://user-images.githubusercontent.com/2618447/54068869-25605380-421f-11e9-9cf5-bd4459b8b2cf.png">

Maybe this bug can be closed now?

I see a couple other small issues: like the tab width is too wide, and it still issues a “Using a variable-width font in the terminal” error even though the default is fixed-width now. I can report those separately now. Maybe with a “macOS” issue label?

**Comment by yan12125** [comment]
> Maybe this bug can be closed now?

Awesome! You got it!

> like the tab width is too wide

Aha, that's because my screen is big :) You can just change the default width in the preferences.

> Using a variable-width font in the terminal

I suspect the cause is that there's no working fontconfig backend. Maybe rephrasing it as "Warning: fontconfig not available, assuming fixed-width font".

> Maybe with a “macOS” issue label?

I've created the `platform:macOS` label. Feel free to add it!

**Comment by apjanke** [comment]
Excellent; thanks.

**Comment by apjanke** [comment]
Any chance of a new qterminal/qtermwidget release to pick these macOS fixes up? I'm interested in trying to migrate GNU Octave to use the current qtermwidget stuff, but it's hard to target the development version instead of a release.
