### ISSUE TITLE
Add option to hide tab bar if only one tab is open

### ISSUE THREAD

**Issue by goetzc** [lxqt/qterminal#54]
To gain some space when only one tab is open.

Maybe an option in "Preferences" near the "Tabs position" like, "Always show the tab bar"?

**Comment by stefonarch** [comment]
Didn't find it in the closed PRs,  it's present in actual version 1.3.
Anyway older versions than 1.1 or 1.2  are really outdated.

**Comment by tsujan** [comment]
It was done before QTerminal came into LXQt, which means that it has always been there.
