### ISSUE TITLE
Set $TERM according to emulation type (but allow overriding)

### ISSUE THREAD

**Issue by tanius** [lxqt/qterminal#551]
Since #100, users can edit the $TERM variable in the settings. That's better than a fixed default, but initially still leads to issues where the emulation type setting and $TERM do not correspond.

For example, by default in qterminal on Ubuntu 18.10, $TERM is `xterm-256color` and emulation type is `linux`. Now the escape codes for F1-F5 differ between the two – see `infocmp xterm-256color` vs. `infocmp linux`. As a result, with these default settings the F1-F5 hotkeys in `byobu` (or `mc` or another application with hotkeys in F1-F5) will not work until setting $TERM to `linux` **or** emulation type to `default`.

Proposal: initialize $TERM according to the chosen emulation type, so that $TERM changes when the user changes the emulation type. Except there would also be a checkbox "Set custom $TERM", enabling an edit field where the user can put in a user defined value like now for $TERM. This way, users who run into problems with a $TERM not being known to a remote server can still solve the problem, while everyone else gets working defaults.

**Comment by yan12125** [comment]
> For example, by default in qterminal on Ubuntu 18.10, $TERM is xterm-256color and emulation type is `linux`

The default emulation type is `default` [1]. Most likely Ubuntu devs change the default there. Complain it on Launchpad.

FYI, all recent improvements to key bindings occur in the `default` emulation only. I don't recommend other emulation types beyond for testing purposes. Furthermore, I'm considering deprecating other emulation types once `default` is good enough (e.g., no more issues like https://github.com/lxqt/qtermwidget/issues/235).

[1] https://github.com/lxqt/qterminal/blob/a8ab4f7f2e97b5658cce664e59cbec6bbaeb76a7/src/properties.cpp#L86

**Comment by tanius** [comment]
Thank you for the clarifications! I have since reported this as a [bug on Launchpad](https://bugs.launchpad.net/ubuntu/+source/qterminal/+bug/1823683).
