### ISSUE TITLE
qterminal distorted on archlinuxarm

### ISSUE THREAD

**Issue by lephonet** [lxqt/qterminal#552]
Elements in qterminal appear to be pushed to the right side, making it hard to use GUI-applications in the terminal

##### Expected Behavior

Terminal elements aren't pushed to the right

##### Current Behavior

Elements appear squished
![terminal-alignment](https://user-images.githubusercontent.com/47280942/52169602-68686c00-2733-11e9-896e-4248aa157d73.png)

![neofetch-align](https://user-images.githubusercontent.com/47280942/52169648-fe9c9200-2733-11e9-9f4f-cc0be1d80fcf.png)

##### Steps to Reproduce (for bugs)

1. Run any advanced command in the terminal
2. 
3. 
4. 

##### Context

I am running Arch Linux on a Samsung Chromebook XE303C12 and have some difficulties using lxqt with it.
I had no response on the archlinuxarm forum though https://archlinuxarm.org/forum/viewtopic.php?f=57&t=13399

##### System Information

* Distribution & Version: Arch Linux ARM armv7l 
* Kernel: Linux alarm 4.20.5-1-ARCH
* Qt Version: 5.12.0
* libqtxdg Version:  community/libqtxdg 3.2.0-5
* qtermwidget Version: community/qtermwidget 0.9.0-1
* lxqt-build-tools Version: community/lxqt-build-tools 0.5.0-1
* Package version: community/qterminal 0.9.0-1

**Comment by tsujan** [comment]
Not reproducible:

![qterminal](https://user-images.githubusercontent.com/981076/52170270-acbc3200-275c-11e9-9455-ac717fdba184.png)

The latest QTreminal is 0.14.0

**Comment by agaida** [comment]
it might be reproducible - if one use some false tagged fonts that say: We are monotypes - but are not
