### ISSUE TITLE
leaving qterminal open after calling and executing a program (-e option)

### ISSUE THREAD

**Issue by hmollercl** [lxqt/qterminal#554]
currently when you call qterminal to execute a command (qterminal -e <command>) it close and you cannot see the output of the command. Is there some way to leave it open?

**Comment by ringo32** [comment]
you have to write a script  and last two lines could be :+1: 
echo end.
read

you have to push then close. got here a script dat uses qterminal to open another script to use pacman..

**Comment by hmollercl** [comment]
I don't understand you. Creating a .sh like this doesn't work:
`#!/bin/sh
qterminal -e sudo apt dist-upgrade
echo end
read`

**Comment by ringo32** [comment]
is just you have to set 2 script, other contains :

> lxqt-sudo qterminal  -e (secondscript)
> echo end
> read

and in the second script is just

> apt dist-upgrade


depend what you set in, it runst then that script ad then have the read working
i use lxqt-sudo before qterminal but if you use sudo yeah then is after te -e

**Comment by ringo32** [comment]
no terminals does not wait after a (terminal) -e

**Comment by yan12125** [comment]
Create a script like this:
```
#!/bin/bash
# do some work
echo Done!
read
```
`chmod +x` the script, and run it with `qterminal -e script.sh`.
