### ISSUE TITLE
Ctrl-arrows not working to skip words on macOS

### ISSUE THREAD

**Issue by apjanke** [lxqt/qterminal#569]
Ctrl-arrow keys don't seem to do anything on macOS. Can someone help me debug this and see if it's an issue with QTerminal or with my shell configuration or something else? This backward/forward-word behavior is something controlled by the shell, so maybe QTerminal isn't passing Ctrl-arrow sequences along to the program it's running?

##### Expected Behavior

I'd expect Ctrl-arrow keys (Ctrl-left-arrow and Ctrl-right-arrow) to do a forward-word or backward-word action in my shells, either zsh or bash. They work in both zsh and bash under both Terminal.app and iTerm2.

Additionally, I'd expect Ctrl-V and then some modified arrow key to display the literal escape sequence sent by the arrow key. This works in both zsh and bash under both Terminal.app and iTerm2 as well. But it does nothing.

##### Current Behavior

Ctrl-arrow keys apparently do nothing. Ctrl-V appears to have no effect: instead of "pasting" in the verbatim escape sequence, it does the normal action of the subsequent arrow key that I press.

##### Steps to Reproduce (for bugs)
1. Launch qterminal on macOS and run `bash` in it
2. Type in `selkfj sdklfhj slfhj ksldfj sdjklfh`
3. Hit Ctrl-left-arrow a few times. Here's where it should move by word; instead it does nothing.
4. Hit left-arrow several times to move the cursor back a couple words.
5. Hit Ctrl-right-arrow. Here's where it should move forward by a word; instead it does nothing.

##### Context

This makes navigating and editing command lines harder. I'll often pull up a command line from history and want to change one of its middle arguments; Ctrl-left-arrow helps me get there quickly.

##### System Information

* Distribution & Version: macOS 10.14.3 with Xcode 10.1
* Kernel: Darwin Kernel Version 18.2.0
* Qt Version: Qt 5.12.1
* libqtxdg Version:  ???
* qtermwidget Version: head of `master` (commit e292763)
* lxqt-build-tools Version: 0.6.0
* Package version: head of `master` (commit aefdf8e)

**Comment by apjanke** [comment]
Ctrl-C, Ctrl-W, and Ctrl-U don't seem to do anything either. I'd expect them to cancel the current command, clear word backwards, or clear entire line, respectively.

**Comment by apjanke** [comment]
Actually, Ctrl combined with any almost any key seems to do nothing, at least in the `default` terminal emulation.

If I change the terminal emulation to `macbook`, then Ctrl- with most keys still does nothing, except:
* Ctrl-arrows go backward or forward one character
* Ctrl-C cancels command
* Ctrl-Shift-C cancels a command
* Ctrl-End enters an `F`
* Ctrl-Home enters an `H`
* Ctrl-PgUp enters a `1~`
* Ctrl-PgDn enters a `;1~`

Also the Menu key (that weird alternate Windows key on the right side of the keyboard seems to step back through my command history.

I'll have a look through the code and keytab files in QTermWidget and see if I can tell what's happening there on macOS.

**Comment by yan12125** [comment]
I believe https://gitlab.com/yan12125/macports-overlay/commit/f266c2d0a8d6813a25e0675a6ba5c2b4b0276086#68ee1803113ed81e5431e1c5f19074ed53c3ecf6 fixes it.

**Comment by apjanke** [comment]
I don't understand that patch, but I'll pull it and hack on it until I do. Thanks!

**Comment by apjanke** [comment]
I'll be darned; it is that simple: [`Qt::ControlModifier` and `Qt::MetaModifier` are swapped on macOS](https://doc.qt.io/qt-5/qt.html#KeyboardModifier-enum).

I pulled in your patch on my branch [fix-ctrl-key-on-macOS](https://github.com/apjanke/qtermwidget/tree/fix-ctrl-key-on-macOS). That wasn't enough to get Ctrl-arrow navigation working, but it made progress: the Ctrl-V command for verbatim insert in bash is working now, which will make debugging easier. I'll keep looking in to it.

**Comment by apjanke** [comment]
Oh! I had my emulation set to "macbook". Changed it to "default" or "linux" and now Ctrl-arrow navigation is working, and Ctrl-V reports reasonable escape sequences for Ctrl-arrow combinations. I'm going to review this a bit more and then submit a PR.

**Comment by apjanke** [comment]
#117 looks similar. Going to check that out while I'm at this.

**Comment by apjanke** [comment]
Related: #570

**Comment by apjanke** [comment]
Here's a PR: https://github.com/lxqt/qtermwidget/pull/261

**Comment by apjanke** [comment]
Hooray! It works now.
