### ISSUE TITLE
Auto-generate the bug report “System Information” section?

### ISSUE THREAD

**Issue by apjanke** [lxqt/qterminal#571]
Hi, QTerminal folks,

It's kind of inconvenient for users to fill out this System Information section:

```
##### System Information
<!--- Include as many relevant details about the system you experienced the bug in -->
* Distribution & Version: 
* Kernel: 
* Qt Version: 
* libqtxdg Version:  
* qtermwidget Version:
* lxqt-build-tools Version:
* Package version: 
```

They may not even know where to find all the relevant information, or make clerical errors when copying it into the bug report.

What do you think about something like a `qterminal --list-system-info` option that would generate that automatically for the user to just copy and paste here?

**Comment by agaida** [comment]
not really much - but we could enhanche lxqt-about

**Comment by tsujan** [comment]
In the case of QTerminal, qtermwidget, qterminal and Qt versions should be enough (but necessary).

Kernel version is almost always irrelevant, IMO. Distribution is there for us to know whether the report is from an Ubuntu user because Ubuntu bugs should not be reported here.

**Comment by apjanke** [comment]
Okay. I think I'll close this out then, and have a look at `lxqt-about`.

**Comment by agaida** [comment]
if we really want it i would suggest to add all possible components under our hood and give back  if installed. maybe a query functionality is useful for cli usage

**Comment by agaida** [comment]
^^ only a idea

**Comment by tsujan** [comment]
> maybe a query functionality is useful for cli usage

Good idea; a command to show the info only relevant to LXQt.

**Comment by agaida** [comment]
like
```
lxqt-about -v1..x (try inxi for an explanation)
lxqt-about --query $package
```

**Comment by tsujan** [comment]
I like it.

**Comment by agaida** [comment]
I'm really good in things that are not related to programming and computers :D

**Comment by tsujan** [comment]
I think it deserves a feature request of its own.

Sometimes, good ideas or weird problems are in font of our eyes but we don't see them -- in the case of problems, it's an automatic defense mechanism ;)

**Comment by yan12125** [comment]
libqtxdg should be removed - #572
