### ISSUE TITLE
terminal settings window is not scrollable

### ISSUE THREAD

**Issue by librewish** [lxqt/qterminal#574]
##### Expected Behavior

qterminal setting dialog/window/dialog should be scrollable
##### Current Behavior

when my font size is  11 and on 15.6 inch laptop screen with 1366x768 resolution
qterminal setting bottom part is not visible as it goes below the screen and no way to see it as scrolling is not implemented.
##### Possible Solution

implement scrolling in qterminal setting window/dialog
##### Steps to Reproduce (for bugs)

1. lxqt with kwin as window manager
2. 15.6 inch laptop screen 1366x768 resolution.
3. top panel.
4. noto sans 11 font.
5.qterminal >>> preferences dialog bottom part is not visible like applying setting

##### System Information

* Distribution & Version: manjaro lxqt-kwin
* Kernel: 4.19
* Qt Version: 5.12.1
* qtermwidget Version:0.14.1
* lxqt-build-tools Version:
* Package version: 0.14.1

**Comment by tsujan** [comment]
@librewish If you compile from source, please try this branch: https://github.com/lxqt/qterminal/tree/compact_settings

You could also test it without installation like:
```
mkdir build && cd build
cmake ..
make
./qterminal
```
The reason why I asked is that your screen is small.

**Comment by librewish** [comment]
yes it is scrollable and compact.
it fits my screen.

**Comment by tsujan** [comment]
Thanks for testing! I wanted to know whether the dialog would fit in the screen with your resolution and font size. Good to know that the answer is "yes" :)

**Comment by mpmc** [comment]
So glad this issue is here, I had exactly the same problem! Can't wait for the fix to be in master!

**Comment by yan12125** [comment]
Fixed thanks to @tsujan!
