### ISSUE TITLE
Clear screen(Ctrl+L) does not work in tmux with any type of terminal emulation

### ISSUE THREAD

**Issue by selivan** [lxqt/qterminal#577]
##### Expected Behavior

In tmux, after pressing Ctrl+L, cursor should go on the first line and all lines should be cleared. It works in gnome-terminal, for example.

##### Current Behavior

After pressing Ctrl+L cursor goes on the first line, but text on lines below is not cleared. Screenshot:

![image](https://user-images.githubusercontent.com/1208989/54494499-f7000980-48eb-11e9-9c88-ea7499bc8ae4.png)

##### Steps to Reproduce (for bugs)
1. Open qterminal
2. Launch tmux
3. Use any command that provides output, like `ls`
4. Press Ctrl+L
5. Cursor goes to the first line, but lines below are not cleared

##### Context

This bug reproduces with any type of terminal emulation: default, vt420pc, macbook, linux, solaris. Ctrl+L works fine in gnome-terminal on the same machine.

tmux version: 2.6-3ubuntu0.1

##### System Information
* Distribution & Version: Ubuntu GNU/Linux 18.04 Bionic
* Kernel: 4.15
* Qt Version: 5.9.5
* qtermwidget Version: 0.8.0-5
* lxqt-build-tools Version: none
* Package version: 0.8.0-4

**Comment by agaida** [comment]
might be a downstream issue or an issue with this outdated version of qterminal. Works fine with 0.14.1.

**Comment by tsujan** [comment]
Confirming @agaida's observation: works without problem with the latest release.

**Comment by selivan** [comment]
@agaida @tsujan Any idea on how to get required patch for qterminal or qtermwidget 0.8.0? This version is installed in latest Ubuntu LTS 18.04 Bionic, that is going to be popular for several next years. I suppose package maintainers will accept the patch.

There is no way to install fresh lxde packages on LTS(there is no ppa or other repository), just compile it from source(which again requires first to build from source newer cmake than the one available in bionic), and that is not nice and easy way for binary distro users.

**Comment by agaida** [comment]
Thats a clear downstream problem - and no, i don't think that it will be solved for 18.04 - lucky us. To be more verbose. LTS means also that bugs are long term stable, as long there is no security relevance. Dunno if LTS have backport repos.

**Comment by agaida** [comment]
BTW - of course, one could try some ppa's if available, but that contradicts the meaning of LTS

**Comment by selivan** [comment]
@agaida Ubuntu LTS has backports, but there is no lqxt/qterminal packages there.

ppa's do not contradict meaning of LTS: I want my system to be stable for years without worrying about breaking something on each update, but I also want to have fresh versions of non-system software I use. Unfortunately, there is no distro with perfect balance, ppa's are workaround. Snap/flatpack solve this, but they have their own problems...

BTW, it might be a good idea to have a snap package with latest LXQT software. It will make a lot of Ubuntu users happy and thinking about switching to LXQT :)

**Comment by agaida** [comment]
We will never ever provide snaps - sorry, wasn't a good idea the first time i closed such a bug a few years ago, it is not a good idea now - and btw: There are these guys who maintain (L)ubuntu: Maybe they are happy if they could spend their time on an mostly ubuntu centric package format.

**Comment by tsujan** [comment]
> I want my system to be stable for years without worrying about breaking something on each update

Then, you should either forget about bug fixes or use a rolling distro (= with continuous, small updates).

Rolling distros usually have Stable, Testing and Unstable versions. Contrary to what some people may believe, "Unstable" isn't unstable most of the time and "Testing" is damn stable. "Stable" usually means stable+archaic -- like "LTS" -- and can be good for servers.

**Comment by agaida** [comment]
LTS can be good for corporate environments too - where users has defined workflows, maybe need some specific versions of programs (that are being audited etc for usage with certain commerzial applications and workflows). In such environments be prepare to be rightfully fired witout warning when you do system updates on your own. 

For mere humans there are a few choices: Use a distribution with a fast release cycle or rolling. If upgrading a distribution with a fast release cycle is error prone - hit the maintainers to do their job. Or use something different. If rollig breaks to often - learn how to handle it or search a distribution where such things don't happend to often.
