### ISSUE TITLE
Expose COLORTERM environment variable

### ISSUE THREAD

**Issue by mscdex** [lxqt/qterminal#595]
##### Expected Behavior
An environment variable is set to determine 24-bit color support programmatically.

##### Current Behavior
`COLORTERM` nor any other unique (to qterminal/qtermwidget) environment variable is set to be able to programmatically detect 24-bit color support.

##### Possible Solution
Automatically set `COLORTERM=truecolor` in the environment.

##### Context
Many terminals utilize the `COLORTERM` environment variable to allow third parties to easily detect 24-bit color support. Other terminals that do not utilize this specific environment variable use other environment variables that can still lead to reliable 24-bit color support detection (e.g. for VTE-based terminals, checking the version in the environment variable `VTE_VERSION`).

**Comment by agaida** [comment]
no, i guess we don't want that
if someone want to know what terminal emulation is used - it is grep env for term

**Comment by mscdex** [comment]
`TERM` does not tell the whole picture and is insufficient for knowing if 24-bit color is supported.

**Comment by yan12125** [comment]
I've once tried `TERM=xterm-direct` but seems many applications are incompatible with it. COLORTERM is a reason alternative IMO. Yet another option is `TERM_PROGRAM`, which is less than ideal as qtermwidget can be embedded in applications other than qterminal.

**Comment by agaida** [comment]
@mscdex sorry, my knowledge was outdated, my latest info was that COLORTERM is outdated and should not be used. Reality says otherwise. 
@yan12125 - we should implement it, if possible in the same row where we set XTERM, possible values COLORTERM=no|__yes__|truecolor

#### TESTS
open xterm
* TERM=xterm-256colors COLORTERM=true mc
* TERM=xterm-256colors COLORTERM=truecolor mc

try the same in qterminal with mc set to a 16M theme

**Comment by yan12125** [comment]
qtermwidget now exposes COLORTERM=truecolor by default.

**Comment by sisrfeng** [comment]
> open xterm
> 
> * TERM=xterm-256colors COLORTERM=true mc
> * TERM=xterm-256colors COLORTERM=truecolor mc
> 
> try the same in qterminal with mc set to a 16M theme

Should it be this ?

`TERM=xterm-256color COLORTERM=truecolor mc`
