### ISSUE TITLE
QTerminal can be be made too small

### ISSUE THREAD

**Issue by tsujan** [lxqt/qterminal#612]
This report isn't related to remembering/setting the size, which can be done appropriately now.

You could resize QTerminal to something like this:

![tiny](https://user-images.githubusercontent.com/981076/63228198-05d54a00-c205-11e9-8e51-a10824581376.png)

This spectacle can be prevented by setting a minimum size. IMO, 300×200 is good; although it's very small but it's only a minimum and is far better that the above screenshot.

**Comment by chriswyatt** [comment]
This would be a shame. I use tiny terminals to block out people eating in group video chats! I'm sure I could find some other tiny app to place over their heads though. Minor inconvenience.

**Comment by tsujan** [comment]
Oh, this was fixed in https://github.com/lxqt/qterminal/commit/56176bdac3b30b868a5010c29d894cbf75664835

 Now, the min. width is 10×space-width (= 10 characters) and the min.height is the font height.
