### ISSUE TITLE
Context menu should have a toggle for Window Decorations / Window Border

### ISSUE THREAD

**Issue by agaida** [lxqt/qterminal#613]
I can live without the menu toggle in the view menu, but the context menu should/must have a toggle for window decorations

![](https://i.imgur.com/KB4v0Cx.jpg)

Follow up to #611

**Comment by tsujan** [comment]
I agree. For the next release or after it?

**Comment by agaida** [comment]
if it is easy, for the next - otherwise after - doesn't really matter

**Comment by tsujan** [comment]
Should be easy.
