### ISSUE TITLE
configuration updates fail - or messages are misleading

### ISSUE THREAD

**Issue by agaida** [lxqt/qterminal#616]
started from terminal:
```
 % qterminal  
Properties constructor called  
Warning: Configuration file was written by a newer version  of QTerminal.  
Some settings might be incompatible.
```
Doesn't change when restarted, even if settings are changed.

##### System Information
latest git

**Comment by agaida** [comment]
https://github.com/lxqt/qterminal/pull/582 - maybe working on this will help.

**Comment by tsujan** [comment]
Lexically, the string "0.14.1" is less than "0.9.0", for example; hence the message.

**Comment by tsujan** [comment]
The fix: https://github.com/lxqt/qterminal/pull/617

**Comment by yan12125** [comment]
Thanks! Haven't had time to look into it :/
