### ISSUE TITLE
Unable to remove/disable (default) shortcuts

### ISSUE THREAD

**Issue by logol** [lxqt/qterminal#621]
##### Expected Behavior
- editable shortcuts (not the mnemonics) can be set empty in the `Shortcut Editor`
- editable shortcuts can be changed by editing the `qterminal.ini`
- if no `qterminal.ini` is present, settings should be restored to defaults properly

##### Current Behavior
- shortcuts cannot be disabled in the `Shortcut Editor` only replaced by new ones (maybe I am stupid but I didn't figure out how to do this)
- shortcuts changed by editing the `qterminal.ini` are not stored, instead settings are restored from a previous session magically e.g. with changes made with the `Shortcut Editor` before

##### Possible Solution
> if no `qterminal.ini` is present, settings should be restored properly

restore defaults to values that are hard coded or read from a higher system file e.g. /etc/qterminal/qterminal.ini

##### Steps to Reproduce (for bugs)
1. change "Add Tab" to `Ctrl+F1` using the `Shortcut Editor`, apply & close settings
2. edit the `qterminal.ini` using a text editor

```
[Shortcuts]
Add%20Tab=
```
or remove all lines below `[Shortcuts]`

3. close and restart qterminal
4. check the shortcuts in the `Shortcut Editor`
5. check the shortcuts in the `qterminal.ini`

##### Context
- tried to disable (default) shortcuts completely

##### System Information
* Distribution & Version: Arch Linux (all packages up to date)
* Kernel: 5.2.9-arch1-1-ARCH SMP PREEMPT x86_64 GNU/Linux
* Qt Version: 5.13.0
* qtermwidget Version: 0.14.1
* lxqt-build-tools Version: 0.6.0
* qtermwidget (lxqt/qtermwidget@9b12c21246fb085cd51d6cca2464956aa778f2d4) and qterminal  (1616d19468420004692a6ef4eb59323113b069de) have been build from master branch

**Comment by tsujan** [comment]
Press a modifier (like Shift) and they will be removed.
