### ISSUE TITLE
"highlight all matches" not working

### ISSUE THREAD

**Issue by anilFree** [lxqt/qterminal#622]
In find ui, there is an option to "highlight all matches", it doesn't work at all.
only one match is highlighted.

qterminal version 0.14.1
qt version 5.11.3
distro: debian unstable

**Comment by tsujan** [comment]
Confirming.

I'm not sure if it stopped working after a commit or never worked.

**Comment by lameventanas** [comment]
I hope this can be fixed soon.

**Comment by deathtrip** [comment]
Yeah. not working for me either.

**Comment by stefonarch** [comment]
Duplicate of https://github.com/lxqt/qterminal/issues/120
