### ISSUE TITLE
Support mixed font rendering

### ISSUE THREAD

**Issue by konomikitten** [lxqt/qterminal#627]
##### Expected Behavior
Rendering of mixed fonts.

##### Current Behavior
At the moment qterminal only allows for using a single font for rendering. A good example for this is how you're unable to see emoji from the Noto Color Emoji font when not using it as your main font for qterminal.

![qterminal-xfce-terminal](https://user-images.githubusercontent.com/12713710/64466268-6a286100-d154-11e9-8688-5daa23ad08ec.png)

##### Possible Solution
None.

##### Steps to Reproduce (for bugs)
1. Select a font other than Noto Color Emoji
2. Copy some emoji to your clipboard
3. Paste it into qterminal

##### Context
Not sure what to put here.

##### System Information
* Distribution & Version: Debian GNU/Linux bullseye/sid
* Kernel: Linux debian 5.2.0-2-amd64 #1 SMP Debian 5.2.9-2 (2019-08-21) x86_64 GNU/Linux
* Qt Version: 5.11.3+dfsg1-4
* qtermwidget Version: 0.14.1-1
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Would you please name a terminal emulator that does that? I do the same thing with gnome-terminal and it shows nothing at all.

**Comment by konomikitten** [comment]
@tsujan the image shows qterminal on the left and xfce4-terminal on the right. xfce4-terminal supports mixed rendering.

**Comment by tsujan** [comment]
xfce4-terminal is exactly like gnome-terminal here: shows nothing at all, even when I choose Noto Color Emoji as its font. It should be some other setting in your case.

**Comment by konomikitten** [comment]
> xfce4-terminal is exactly like gnome-terminal here: shows nothing at all, even when I choose Noto Color Emoji as its font. It should be some other setting in your case.

I think you must have something wrong on your end because I can clearly get it working here. Screenshot below.

![xfce4-terminal-rendering-multiple-fonts](https://user-images.githubusercontent.com/12713710/64474820-8d3b2b00-d1bd-11e9-9315-55f33df7e4f7.png)

**Comment by tsujan** [comment]
Back to front: xfce4-terminal, gnome-terminal, qterminal:

![terminals](https://user-images.githubusercontent.com/981076/64474838-b0e77c80-d18f-11e9-9d97-a143b2809189.png)

The xfce4-terminal's settings are as in your screenshot.

**Comment by konomikitten** [comment]
@tsujan could be your distro I'm not sure I know for a fact on two Debian bullseye installs this works correctly on xfce terminal.

**Comment by tsujan** [comment]
I may be wrong but I guess this isn't about the terminal itself.

**Comment by tsujan** [comment]
@yan12125 is the expert in this area. Let's wait for him to see this.

**Comment by tsujan** [comment]
OK, I was right: This doesn't have anything to do with terminals.

Read https://www.reddit.com/r/linux/comments/ao0mp3/how_to_better_enable_color_emojis/ , do as it says, and you'll have colored emoji inside QTerminal, FeatherPad,... without needing to change their fonts.

**Comment by agaida** [comment]
ok - after 0.15 - maybe before we have to polish some configurations - font config is one of them, there is an ancient debian report about and the report is right - will file something if not in our bugs yet

**Comment by tsujan** [comment]
@agaida These emoji's need special fonts. Adding 4 lines to `fonts.conf` is easy but font config should first check if the required font(s) are installed.

Anyhow, although this report wasn't valid, it had a good result.

**Comment by agaida** [comment]
grml - we shouldn't use fonts:conf any longer - thats what the debian report is about - instead we should use fonts.conf.d

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834599

**Comment by tsujan** [comment]
OK. In any of these cases, two things need to be added:

 1. High priority: A configuration for monospace, so that the user could choose it (if he/she wants to).

 2. Low priority: Another configuration for choosing a monospace (colored) emoji font.

Would you open an issue for them and also for `fonts.conf.d`?

**Comment by konomikitten** [comment]
The `~/.fonts.conf` vs `~/.config/fontconfig/conf.d/` is not an issue as I was able to get fonts rendering this way:

`sudo editor ~/.config/fontconfig/conf.d/99-noto-mono-color-emoji.conf`

```xml
<?xml version="1.0"?>
<!DOCTYPE fontconfig SYSTEM "fonts.dtd">
<fontconfig>
  <match target="pattern">
    <test qual="any" name="family"><string>mono</string></test>
    <edit name="family" mode="assign"><string>monospace</string></edit>
  </match>
  <match>
    <test name="family"><string>monospace</string></test>
    <edit name="family" mode="prepend" binding="strong"><string>Noto Color Emoji</string></edit>
  </match>
</fontconfig>
```
`fc-cache -rf`

Working emoji terminus and Noto:

![sort-of-working](https://user-images.githubusercontent.com/12713710/64477043-0779a880-d1da-11e9-991b-4ac1b10ca501.png)


But doing things like this have side affects, whatever font you match in this case `monospace` will be affected by the change and now in Feather you can see it affecting all monospace fonts.


With `~/.config/fontconfig/conf.d/99-noto-mono-color-emoji.conf`.

![with config](https://user-images.githubusercontent.com/12713710/64477020-c2ee0d00-d1d9-11e9-8bb3-b4c474de9029.png)

Without `~/.config/fontconfig/conf.d/99-noto-mono-color-emoji.conf`.

![without-config](https://user-images.githubusercontent.com/12713710/64477025-ced9cf00-d1d9-11e9-86db-8a18eac23cb0.png)

Using font-config matching is not the answer, though I am not saying that I do know what xfce4-terminal is doing to render correctly and I certainly didn't have to go messing about with font-config matching it just worked.

**Comment by tsujan** [comment]
> But doing things like this have side affects, whatever font you match in this case monospace will be affected by the change

→ What I said above about monospace. Something like this:

```xml
 <alias>
  <family>monospace</family>
  <prefer>
   <family>DejaVu Sans Mono</family>
  </prefer>
 </alias>
```

> ...didn't have to go messing about....

This isn't "messing" but "configuring". Of course, anyone could mess with any configuration.

**Comment by agaida** [comment]
@tsujan - right now i'm working on `lxqt-kcm-integration` - will file the bugs afterwards - and if the kcm integration is done we can have i look what we can and should borrow from the KDE guys.

**Comment by konomikitten** [comment]
> his isn't "messing" but "configuring". Of course, anyone could mess with any configuration.

That will still make DejaVu Sans Mono render incorrectly and once again xfce terminal did not need configuring and works even without the fontconfig changes you've shown so how do you explain that?

**Comment by tsujan** [comment]
@konomikitten 

All in all:

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <!-- Previous lines, if any -->
 <!-- For colored emojis: -->
 <match target="pattern">
  <test name="family"><string>monospace</string></test>
  <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
 </match>
 <!-- To fix monospace, which lacked boldness after an update: -->
 <alias>
  <family>monospace</family>
  <prefer>
   <family>DejaVu Sans Mono</family>
  </prefer>
 </alias>
</fontconfig>
```
LXQt font config should do it automatically in future.

@agaida I don't think KDE has what I requested above. I might look into it when I find the time.

**Comment by tsujan** [comment]
> how do you explain that?

I can't explain what a GTK terminal does -- a terminal that can't insert emojis even with the correct font and have problems in text rendering (see my screenshot). GTK apps may need some things that only GTK DEs provide.

**Comment by konomikitten** [comment]
Just a little note that tripped me up for a bit, configs in `~/.config/fontconfig/conf.d/` should start with a number or they are ignored.

**Comment by konomikitten** [comment]
@tsujan I refined the config down you don't need the work around `alias`.

`~/.config/fontconfig/conf.d/99-emoji.conf`

```xml
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
  <match target="pattern">
    <test name="family"><string>monospace</string></test>
    <edit name="family" mode="append"><string>Noto Color Emoji</string></edit>
  </match>
</fontconfig>
```
This seems to work with no issues and be the most minimal form, being a `conf.d` file qterminal wouldn't have to worry about clobbering the users config either.

**Comment by konomikitten** [comment]
Also interestingly even with the config there are still differences between `xfce-terminal`. Note the flags at the bottom.

xfce-terminal
![xfce-terminal](https://user-images.githubusercontent.com/12713710/64477767-dbaef080-d1e2-11e9-8980-6435e656922e.png)

qterminal with config change
![qterminal-with-config](https://user-images.githubusercontent.com/12713710/64477772-dfdb0e00-d1e2-11e9-9412-f6e160f83930.png)

**Comment by tsujan** [comment]
@konomikitten 

It depends on the system and its font configs. Hopefully, we won't need to edit the file manually in near future.

Those flags are OK in FeatherPad with `U+E006E U+E0067 `, `U+E0063 U+E0074 `,... but not in QTerminal. They don't have a single code; that may be somehow relevant.

As for how GTK does it, I think it has its own settings. In Arch, xfce4-terminal needs libxfce4ui, libxfce4util and xfconf but they can't fix xfce4-terminal's problem. Maybe another xfce package is needed too. For now, I don't have time to investigate it.

**Comment by konomikitten** [comment]
@tsujan least this gets it somewhat usable now.

**Comment by tsujan** [comment]
@konomikitten If you find time, please see what happens with Konsole. I'm like this now: 🤪

**Comment by konomikitten** [comment]
@tsujan the config works fine with konsole too, ignore the weird spacing when typing it isn't related to the config

Konsole
![konsole](https://user-images.githubusercontent.com/12713710/64478146-4b26df00-d1e7-11e9-859f-3beafabdc797.png)

**Comment by agaida** [comment]
@konomikitten - the numbers are important in cases where the sort in which the configs are readed are important - so it is good practice that the basic configurations (upstream) are read first, afterwards the distribution configs - after that the derivatives and other configs - so we should not provide 99-foo.conf as upstream :P

**Comment by tsujan** [comment]
@konomikitten Thanks! So, those flags aren't specific to QTerminal, although they aren't related to Qt either.  QTerminal was forked from Konsole a long time ago.

**Comment by tsujan** [comment]
Attached are thousands of emojis for those who want to test quickly. All of them should be seen correctly in FeatherPad if the font config is right.

[emojis.zip](https://github.com/lxqt/qterminal/files/3586941/emojis.zip)

**Comment by yan12125** [comment]
I have enabled wiki for qterminal some time ago. Feel free to write fontconfig tricks there. https://github.com/lxqt/qterminal/wiki
