### ISSUE TITLE
Shift-Tab behaves differently depending on presence of tab navigation buttons.

### ISSUE THREAD

**Issue by steventux** [lxqt/qterminal#629]
##### Expected Behavior

Regardless of how many terminal tabs are open in QTerminal Shift+Tab is captured as console input (eg. to un-indent text in Vim).

##### Actual Behaviour

With multiple tabs open (and tab 'arrow' navigation buttons appear on QTerminal window)
Shift-Tab moves focus to the tab navigation 'back' button.

##### Possible Solution

Given tabs work as expected regardless of tab navigation being present, Shift-Tab input should consistently be passed to the terminal.
There seems to be an explicit case made in a conditional here: https://github.com/lxqt/qterminal/blob/56176bdac3b30b868a5010c29d894cbf75664835/src/propertiesdialog.cpp#L57 dealing with those two key combos but this concerns a different dialogue.

##### Steps to Reproduce (for bugs)

1. Open multiple terminal tabs until tab navigation arrows appear:
![Screenshot from 2019-09-10 09-24-29](https://user-images.githubusercontent.com/93511/64596975-d3a2ac80-d3ac-11e9-9e94-3687707d329b.png)

2. Use Shift-Tab key combination

![Screenshot from 2019-09-10 09-26-03](https://user-images.githubusercontent.com/93511/64597101-0a78c280-d3ad-11e9-87c0-19f31a46ca10.png)

##### Context

For Vim use this limits how many terminal tabs I can open and effectively use Tab / Shift-Tab as indentation (or any other sort of) keyboard shortcuts. This differs from LXTerminal and many others and _feels_ a bit inconsistent as the behaviour differs depending on the number of terminal tabs open.

The workaround is not to open too many tabs which I can live with. I've logged the issue as it took me a while to figure out what was going on, hopefully this will save others a bit of time.

##### System Information
* Distribution & Version: Lubuntu 19.04
* Kernel: 5.0.0-27-generic #28-Ubuntu SMP
* Qt Version: 5.12.2
* qtermwidget Version: 0.14.1
* lxqt-build-tools Version: 
* Package version: 

- [ ]

**Comment by tsujan** [comment]
> There seems to be an explicit case made in a conditional here:

Not related at all.

`Shift+Tab` is backtab and changes the focus widget in the reverse order. To prevent that, the terminal widget needs to consume it, like text editors do.

**Comment by steventux** [comment]
@tsujan I'd be happy to attempt a PR if you can point me in the right direction. Not that familiar with the project.

**Comment by tsujan** [comment]
@steventux I'm afraid I don't remember the code but it shouldn't be difficult. For now, I'm a little busy with other projects. Will fix it as soon as I find the time.

**Comment by tsujan** [comment]
@steventux, I took a look at it.

Please go to `qtermwidget` → `TerminalDisplay.cpp` → `bool TerminalDisplay::event(QEvent* event)` and add the following `case` to the `switch`:

```c++
    case QEvent::KeyPress:
        if(((QKeyEvent*)event)->key() == Qt::Key_Backtab)
        {
            event->accept();
            return true;
        }
```

Does that solve your problem?

**Comment by steventux** [comment]
@tsujan Focus remains in the terminal window with this case, it no longer changes focus to the tab navigation so the case statement appears to be in the right place. 
I get no input into the terminal though, ie. the back-tab keystroke appears to do nothing regardless of the presence of tab navigation buttons so perhaps `event->accept()` is not behaving as expected? Other keystrokes work fine.

**Comment by tsujan** [comment]
Thanks for testing!

> I get no input into the terminal though

That was what I worried about ;)

Would you please explain to me how to test backtab with QTerminal? I tried vim inside QTerminal, Konsole and gnome-terminal but backtab didn't un-indent text -- actually, vim has `Ctrl+D` for un-indenting.

**Comment by steventux** [comment]
My vim config for this particular setting:
https://github.com/steventux/vimfiles/blob/master/vimrc#L28

```
vmap <TAB> >gv
vmap <S-TAB> <gv
```

You can add this to your `~/.vimrc` file for quick testing. I've `vmap`d them so you need to enter visual mode to test (esc then v).

**Comment by tsujan** [comment]
What I needed! Will do tests in my free time. Thank you very much!
