### ISSUE TITLE
noise when starting a terminal from command line

### ISSUE THREAD

**Issue by alvherre** [lxqt/qterminal#634]
####  Expected behavior

When I start a new terminal from a command line (another terminal), I expect that the console that I launch it from should be silent. No other terminal that I use (I am switching from lxterminal, previously used rxvt and xterm) do any similar things.

#### Current behavior
This text appears:

```
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_es_CL.qm" from dir /usr/share/qterminal/translations
load success: true
QDir::exists: Empty or null file name
Canot open file "/home/alvherre/.config/qterminal.org/qterminal_bookmarks.xml"
Trying to load translation file from dir "/home/alvherre/.local/share"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
Translations found in "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
Shell program: "/bin/bash"
("/bin/bash")
```

This looks like debugging output and is pretty uncomfortable.

##### Suggested solution

I suggest that some debugging option is turned on by default and it shouldn't.

##### System Information

* Distribution & Version: Debian 10.1
* Kernel: .19.67-2+deb10u1 (as packaged by Debian)
* Qt Version: 5.11.3
* qtermwidget Version: 0.14.1
* lxqt-build-tools Version: (no idea)
* Package version: 0.14.1-1

**Comment by tsujan** [comment]
I second that.

IMHO, it's better to remove this kind of output everywhere. Developers could always add `qDebug() << ...` *temporarily* to find and fix problems; users -- including developers as users -- don't need to see it later. And if a GUI app needs to inform users about real problems, message boxes could be used.

**Comment by tsujan** [comment]
Some apps may need it in a state of transition -- like when libfm was being ported into C++11 -- but I think we've passed that phase.
