### ISSUE TITLE
Custom window names

### ISSUE THREAD

**Issue by morfikov** [lxqt/qterminal#637]
I just came across this `qterminal` and wanted to replace my current terminal with it. The problem is I don't really know how to change the `qterminal` window name based on profile name or some custom text. Here's how it looks like now:

```
$ obxprop | grep NAME
_OB_APP_GROUP_NAME(UTF8_STRING) =
_OB_APP_NAME(UTF8_STRING) = "qterminal"
_NET_WM_VISIBLE_ICON_NAME(UTF8_STRING) = "QTerminal"
_NET_WM_VISIBLE_NAME(UTF8_STRING) = "QTerminal"
_NET_WM_ICON_NAME(UTF8_STRING) =
WM_NAME(STRING) = "QTerminal"
_NET_WM_NAME(UTF8_STRING) = "QTerminal"
```
So is there a way to add some constant string in the `_NAME`, so the window manager could easily target the right `qterminal` window?

##### System Information

* Distribution & Version: Debian Sid
* Kernel: 5.3.7
* Qt Version: 5.11.3
* qtermwidget Version:  0.14.1
* lxqt-build-tools Version: 0.6.0-2
* Package version: 0.14.1

**Comment by yan12125** [comment]
I assume you are on X11? Then you can use the Qt option `-name` to specify `WM_NAME`. See also https://github.com/lxqt/qterminal/issues/334 for previous discussions.

**Comment by morfikov** [comment]
Yes, it works with `-name` , thanks.
