### ISSUE TITLE
Is there a way to open new windows as part of an existing instance without navigating to an open window of that instance?

### ISSUE THREAD

**Issue by marlonn** [lxqt/qterminal#644]
Whenever I open a new qterminal window through my window manager's shortcut, it creates a new qterminal instance. Obviously, this eats a lot of RAM if you have 20 qterminal windows. I know that you can keep new windows in the same instance if you open them from another qterminal window with Ctrl+n, but you have to navigate to that window first. 

Basically, I'd like to get the same behavior as with lxterminal. 

Is this currently possible, and if not, would it be possible to add this functionality?

**Comment by tsujan** [comment]
A single-instance app is possible but may not be desirable. Sorry, I don't remember the reason I found for its probable undesirability (at https://github.com/lxqt/qterminal/issues/402#issuecomment-535597672).

If it doesn't have any drawback, it'll need a code overhaul. So, I don't think it'll happen soon.

@yan12125, what do you think?

**Comment by yan12125** [comment]
An possible alternative might be calling the dbus API to create a new tab instead of running another qterminal process.

**Comment by yan12125** [comment]
> An possible alternative might be calling the dbus API to create a new tab instead of running another qterminal process.

Here is an example:
```
gdbus call --session --dest org.lxqt.QTerminal-613442 --object-path / --method org.lxqt.QTerminal.Process.newWindow "{}"
```

https://github.com/lxqt/qterminal/issues/402 is probably the only feature that needs the single-instance model. Please move there for further discussions, thanks!
