### ISSUE TITLE
QTerminal fails to start on Wayland platforms

### ISSUE THREAD

**Issue by yca** [lxqt/qterminal#645]
I'm trying to run QTerminal on barebone Wayland backends but I'm taking error during start:
```
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/share/qterminal/translations
load success: false
Canot open file "/home/admin/.config/qterminal.org/qterminal_bookmarks.xml"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
loadAllColorSchemes
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
Shell program: "/bin/bash"
("/bin/bash")
Using a variable-width font in the terminal.  This may cause performance degradation and display/alignment errors.
Segmentation fault (core dumped)
```

Please note that I don't have lxqt as my desktop environment. I'm launching some Wayland compositors before starting QTerminal. I tried weston and some example compositors from QtWayland project. QTerminal is started with the following command:

```
$>qterminal -platform wayland
```
Please note that I'm able to run my custom Qt applications on this setup.

##### Expected Behavior
I'm not sure if this is the intended behavior but I expect QTerminal to run on this config without much effort.
##### Current Behavior
QTerminal crashes.

##### Possible Solution
Probably bug is related to QTermWidget, which also crashes with a similar pattern.

##### Steps to Reproduce (for bugs)
1. Setup a recent Arch Linux.
2. Start weston reference compositor:
```
$>weston
```
3. Start QTerminal in another terminal, ssh probably:
```
$>qterminal -platform wayland
```
##### System Information

* Distribution & Version:  Arch Linux rolling
* Kernel: 5.3.8-arch1-1
* Qt Version: 5.13.2
* qtermwidget Version:  
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
QTerminal runs fine under wayland.; for example weston (`qterminal -platform wayland`):

![weston](https://user-images.githubusercontent.com/981076/68300106-62346100-00b2-11ea-9957-5df8e8b0f92e.png)

Maybe, you don't have the latest git version of qterminal.

**Comment by yca** [comment]
Yes you are right. Current master works as expected. For the reference, Arch has 0.14.1 in its repo.

**Comment by tsujan** [comment]
For LXQt and/or its components, please use the latest git.
