### ISSUE TITLE
QTerminal arrow keys do not function properly on 2nd user but 1st user is fine .. 

### ISSUE THREAD

**Issue by ssdirect** [lxqt/qterminal#646]
Running Lubuntu 19.4 and 19.10 with QTerminal 0.14.1 even with brand new install the first user can use the up, down, left and right arrow keys in terminal window to retrieve command history or move back/forth within a line, but with the second user, this functionality is missing. Instead, only ^[[A ^[[B ^[[C or ^[[D characters are displayed. Somewhat annoying for that user ..

##### Expected Behavior

The up/down arrows should display the most recent command line history up/down, the left/right arrows should allow user to move back and forth within the currently typed command.
  
##### Current Behavior

Works correctly with first user on system, for the second+ user the ^[[ characters are displayed instead ..

##### Steps to Reproduce (for bugs)

1. first user works as expected, but
2. add user using Users and Groups with user name eg user2 and group users
3. logout of user one and into user two and open a QTerminal window
4. arrow keys produce ^[[A for up ^[[B for down ^[[C for right and ^[[D for left arrow key presses instead of command history etc.

##### System Information

* Distribution & Version: 
* Kernel: 
* Qt Version: 
* qtermwidget Version: 
* lxqt-build-tools Version: 
* Package version: 

latest Lubuntu 19.10 download also same issue in 19.04
Linux version 5.3.0-18-generic (buildd@lcy01-amd64-027) (gcc version 9.2.1 20190909 (Ubuntu 9.2.1-8ubuntu1)) #19-Ubuntu SMP Tue Oct 8 20:14:06 UTC 2019 (Ubuntu 5.3.0-18.19-generic 5.3.1)
LXQt Version 0.14.1
Qt 5.12.4

**Comment by agaida** [comment]
and why is this an upstream problem? @wxl - can you please check?

**Comment by stefonarch** [comment]
Happens truely if login shell is /bin/sh and not /bin/bash
Probably everywhere.
No issue.

**Comment by yan12125** [comment]
> arrow keys produce ^[[A for up ^[[B for down ^[[C for right and ^[[D for left arrow key presses instead of command history etc.

Sounds like the `$TERM` variable is not correctly configured or the shell does not honor it.

**Comment by stefonarch** [comment]
In the "User and Groups \ >Advanced Tab" when creating a new user default shell is bin/sh, at least in VM with Lubuntu.
Here it looks as default shell isn't set if no choice is made but not sure.

**Comment by yan12125** [comment]
Oh, I didn't notice the original poster uses Lubuntu. I guess like Debian, /bin/sh on Lubuntu is dash? Then arrow keys do not work out of box - https://unix.stackexchange.com/questions/21733/why-dont-my-arrow-keys-work-in-sh
