### ISSUE TITLE
"Remove newline" not respected when d&d comand

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#652]
Not quite sure about this, but yesterday I learned that some people (really!) use drag and drop from webpages ecc into the terminal. Setting "remove newline" in the preferences works only with pasting, comands dragged into the terminal get immediately executed always if there is a new line.

##### Expected Behavior

Always remove  newline if it's set in preferences
##### Current Behavior

Comands get executed if dragged into qterminal.

##### Steps to Reproduce (for bugs)

1. Qterminal > preferences > behaviour - actions after paste, select "remove newline" and apply.
2. Comand:

```
touch /tmp/empty_file

```
3. select all of the above including newline and dragit  in a qterminal window . 
4. The comand is executed
5. Select all of the above, copyand paste it, qterminal will not execute it. 

##### System Information

* Distribution & Version: arch linux up to date

**Comment by tsujan** [comment]
I tested with Firefox and can confirm the problem.

But I also saw a more serious problem that may need a report of its own: Text DND from Qt apps doesn't work, while QTerminal is a Qt app itself! I tested with FeatherPad, Kate and Falkon.

**Comment by stefonarch** [comment]
> Text DND from Qt apps doesn't work, while QTerminal is a Qt app itself!

Sure? My first test yesterday I did with some comand from featherpad, it worked but made a cut&paste, in featherpad I did cltr+z to make reappear the comand+newline.

**Comment by tsujan** [comment]
Here, with FeatherPad, cut is done but paste isn't. With Kate, neither is done.

The silly thing is that DND works from FeatherPad to Firefox's address bar and from Firefox to FeatherPad BUT nothing works with Falkon. Of course, FP to FP works but *Kate to Kate doesn't!*

Something's wrong with text DND between Qt apps.

I haven't tested with another window manager yet -- I use the latest KWin.

**Comment by tsujan** [comment]
It wasn't KWin's fault. They happen under Enlightenment too.

Anyhow, it isn't specific to QTerminal but QTerminal to QTerminal doesn't work here.

**Comment by stefonarch** [comment]
Hm, actually I did test this bug report using falkon under debian/openbox 32bit and DND worked as it did with featherpad, now on my main PC it doesn't as you say, this with Kwin. Will switch to openbox now and report. Maybe debian has an older qt version.

**Comment by stefonarch** [comment]
Not sure, tried to find it:
https://bugreports.qt.io/browse/QTBUG-80786

**Comment by tsujan** [comment]
> Not sure, tried to find it:
> https://bugreports.qt.io/browse/QTBUG-80786

It should be related if not the same bug. (You deleted your good comment?)

> here it's 5.13.2-3
Here too.

I'll test with my older laptop, which has Qt 5.12.

**Comment by tsujan** [comment]
OK, it's another serious bug in Qt 5.13. Qt 5.12 doesn't have any problem, even with KWin.

I think we'll have to tolerate it in Qt 5.14 too.

**Comment by stefonarch** [comment]
Yeah I deleted it, thought it wasn't related at all ;)
I had to abandon arch32 on my laptop, twice now qt5 was completely broken, but looking at this here I think debian isn't bad at all.

But actually all this isn't related really to the DND bug in qterminal no?

**Comment by tsujan** [comment]
> But actually all this isn't related really to the DND bug

No, they aren't related to each other.

**Comment by stefonarch** [comment]
Just drop a note here, I noticed that drag&drop in split view (F6) in pcmanfm-qt crashes it while copy&past works.

**Comment by tsujan** [comment]
> I noticed that drag&drop in split view (F6) in pcmanfm-qt crashes it while copy&past works.

I use it on a regular basis -- DND is the only reason I press `F6` -- and have encountered no problem.

You need to be more specific. Lack of re-compilation after upgrading libfm-qt or Qt?

**Comment by stefonarch** [comment]
>  Lack of re-compilation after upgrading libfm-qt or Qt?

infact, guess it was that, didn't recompile after qt5 went form 5.13.2-1 -> 5.14.0-1 2 weeks ago, but it's the first time I encountered a misbehaviour.

**Comment by tsujan** [comment]
It'll take a day or 2 until Qt 5.14 comes here. An Arch user reported a false bug against Kvantum with it. I just hope the bugs aren't in Qt 5.14 itself, having seen enough bugs in 5.13.

**Comment by tsujan** [comment]
Oh, I forgot to ask: Is the lack of text DND between Qt apps still present in Qt 5.14?

**Comment by stefonarch** [comment]
The issue here is still unchanged, dragging text doesn't appear i qterminal, dragging files it shows the path and filename. Dragging a picture from falkon to the desktop it asks only  "move here?" (  should ask only "copy here?) and works. Some of them I didn't test before, I hardly use dnd.

**Comment by tsujan** [comment]
Qt 5.14 came here right now :) I'll upgrade, recompile, reboot and tell you.

**Comment by tsujan** [comment]
Split view DND works well in pcmanfm-qt; no crash.

But, to put it VERY politely, Qt 5.14.0 is a piece of crap. I encountered serious bugs here and there. Code reviews have become so poor at Qt! Where are those days that Qt kept its quality?!

**Comment by tsujan** [comment]
Strangely enough, DND from Qt apps to QTerminal works well under Wayland -- I tested with Weston and Wayfire -- and that's good news because pasting by middle clicking doesn't work with Wayland.

**Comment by stefonarch** [comment]
This is obsolete/solved by https://github.com/lxqt/qterminal/commit/8c10c6ba8da8294c565a2be886da21205e693b1c I think.

**Comment by tsujan** [comment]
@stefonarch
Your report is still valid. DND doesn't follow the settings "Confirm multiline paste" and "Trim trailing newlines in pasted text".

**Comment by tsujan** [comment]
Probably, related to https://github.com/lxqt/qterminal/issues/970
