### ISSUE TITLE
JetBrains Mono font unavailable for setting

### ISSUE THREAD

**Issue by RistiCore** [lxqt/qterminal#656]
I'd installed [JetBrains Mono](https://www.jetbrains.com/lp/mono/) font to system and want to use it as default terminal font. 

##### Current Behavior
I cannot find JetBrains Mono in font list.

##### Possible Solution
Add correct detection of JetBrains Mono font for terminal purpose.

##### Steps to Reproduce (for bugs)
1. Install JetBrains Mono from official site
2. Open qterminal File » Preferences » Appearance 
3. Click Change button in Font section
4. In Font selection list try to find JetBrains Mono

##### System Information
* Distribution & Version: openSUSE Tumbleweed
* Kernel: 5.4.10
* Qt Version: 0.14.1

**Comment by tsujan** [comment]
JetBrains Mono doesn't introduce itself as a fixed-pitch font -- not to Qt at least. This isn't a QTerminal issue.
