### ISSUE TITLE
Support for Italic, Dim, Hidden, and Strikethrough

### ISSUE THREAD

**Issue by Joedang** [lxqt/qterminal#661]
This is a feature request. It would be nice to have support for the `\e[3m` "italic" console code. 

Similarly, support for "dim", "hidden", and "strikethrough" would be cool. (Personally, I care a lot less about them. :P)

Sorry if this is a duplicate, or if there's some way to do this already. I didn't see any mention of "italic" in the issues, PRs, or source. 

## Examples
Here's a display of some of the "attribute" console codes, using the Ubuntu Mono font. 

### qterminal
![Screenshot_2020-02-17_16-58-53](https://user-images.githubusercontent.com/16861664/74694897-d220b000-51a6-11ea-8c28-5229648b5504.png)

### Sakura
![Screenshot_2020-02-17_16-58-14](https://user-images.githubusercontent.com/16861664/74694898-d2b94680-51a6-11ea-9c1d-952fd56cc1e2.png)

**Comment by yan12125** [comment]
Italic texts works with DejaVu Sans Mono

![image](https://user-images.githubusercontent.com/1937689/74699036-93d4d080-523a-11ea-8ecd-44a03c73abf4.png)

Support was added some time ago (https://github.com/lxqt/qtermwidget/commit/d84849b04b4ed860a82e5833faf0b1102a1834c3). You may want to check whether Ubuntu Mono works with Qt and your qterminal/qtermwidget is new enough or not.

**Comment by tsujan** [comment]
> Italic texts works with DejaVu Sans Mono

@yan12125  I just wanted to tell that (DejaVu Sans is my default font) but you were faster :) Yes, it works.

**Comment by tsujan** [comment]
QTerminal and Ubuntu Mono::

![ubuntu_mono](https://user-images.githubusercontent.com/981076/74738711-c7305300-526c-11ea-9fbc-e81b87ff52bd.png)
