### ISSUE TITLE
Qterminal on Kali

### ISSUE THREAD

**Issue by kerolloz** [lxqt/qterminal#668]
How can I get the same look of qterminal on Kali on my Ubuntu?
![image](https://user-images.githubusercontent.com/36763164/79398981-5fec0200-7f82-11ea-9567-d9b04e97f2fa.png)
![image](https://user-images.githubusercontent.com/36763164/79399195-00dabd00-7f83-11ea-96b5-24bd2ad00f96.png)
I mean the dark theme of the tab bar, menu bar and scrollbar

**Comment by tsujan** [comment]
Here is the bug tracker. The place for questions is LXQt forum but, unfortunately, the forum is down for now.

Use a dark Qt style — for example, Breeze with a dark color scheme (you need KDE System Settings to choose Breeze's color scheme), or a dark Kvantum theme, or a QtCurve theme with dark background colors,...

**Comment by kerolloz** [comment]
@tsujan

Thank you for the help. That [video](https://www.youtube.com/watch?v=rP4DWu24ff0) helped.
![image](https://user-images.githubusercontent.com/36763164/79402902-8ebba580-7f8d-11ea-9b43-870d40f85c8f.png)

I don't know why it's very slow on startup. it takes too long.

**Comment by kerolloz** [comment]
fixed the slow start after installing _qt5ct_

in `/etc/enviorment` added `QT_QPA_PLATFORMTHEME=qt5ct`

**Comment by tsujan** [comment]
> That video helped.

The video is about Qt's gtk2 plugin. Yes, it's another choice -- not the best but good enough.

> I don't know why it's very slow on startup. it takes too long.

If you mean QTerminal, it should start almost instantly.

> fixed the slow start after installing qt5ct

If you don't use LXQt, it's OK; otherwise, you shouldn't need `qt5ct`.
