### ISSUE TITLE
True single window mode

### ISSUE THREAD

**Issue by robschi** [lxqt/qterminal#671]
Is it possible to add this lxqt/pcmanfm-qt#1094 also for the QTerminal?

So if for example I press F4 in the PCManFM-Qt, the the location opens as a new tab in an existing QTerminal rather than in a new window?

**Comment by tsujan** [comment]
The short answer is "no".

QTerminal and pcmanfm-qt have totally different code structures. Most importantly, pcmanfm-qt is a single-process app, while each QTerminal window has its own process.

Theoretically speaking, I don't think it's wise to make QTerminal a single-process app. For now, I have no reason other than that I don't know of a single-process terminal emulator.

Practically speaking, even if a developer has lots of extra time for coding and debugging, the final result won't be worth the effort, IMHO.

However, there may be a simple way other than making a single-process app — although I have no idea.

**Comment by redtide** [comment]
I also would like this feature. Not sure if this could make sense/feasible:
- Add a "When using QTerminal, open in a new tab" setting in PCManFm
- Eventually a QTerminal "Accept DBus new tab requests" setting
- In such case first time is run give QTerminal an ID to use via DBus together with the folder path
- The given QTerminal instance with such ID will accept the message and open a new tab

**Comment by yan12125** [comment]
Adding a new tab via DBus is already possible. For example:
```
gdbus call --session --dest org.lxqt.QTerminal-613269 --object-path /windows/d45ba8c729c24ec98e2382d68b18ad92 --method org.lxqt.QTerminal.Window.newTab "{'workingDirectory': <'/some/path'>}"
```
However, the interface name and the object path is not fixed. Clients (ex: pcmanfm-qt) will need to iterate over available interface names and object paths.

The requested feature is possiblie without the single-instance model. For the latter, please follow https://github.com/lxqt/qterminal/issues/644.

**Comment by redtide** [comment]
> However, the interface name and the object path is not fixed. Clients (ex: pcmanfm-qt) will need to iterate over available interface names and object paths.

So what a user should do to make that iteration, via shell script? Is F4 key configurable in PCManFM or need to move this request to that (and eventually other) project?
