### ISSUE TITLE
Shortcut key combination to cancel a command in execution

### ISSUE THREAD

**Issue by avariado** [lxqt/qterminal#675]
Does qterminal have a shortcut key combination to cancel a command in execution, such as Crtl+C (which does work with some terminals but not with this one)? I can't find one... Thanks.
Lubuntu 20.04 LTS (Focal Fossa)
Qterminal 5.12.8

**Comment by tsujan** [comment]
`Ctrl+C` is a common command that works with QTerminal too.

**Comment by tsujan** [comment]
> Qterminal 5.12.8

QTerminal has no version 5.12.8.

**Comment by avariado** [comment]
Hello, tsujan, and thank you very much for your help!
My fault, I meant QTerminal 0.14.1 using QT version 5.12.8.
Here's my problem, I made a bash script like this in order to monitor the CPU temperature:

#!/bin/bash
for i in {1..10}; do sensors; date ; sleep 5; done

And I'm unable to cancel that command with Ctrl+C, it returns ^C.
But you're right, I just realized that if I type that in the console directly, then Ctrl+C works.
Do you know if it's possible to use other key combination to stop the bash script?

**Comment by tsujan** [comment]
> And I'm unable to cancel that command with Ctrl+C, it returns ^C

Which means the process is interrupted, as expected. Use a process manager (like Qps) to verify that.

There's no difference between QTerminal and, for example, XTerm in this regard.

**Comment by avariado** [comment]
Gotcha, thanks again for your quick answer, tsujan!
