### ISSUE TITLE
Preferences not saving

### ISSUE THREAD

**Issue by led5150** [lxqt/qterminal#681]
##### Expected Behavior

Preferences save and are reflected in terminal upon closing preferences window

##### Current Behavior

They don't save or take effect

##### Steps to Reproduce (for bugs)

1. open preferences from file
2. change a preference
3. exit
4. 

##### System Information

* Distribution & Version: 
* Kernel: Kali Linux 
* Qt Version: 5.12.5
* qtermwidget Version: 
* lxqt-build-tools Version: 
* Package version:

**Comment by tsujan** [comment]
Terrible report. Closing.
