### ISSUE TITLE
Shortcut keys to resize split terminals

### ISSUE THREAD

**Issue by amaush** [lxqt/qterminal#686]
I would like to suggest an addition to the shortcut options currently available. While writing code and testing, I typically open up a split terminal and when the occasional test fails,  i.e. in Terminator, I just quickly enter <Ctrl+Shift+Up> for example to expand the bottom terminal, peek at failed test and then <Ctrl+Shift+Down> to minimise the bottom terminal to whatever size I want. Currently I have not found any method of doing that in qterminal.  This would potentially work with both vertical and horizontal splits.

**Comment by manid2** [comment]
Hi, is there any work in progress on this feature? as this is highly useful would like to see this in qterminal.

**Comment by ahmadraniri1994** [comment]
You can mix qterminal with vim, vim has shortcut to resize split window. Just a bit of advice.
