### ISSUE TITLE
qterminal doesn't show powerline / nerd font  symboles

### ISSUE THREAD

**Issue by j4n3b** [lxqt/qterminal#689]
Hello
I am using `qterminal 0.14.1` and I first noticed the problem while using [colorls](https://github.com/athityakumar/colorls).

qterminal doesn't show any simple at all. other terminals show them and if there is any problem they show wired symbols and rectangular shape instead. qterminal shows none.

normaly it should show this:
https://user-images.githubusercontent.com/17109060/32149078-899b0622-bd25-11e7-9810-d398eaa77e32.png

here is my locale:

```
LANG="en_US.UTF-8"
LC_CTYPE="en_US.UTF-8"                                                                    
LC_COLLATE="en_US.UTF-8"                                                                  
LC_TIME="en_US.UTF-8"                                                                     
LC_NUMERIC="en_US.UTF-8"                                                                  
LC_MONETARY="en_US.UTF-8"                                                                 
LC_MESSAGES="en_US.UTF-8"                                                                 
LC_ALL="en_US.UTF-8" 
```

**Comment by yan12125** [comment]
Maybe something else is not correctly configured? After installing nerd-fonts-dejavu-sans-mono from [1] and asking qterminal to use it, colorls seems to work fine.

![image](https://user-images.githubusercontent.com/1937689/84154936-4d7dd880-aa9a-11ea-9cb1-b7c224b2ebe2.png)

[1] https://github.com/archlinuxcn/repo/tree/master/archlinuxcn/nerd-fonts

**Comment by luis-pereira** [comment]
I'm not using powerline, didn't  change my font to nerd and it works:

![screen](https://user-images.githubusercontent.com/62877/84159434-f8739f80-aa64-11ea-8a9d-a0a32eb3f5d3.jpg)

@j4n3b 0.14 is old.

**Comment by tsujan** [comment]
This can be closed. The issue is reported against an outdated version of QTerminal and 2 LXQt devs can't reproduce it.

**Comment by yan12125** [comment]
@luis-pereira Thanks for testing!

@j4n3b Feel free to leave comments if you find the cause and it's related to qterminal.

**Comment by uBadRequest** [comment]
Sorry to bring back this issue back from the dead but i figured i'd add this here as symbols in the PS1 aren't showing up for me in all but 1 font that i've tried.

![image](https://user-images.githubusercontent.com/47282747/113936105-debafa00-97e6-11eb-89a1-0222cecdfd88.png)
![image](https://user-images.githubusercontent.com/47282747/113936221-03af6d00-97e7-11eb-9fb9-23b00c749f5d.png)

I can change it to this ugly looking font and all of a sudden it works!
![image](https://user-images.githubusercontent.com/47282747/113936430-45d8ae80-97e7-11eb-857f-84ecf148a85d.png)

Started to think maybe it was something in my zsh config or something with starship but as you can see it works just fine in other terminals?  Could it be configuration issue or a spacing issue?
![image](https://user-images.githubusercontent.com/47282747/113938770-943b7c80-97ea-11eb-825d-6948b77b9415.png)
