### ISSUE TITLE
Building from (github) source produces binary with wrong version number

### ISSUE THREAD

**Issue by uffejakobsen** [lxqt/qterminal#693]
Building from (github) source produces binary with wrong version number

Building source from github master branch produces qterminal binary that identifies itself as 0.9.0 - where the expected version was 0.15.0

**Comment by tsujan** [comment]
`cmake` should be used to compile it, not `qmake`.

@yan12125 
Any reason for keeping the `pro` file? I hadn't noticed it before.

**Comment by yan12125** [comment]
> Any reason for keeping the pro file?

I don't think so. The pro file is added for "easier to use in creator than cmake" (6cae5c98fa3fecf3e3a0ff2eecc38158f2b1a0dc). But none of current developers use Qt Creator I guess.

**Comment by tsujan** [comment]
> But none of current developers use Qt Creator I guess.

I think so too. Personally, I hate it ;)

**Comment by tsujan** [comment]
BTW, I read somewhere that Qt itself will drop qmake in Qt6; didn't investigate the reliability the source though.

**Comment by yan12125** [comment]
> We will continue to support our users on QMake, but not develop it further or use it to build the Qt framework itself.

(https://www.qt.io/blog/2019/08/07/technical-vision-qt-6)

**Comment by jubalh** [comment]
> But none of current developers use Qt Creator I guess.

Just curious. What do you use?

**Comment by yan12125** [comment]
Just vim LOL

**Comment by tsujan** [comment]
@yan12125 
Thanks for the link!

@jubalh
I use QTerminal + FeatherPad + any browser to consult Qt doc. Light and comfortable :)

**Comment by yan12125** [comment]
Yes, Qt  online docs are awesome!

**Comment by luis-pereira** [comment]
> Just curious. What do you use?

qterminal + vim/neovim + assistant/brower for docs

**Comment by jubalh** [comment]
Nice!
