### ISSUE TITLE
master branch does not seem to compile anymore

### ISSUE THREAD

**Issue by uffejakobsen** [lxqt/qterminal#696]
Hi,
I'm wondering if I missed something here - but

After the recent commit 73fa1a on master - master does not seem to compile anymore
```


/tmp/qterminal/qterminal-devel/qterminal-devel.git/src/termwidget.cpp: In member function ‘void TermWidgetImpl::propertiesChanged()’:
/tmp/qterminal/qterminal-devel/qterminal-devel.git/src/termwidget.cpp:104:5: error: ‘setBoldIntense’ was not declared in this scope
  104 |     setBoldIntense(Properties::Instance()->boldIntense);
      |     ^~~~~~~~~~~~~~

```

**Comment by tsujan** [comment]
Every time you want to compile the latest git QTerminal, you should first compile and install the latest git QTermWidget. See https://github.com/lxqt/qtermwidget/commit/8eac739cbc4c6461efee7a8a347b9c8f5e75340b

**Comment by uffejakobsen** [comment]
Argh - actually I did - except for the fact that my origin was pointing to my own fork of qterwidget - and that needed a rebase against upstream/master...

sorry for the noise :-)
