### ISSUE TITLE
Functions keys not sent to application (specifically `htop`) running in qterminal version 0.14.1

### ISSUE THREAD

**Issue by MiBengtsson** [lxqt/qterminal#697]
##### Expected Behavior
In Qterminal, start `htop`. Hit one of the following keys:
* F6 for "SortBy",expecting to be able to sort by a specified column.
* F5 for "Tree", expecting to view processes in a tree view
* F4 for "Filter", expecting to be able to type in a filter string, 
* F3 for "Search", expecting to perform a search
* F2 for "Setup", expecting to reach htop's configuration screen.

##### Current Behavior
* Hitting F6 works as intended (as does F9 and F10, but these are the only three, out of the ten function keys that htop recognizes, that do work)
* Hitting F5 has no effect at all
* Hitting F4 has no effect at all
* Hitting F3 has the same effect as if I had hit F2, while using a different terminal program (i.e. I get "setup" instead of "Search")
* Hitting F2 has no effect at all

I do not believe the problem lies in `htop`, because I can successfully run `htop` in other terminal programs on the same machine in which the function keys are propagated properly to `htop`.

##### Steps to Reproduce (for bugs)

1. 
2. 
3. 
4. 

##### Context
I tend to have htop running in a terminal window at all times. In qterminal 0.7.x this worked well. After updating to qterminal 0.14.1, I can no longer interact with `htop`, and makes me use a different terminal for `htop`.

I have went through the preferences to find any shortcut that might be hijacking the function key presses, but can only find F11 and F12, which were irrelevant for htop.

##### System Information

* Distribution & Version: Fedora 31
* Kernel: 5.6.19-200.fc31.x86_64
* Qt Version:  5.13.2
* qtermwidget Version: qtermwidget-0.14.1-2.fc31.x86_64
* lxqt-build-tools Version: lxqt-build-tools-0.6.0-2.fc31.noarch
* Package version: N/A

**Comment by tsujan** [comment]
None is reproducible. Here, all function keys work file with htop in Qterminal.

V0.14.1 is outdated.

**Comment by yan12125** [comment]
Most likely the same issue as described in https://github.com/lxqt/qterminal/issues/38#issuecomment-459998026. The "linux" emulation type is not recommended. Removal of the misleading text (https://github.com/lxqt/qterminal/pull/682) does not catch up 0.15, though.

If you still get issues with the "default" emulation type, feel free to leave more comments.

**Comment by MiBengtsson** [comment]
That was indeed the problem. Thanks!
