### ISSUE TITLE
[Feature Request] Support for (minimal) .css (CSS) Files, similar to KDE konsole

### ISSUE THREAD

**Issue by rubyFeedback** [lxqt/qterminal#701]
Heya,

I will skip most of the template, since this is a feature request really. :-)

I compiled all of lxqt from source; works fine!

qterminal also works fine, no crashes, lots of options to configure.

There is one thing I am missing or perhaps I have not looked closely
enough. If so please just close this.

KDE konsole has support for .css files. You can enable this in some
preferences setting, where it asks you to provide the path to the 
.css file.

I autogenerate the following .css file via ruby:

    QTabBar::tab {

      font-size: 12px;

      /* Minimum width for every tab */
      min-width: 62px;

    }

    QTabBar::tab:selected {

      background: skyblue;

      color: black;

    }

The most important part for me is the "selected" -> skyblue background.

This is a visual helper for me to see which tab I am working on right now.

I believe this is done by Qt so perhaps it is not difficult to add it to qterminal
(my C++ is really bad; I am more a ruby hacker). 

Note: I am NOT asking for all of CSS support. Just the colour-related part
for background and/or border (it would be ok for coloured borders too,
although I prefer light blue as a background for the fastest visual indiciator).

Thanks for reading - feel free to close this at any moment in time.

**Comment by tsujan** [comment]
LXQt panel supports two kinds of styles: `QStyle` and stylesheet. The second one can be controlled by CSS. What you want is a stylesheet support for QTerminal. Whether its implementation would be worth the effort or who would have time to do it, I don't know.

**Comment by yan12125** [comment]
It has been supported for some time (https://github.com/lxqt/qterminal/pull/308). Here is an example - create a file `~/.config/qterminal.org/style.qss` with the following content (adjust the path if you use a custom `$XDG_CONFIG_HOME`)

```
QMenuBar { background-color: red; }
```

And restart qterminal to see what changes :)
