### ISSUE TITLE
Can't change the font if the previous font is misspelled or not installed

### ISSUE THREAD

**Issue by daniruiz** [lxqt/qterminal#708]
If the fontFamily set inside the config file is missing or misspelled you can't change the font until you manually remove/fix that value. The dialog works properly and lets you modify the font, but after clicking OK the font is still unmodified, showing the old value. Trying to debug it I've looked at the logs it throws but the messages it shows when the issue happens and when the terminal is using the correct font are the same.

##### Expected Behavior
The font should be changeable even if the previously configured one is wrong.

##### Current Behavior
The font selector dialog works properly and lets you select another font. But once you click OK nothing happens, the font configured for the terminal remains the same.

##### Steps to Reproduce (for bugs)
![Peek 21-09-2020 14-17](https://user-images.githubusercontent.com/12565871/93766042-1cbf4a80-fc16-11ea-95b5-37d92ce92286.gif)

##### Context
The issue occurred after an update of the Qt5 libraries, not qterminal per se, but I haven't found this issue on any other qt app. It was originally spotted using qterminal 0.14, but the issue remains with qterminal 0.15 (built from source using qtermwidget 0.15.0 lxqt-build-tools 0.7.0 and qterminal 0.15.0)

Not being able to change the font can affect especially to people who want to modify the font-size.

##### System Information
* Distribution & Version: Kali Linux (rolling release based on Debian testing)
* Kernel: Linux kali 5.7.0-kali3-amd64
* Qt Version: 5.14.2-3
* qtermwidget Version: 0.15.0
* lxqt-build-tools Version: 0.7.0
* Package version: 0.15.0

**Comment by tsujan** [comment]
Not reproducible with the latest version.
