### ISSUE TITLE
Window position and size with 2 monitors

### ISSUE THREAD

**Issue by ioO** [lxqt/qterminal#715]
#### Given
A laptop with LVDS monitor of 1366x768 resolution. It is set as primary monitor.
A VGA monitor plugged in of 1280x1024 resolution. It is set as extend another monitor.
LXQT with openbox.
Qterminal size preferences, set as 90% for width and 45% for height

##### Expected Behavior
I just install QTerminal to remove Yakuake, and I used to get this behavior, the window is displayed on monitor where my mouse is, with the window size I define in app.

##### Current Behavior
By default, when I press QTerminal <F12>, it displays only on primary monitor even if my mouse is on second monitor. Window size is ok.

Then I add in my openbox config file those lines
```xml
<application name="qterminal">
    <position force="yes">
      <monitor>Mouse</monitor>
      <x>center</x>
      <y>0</y>
      <size>
        <width>default</width>
        <height>default</height>
      </size>
    </position>
  </application>
```
With this config, Qterminal window is displayed in monitor where my mouse is. But the size depends in which monitor Qterminal was opened previously. As a result, if Qterminal is open on primary monitor (LVDS) and I move to extend monitor (VGA), I got a width of 90% of 1366 instead of 1280 and an height of 45% of 768 instead of 1024.  And if I move my mouse back to primary monitor, I got size based on extend monitor.
One solution is to keep my mouse on monitor and to press <F12> twice, to make the window down and drop, I finally get the good size. My size is in percent, so I was hoping the window sized well the first time.

I had to set __force=yes__ which is described in openbox documentation as a "__this is to override buggy applications who refuse to behave__". I firstly use __no__ and this had no effect on behavior.

##### Possible Solution
Sorry :cry: 

##### System Information

* Distribution & Version: Archlinux (updated 2020-10-18)
* Kernel: Linux 5.9.1-arch1-1
* Qt Version: 5.15.1
* qtermwidget Version: 0.15.0-1
* lxqt-build-tools Version: 0.7.0-1
* Package version: 0.15.0-1

**Comment by tsujan** [comment]
If you mean the drop-down mode, I think it's easy to open the window on the screen with the mouse pointer and resize it accordingly. Should read the code to remember that part...

**Comment by ioO** [comment]
Sorry, I mean drop-down mode. And I also set an auto launch in lxqt session preferences this way `/usr/bin/qterminal --drop`

For sure your solution is easy, but not when you drop-down all day long :wink: 
I start reading openbox documentation for this case (as I am lazy, I use lxqt for a while and I didn't have a look at openbox since) and I did some research. It looks like this behavior has to be managed by the window manager and not the window. Tell me if I am wrong as I am a newbie on this topic.

**Comment by tsujan** [comment]
The fix is here: https://github.com/lxqt/qterminal/pull/716. It passed my tests,

> I start reading openbox documentation for this case

Forget about openbox; the problem was in QTerminal: its drop-down instance should have been opened on the screen with the mouse cursor. The above patch does that.

**Comment by tsujan** [comment]
> It looks like this behavior has to be managed by the window manager and not the window. Tell me if I am wrong as I am a newbie on this topic.

On Wayland, the app has no control over its window position. But on X11, the app can determine where it appears. The drop-down mode is for X11, as far as I know.

**Comment by ioO** [comment]
Thank you  @tsujan. I took the opportunity to learn a little bit more about X11 and Wayland, I got a headache :laughing: 
My session use X11 ( `echo $XDG_SESSION_TYPE` )

> Forget about openbox; the problem was in QTerminal: its drop-down instance should have been opened on the screen with the mouse cursor. The above patch does that.

I am not a Qt developer, but when I read your code line [725](https://github.com/lxqt/qterminal/pull/716/commits/87318b6f58b71875aa1dc5054080ef90888b73d9#diff-c72b037f3ac7abbd3d0ee519b6f456013a9bbf5a59df16308939320c04970447R725) I understand you open Qterminal in screen where the cursor is. For example, if someone with 2 monitors wants to open only in primary monitor, will it be possible ? What I have understood at this time, it is the responsibility of openbox and not the application. But I agree, I have a lack of knowledge :wink:

**Comment by tsujan** [comment]
> when I read your code line 725 I understand you open Qterminal in screen where the cursor is.

That's how Qt will position windows/dialogs if their positions aren't forced by the code and it's the most natural positioning: on the screen that contains the mouse pointer. It's especially appropriate with a drop-down terminal.

> if someone with 2 monitors wants to open only in primary monitor

Then the WM should force it if it can.

**Comment by ioO** [comment]
Thank you @tsujan for your time. My knowledge grows step by step :smile:
