### ISSUE TITLE
Allow right click for shortcut

### ISSUE THREAD

**Issue by matkoniecz** [lxqt/qterminal#721]
##### Expected Behavior
right click can be set as shortcut, for example for pasting

##### Current Behavior

File | Preferences | Shortcuts allows to set shortcuts (what allows to restore sane default for ctrl+v for pasting - BTW, why it is not default?).

But I see no way at all to set right-click as a shortcut.

##### Possible Solution

No idea, sorry :(

##### Context

Recently I am testing Windows again, and one of very nice things that appeared since I was using it last time is Powershell. Some features worth copying from it include right click inserting into CLI (and rightclick copying what is selected but that may be harder to copy).

It is quite intuitive and very useful, at least in my case where I am either invoking my prepared scripts/programs or copy pasting stuff.

##### System Information

* Distribution & Version: Lubuntu 20.04.1 LTS
* Kernel: how can I check this?
* Qt Version:  how can I check this?
* qtermwidget Version:  how can I check this?
* lxqt-build-tools Version: how can I check this?
* Package version: QTerminal 0.14.1
 - bpytop version: `bpytop -v` `bpytop version: 1.0.42`
 - psutil version: `bpytop -v` (version 5.7.0 or above is required) `psutil version: 5.7.2`
 - Terminal used: QTerminal 0.14.1
 - Font used: Ubuntu Mono 14 pt (default for this terminal)
 - Python version, `python3 --version` (version 3.6 or above is required): Python 3.8.5

**Comment by tsujan** [comment]
First, shortcut is always a key (in Qt) and right-click is not. Second, right-click is for showing the context menu.

> Some features worth copying from it include right click inserting into CLI

It seems you're not familiar with Linux. In Linux, you copy by selecting and paste by middle-clicking. That's called "selection clipboard".

**Comment by matkoniecz** [comment]
> shortcut is always a key (in Qt)

:( I was worried that it is caused by Qt shortcomings.

> Second, right-click is for showing the context menu.

As it is not really needed I planned to remap it to some obscure key, like middle click or something.

> you copy by selecting and paste by middle-clicking. That's called "selection clipboard".

Thanks for the tip! It is less useful (as middle button is harder to use than right one), but I was unaware of this.
