### ISSUE TITLE
Shortcuts are always in English in Preferences dialog

### ISSUE THREAD

**Issue by tsujan** [lxqt/qterminal#731]
##### Steps to Reproduce (for bugs)

1. Open QTerminal with `LANGUAGE=fr qterminal`.
2. Show the Preferences dialog.
3. Go to "Raccourcis".

Then the first column is in English, while it should be in French.

##### Possible Solution

The first column should be populated by translated strings. Using `tr()` inside `PropertiesDialog::setupShortcuts()` doesn't do anything other than returning a `QString` — `tr()` should have a literal string as its argument and it can't have it inside that function.

##### System Information

* Latest git LXQt

**Comment by tsujan** [comment]
@stefonarch, could you confirm this issue with your native language? I only recently installed QTerminal translations.

**Comment by stefonarch** [comment]
Always english this column, opening with  `LANGUAGE=it qterminal
` or from runner.

**Comment by tsujan** [comment]
@stefonarch, thanks!

Not only the action names but also the shortcut strings are in English (`Shift` should be `Maj` in French, for example). Something is very wrong in the code.

In comparison, lximage-qt doesn't have this problem.

**Comment by tsujan** [comment]
Came back to this and found the problems:

 1. The app doesn't install Qt translations.
 2. The app doesn't use translated strings in the shortcut editor.

Both issues can be fixed easily. I'll make a PR.

On a side note, the core shortcut code is weird: adding strings to `config.h`, using a method like `MainWindow::setup_Action()`, etc., are all weird and unnecessary. I guess they were written when Qt didn't translate shortcuts (Qt3?!). IMHO, after fixing issues like this one, we should modernize the core code.
