### ISSUE TITLE
how can I update QTerminal in Kali Linux?

### ISSUE THREAD

**Issue by xyxexy** [lxqt/qterminal#738]
Now i have 0.14.1 version,but i need the latest version of QTerminal,i've tried sudo apt-get autoremove qterminal and after sudo apt-get install qterminal,but still it's installed 0.14.1 version,i've tried to sudo apt-get dist-upgrade the system,but still doesn't work,if i want to sudo apt-get install qterminal it's saying "The latest version of qterminal (0.14.1-1+b1) is already installed." so idk how may i update QTerminal
* Distribution & Version: Kali Linux the latest version
* Kernel: Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux
* Qt Version: 5.15.1
* qtermwidget Version: -
* lxqt-build-tools Version: 0.6.0-2
* Package version: 0.14.1

**Comment by tsujan** [comment]
Downstream questions should be asked downstream.

**Comment by grese** [comment]
I filed an[ upgrade request](https://bugs.kali.org/view.php?id=6831) in [Kali's bug tracker](https://bugs.kali.org), and they took care of it. They currently have 0.16.1-1 in kali-rolling. Just update with `sudo apt update; sudo apt install qterminal;`

**Comment by yan12125** [comment]
> I filed an upgrade request in Kali's bug tracker, and they took care of it.

Thanks and glad to see that developers of Kali Linux is taking it seriously!

Another good news: LXQt packages in Debian are updated to 0.16.x, too: https://qa.debian.org/developer.php?login=pkg-lxqt-devel%40lists.alioth.debian.org

**Comment by stefonarch** [comment]
That's real good news, seeing debian at 0.14.1 was a pain...
