### ISSUE TITLE
ask for confirmation when closing (feature request?) 

### ISSUE THREAD

**Issue by michaelhmich** [lxqt/qterminal#746]
when "ask for confirmation when closing" is enabled QT clears the terminal (stays white) and then pops up the confirmation pop up ... I thing this way it does not make much sense, the context should stay there until confirming closing, worse it does not confirm tab sessions 

but I use it anyway because it blocks the wall msgs, thanks

###
System:
  Host: hm-mint Kernel: 5.9.9-hmich-tl-1.99 x86_64 bits: 64 Desktop: KDE Plasma 5.18.5 
  Distro: Linux Mint 20 Ulyana 
Graphics:
  Device-1: NVIDIA GK208 [GeForce GT 710] driver: nouveau v: kernel 
  Display: x11 server: X.Org 1.20.8 driver: modesetting unloaded: fbdev,vesa tty: N/A 
  OpenGL: renderer: NVD9 v: 4.3 Mesa 20.0.8

**Comment by tsujan** [comment]
Fixed in https://github.com/lxqt/qterminal/commit/8b1385e4299ca259c5759b6641cd435e0ee93f1a

As explained there, the behavior in question was not only self-inconsistent but also dangerous.
