### ISSUE TITLE
[feature request] Make use of pos1/end keys.

### ISSUE THREAD

**Issue by V10lator** [lxqt/qterminal#77]
A feature I'm missing is to use pos1 to set the cursor to the beginning of the text and end to set the cursor to the end of it. If you need an example for that check xfce4-terminal.

**Comment by yan12125** [comment]
Home and End keys work fine in the latest version. If it doesn't work for you, hit Ctrl+V and then Home/End to see what the shell gets and configure your shell accordingly.
