### ISSUE TITLE
How to open new a tab or a window with $PWD maintained?

### ISSUE THREAD

**Issue by ssxcxS45XT** [lxqt/qterminal#782]
##### Expected Behavior
I want the pwd be maintained.

##### Current Behavior
When I create a new tab or window, the pwd will not be maintained.

##### Possible Solution

I don't know.

##### System Information
* Distribution & Version: $ cat /etc/issue
Kali GNU/Linux Rolling \n \l
* Kernel: $ uname -a
Linux kali 5.9.0-kali1-amd64 #1 SMP Debian 5.9.1-1kali2 (2020-10-29) x86_64 GNU/Linux
* Qt Version: $ qterminal --version
0.14.1
* qtermwidget Version: Not sure how to check.
* lxqt-build-tools Version: Not sure how to check.
* Package version: Not sure how to check.

**Comment by stefonarch** [comment]
No new shell will maintain ever any sudo/root passwd afaik

**Comment by ssxcxS45XT** [comment]
I am not talking about the password. I am not talking about the current working directory.

https://en.wikipedia.org/wiki/Pwd

**Comment by tsujan** [comment]
> I am not talking about the current working directory.

Which is kept when a new tab is opened. Your problem may be caused by the old version you use.

@yan12125?

**Comment by ssxcxS45XT** [comment]
I use this version. Is it too outdated?

```
$ qterminal --version
0.14.1
```

When I open a new tab, it only maintains the directory when qterminal was original launched. But I need to the directory of the new tab to be the same the tab that was focused on, not the directory when qterminal was first launched.

**Comment by stefonarch** [comment]
Sorry for the missunderstanding.
You mean this option?

![schermata-18-12-09](https://user-images.githubusercontent.com/10681413/103560748-9541d280-4eb8-11eb-9f29-b2900c48432e.png)

**Comment by tsujan** [comment]
> I use this version. Is it too outdated?

Yes, it's obsolete.

**Comment by ssxcxS45XT** [comment]
> You mean this option?

Yes.

> Yes, it's obsolete.

Is this version good enough to use the option that you showed? (I don't see where I can find the option.)

$ qterminal  --version
0.16.1

**Comment by tsujan** [comment]
Yes, 0.16.1 is the latest release.

> I don't see where I can find the option.

I'm not sure that your problem is that option. Let's wait for @yan12125; he might shed more light on it.

**Comment by yan12125** [comment]
> I don't see where I can find the option

That option is in Preferences -> Behavior. And yes, if that option is not enabled, working directory is not preserved.

**Comment by ssxcxS45XT** [comment]
> That option is in Preferences -> Behavior. And yes, if that option is not enabled, working directory is not preserved.

It looks like this should be enabled by default.

"Open new tab to the right of the active tab" should also be enabled by default.

Could you make them default in future versions of qterminal?

**Comment by yan12125** [comment]
> It looks like this should be enabled by default.

Agreed. Let's keep this issue open until that is enabled by default.

> "Open new tab to the right of the active tab" should also be enabled by default.

Either on or off for that option makes sense and there is no need to change the default IMO.

**Comment by stefonarch** [comment]
> Agreed. Let's keep this issue open until that is enabled by default.

Not so sure if default is a good idea. Most users expect open new instances  in ~

**Comment by stefonarch** [comment]
We could decide something here, I didn't change my mind.

**Comment by tsujan** [comment]
> Most users expect open new instances in ~

A new instance, yes — they can simply launch a new instance — but a new tab/window from the current terminal should be opened in the current directory (it isn't a new instance because it shares the same process). Again, since the user can always launch a new instance, I think the option in question is redundant.

**Comment by stefonarch** [comment]
This could be closed IMO.

**Comment by tsujan** [comment]
Yes. Thanks.

Recently I started to clean up the issue tracker to make it really usable.
