### ISSUE TITLE
How to show the current working directory in the table title?

### ISSUE THREAD

**Issue by ssxcxS45XT** [lxqt/qterminal#783]
The title is shown as something like "Shell No. 3".

It is better to show the current working directory in the title instead. Is there a way to configure so? Thanks.

**Comment by stefonarch** [comment]
Please don't open issue for asking things like that, which answers themselves (yes) looking at the preferences in 0.16.1

**Comment by ito32bit** [comment]
> The title is shown as something like "Shell No. 3".

What is your PS1?
https://wiki.archlinux.org/index.php/Bash/Prompt_customization#Customizing_the_terminal_window_title
example: `PS1='\[\e]2;\w\a\]\w \$ '`
![Qterminal_PS1_screen-2021-01-07_11-44-41](https://user-images.githubusercontent.com/52656419/103844922-58572500-50de-11eb-94c5-1c3994e2378e.jpg)

LXQt has "Discussions": https://github.com/lxqt/lxqt/discussions
You could use for questions.

**Comment by ssxcxS45XT** [comment]
> LXQt has "Discussions": https://github.com/lxqt/lxqt/discussions

I didn't know that. I will use it next time.

Here is it. 

> What is your PS1?

I use this PS1. I don't understand why the title is not shown the same as the prompt.

But I don't want what is shown on the prompt be the same as the title (I want the title just show the current path). Should the title be controled by a different variable?

```
$ declare -p PS1
declare -x PS1="\\[\\e[4m\\]\$(tty | cut -d / -f 3)\\[\\e[m\\]@\\[\\e[36m\\]\\[\\e[4m\\]\\D{%b} \\D{%d}\\[\\e[m\\]|\\[\\e[1;36m\\]\\D{%T}\\[\\e[m\\]@\\[\\e[1;34m\\]\\w\\[\\e[m\\]\$ "
```

**Comment by ito32bit** [comment]
Please try typing `export PS1="\\[\\e[4m\\]\$(tty | cut -d / -f 3)\\[\\e[m\\]@\\[\\e[36m\\]\\[\\e[4m\\]\\D{%b} \\D{%d}\\[\\e[m\\]|\\[\\e[1;36m\\]\\D{%T}\\[\\e[m\\]@\\[\\e[1;34m\\]\\w\\[\\e[m\\]\$ \\[\\e]2;\\w\\a\\]"` and look the title.
I don't know much about PS1. Please see https://wiki.archlinux.org/index.php/Bash/Prompt_customization#Customizing_the_terminal_window_title

**Comment by ssxcxS45XT** [comment]
My PS1 works fine as a terminal prompty. I don't want to change it.

For the title of a tab, should it use some other environment variable? (It can default to PS1 if that variable is not set.)

**Comment by ssxcxS45XT** [comment]
> Please don't open issues for asking things like that, which answers themselves (yes) looking at the preferences in 0.16.1

I don't see which option to chose. Could you please show me?

Also, where should I ask questions about qterminal?

**Comment by ssxcxS45XT** [comment]
> declare -x PS1="\\[\\e[4m\\]\$(tty | cut -d / -f 3)\\[\\e[m\\]@\\[\\e[36m\\]\\[\\e[4m\\]\\D{%b} \\D{%d}\\[\\e[m\\]|\\[\\e[1;36m\\]\\D{%T}\\[\\e[m\\]@\\[\\e[1;34m\\]\\w\\[\\e[m\\]\$ "

I think this is a bug of qterminal. The above PS1 works in the prompt. But it doesn't work at the title of the tab. Therefore, it is a bug of qterminal.

**Comment by stefonarch** [comment]
> Could you please show me where it is?
 
![schermata-28-1-8:28](https://user-images.githubusercontent.com/10681413/106104748-21a38600-6143-11eb-8f39-1a19603f6eb0.png)


> Also, where should I ask questions about qterminal?

This  was mentioned too here: LXQt has "Discussions": https://github.com/lxqt/lxqt/discussions

**Comment by ito32bit** [comment]
> > declare -x PS1="\[\e[4m\]$(tty | cut -d / -f 3)\[\e[m\]@\[\e[36m\]\[\e[4m\]\D{%b} \D{%d}\[\e[m\]|\[\e[1;36m\]\D{%T}\[\e[m\]@\[\e[1;34m\]\w\[\e[m\]$ "
> 
> I think this is a bug of qterminal. The above PS1 works in the prompt. But it doesn't work at the title of the tab.

You made a typo, I think.

Please try again:
```sh
export PS1="\\[\\e[4m\\]\$(tty | cut -d / -f 3)\\[\\e[m\\]@\\[\\e[36m\\]\\[\\e[4m\\]\\D{%b} \\D{%d}\\[\\e[m\\]|\\[\\e[1;36m\\]\\D{%T}\\[\\e[m\\]@\\[\\e[1;34m\\]\\w\\[\\e[m\\]\$ \\[\\e]2;\\w\\a\\]"
```
Please copy and paste the above string.
