### ISSUE TITLE
Pressing Ctrl + L to clear the terminal does not automatically scroll down

### ISSUE THREAD

**Issue by daniruiz** [lxqt/qterminal#785]
##### Expected Behavior
Automatically scroll down after clearing the terminal

##### Current Behavior
After pressing Ctrl+L to clear the terminal, if you've scrolled up before doing so, the terminal does not automatically scroll down to show the cleaned terminal.

##### System Information
* Distribution & Version: Kali 2020.4
* Kernel: Linux kali 5.9.0-kali5-amd64
* Qt Version: 5.15.2
* qtermwidget Version: 0.16.1
* Package version: 0.16.1

**Comment by tsujan** [comment]
Already fixed in git.

**Comment by daniruiz** [comment]
Oh, sorry

Thank you then! :wink:

**Comment by tsujan** [comment]
No need to be sorry. The report was valid against 0.16.1.
