### ISSUE TITLE
Feature request: Open position in filemanager.

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#789]
One thing I miss sometimes: right click and have an option for opening working directory in  the filemanager.

**Comment by stefonarch** [comment]
Found a trick,  bookmark this:
`    <command name="Open filemanager here" value="pcmanfm-qt $(pwd)"/>
`

**Comment by tsujan** [comment]
Or `xdg-open` instead of `pcmanfm-qt`.

**Comment by stefonarch** [comment]
Even better :)

**Comment by tsujan** [comment]
I think it can be closed now. When we can already do a job, we don't need to clutter the context menu for it. Don't you agree?

**Comment by stefonarch** [comment]
I propose a deal: closing this but  remember "local bookmarks" collapsed state ;)
By default all bookmarks are exanded at startup and I never needed the "local bookmarks"

**Comment by tsujan** [comment]
Three things can be remembered:

 1. The width of the side-pane;
 2. The expand/collapse state; and
 3. The attachment/detachment of the pane.

Currently, none of them is remembered.

**Comment by stefonarch** [comment]
I'd say remember all, but no idea what 3) means.
Another issue is about default bookmarks: IMO we should ship only bookmarks that can be modified, a list of examples.

**Comment by tsujan** [comment]
> I'd say remember all, but no idea what 3) means.

The bookmark pane is a dock. It'll be detached from the main window if you click its left title-bar button.

> Another issue is about default bookmarks

The default bookmarks are hard-coded. They're about the most important places.

I don't like the current GUI design either. What should the user think about the name "Synchronized Bookmarks"? What's "synchronized"? Why are the default bookmarks called "Local"?...

If we want to change the design, we'll first need a probably long discussion and especially @yan12125's opinion.

**Comment by stefonarch** [comment]
I think "synchronized" comes from the possibility to save them in some cloud.
