### ISSUE TITLE
Adding a bookmark or loading default view?

### ISSUE THREAD

**Issue by markdavieswlt** [lxqt/qterminal#790]
I'm using qterminal on lxqt debian desktop

I need around 9 terminal windows all with different directories and commands
Ideally i'd like click one thing on desktop and load the layout and run each program
Is this possible?

If not can someone provide an example of XML bookmarks so I can add my own and do the above manually 
I've looked around and cannot see what the correct XML format is

This is probably the wrong place for this question but could not find the correct place, so please let me know where this type of thing should be asked.

**Comment by stefonarch** [comment]
A better place is https://github.com/lxqt/lxqt/discussions .
The default syntax is shown in Preferences > Bookmarks, you could try something like
```
<qterminal>
  <group name="MyBookmarks">
    <command name="tmpfiles" value="qterminal -w /tmp/">
    <command name="usr" value="qterminal -w /usr/">
  </group>
</qterminal>
```
But probably you'd better off with a script which will open different instances.

Btw I found a bug testing bookmarks...

**Comment by tsujan** [comment]
The "To discussion" button disappeared again.

**Comment by stefonarch** [comment]
> The "To discussion" button disappeared again.

So it had returned? I never saw it, probably missing permissions. Only "transfer issue" to other components.

**Comment by tsujan** [comment]
Yes, it returned for a while.
