### ISSUE TITLE
Feature request : --fullscreen switch

### ISSUE THREAD

**Issue by T0MuX** [lxqt/qterminal#796]
Hi, this is not really an issue, but a feature request.
Is there a way to start qterminal in fullscreen mode ? I tried --fullscreen -fullscreen -f but these options are not recognized. To me this function could be great :)

Thank you

**Comment by ballo** [comment]
Not being able to launch this with full screen is annoying as I have to reboot often. Is there a work-around?

**Comment by ballo** [comment]
I think I found a work-around:
qterminal --geometry 9000x9000

**Comment by stefonarch** [comment]
Some window manager (openbox, kwin) have rules for windows, you could use them.

**Comment by tsujan** [comment]
However I look at it, adding a trivial action like pressing F11 to the command-line options of a terminal emulator isn't justified.
