### ISSUE TITLE
cmake fails: Unknown arguments 'USE_YAML'

### ISSUE THREAD

**Issue by uffejakobsen** [lxqt/qterminal#800]
cmake on master branch has recently begun to fail with the following - see below

seen on Arch Linux with cmake version 3.19.6

```
cmake -B _build.out -S .
-- The C compiler identification is GNU 10.2.0
-- The CXX compiler identification is GNU 10.2.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Qt version: 5.15.2
-- Using bundled Qxt...
-- Found X11: /usr/include   
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so
-- Looking for XOpenDisplay in /usr/lib/libX11.so;/usr/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- X11_X11_LIB: /usr/lib/libX11.so
-- Building with Qt5DBus support
CMake Error at /usr/share/cmake/lxqt-build-tools/modules/LXQtTranslateDesktop.cmake:35 (MESSAGE):
  Unknown arguments 'USE_YAML'.

  See lxqt_translate_desktop() documentation for more information.

Call Stack (most recent call first):
  CMakeLists.txt:140 (lxqt_translate_desktop)


-- Configuring incomplete, errors occurred!
See also "/tmp/qterminal-devel.git/_build.out/CMakeFiles/CMakeOutput.log".
```

**Comment by yan12125** [comment]
Did you install lxqt-build-tools-git? A needed feature is not yet included in the latest stable version.

By the way, using AUR packages may be better. Most of LXQt packages on AUR are maintained by LXQt developers.

**Comment by uffejakobsen** [comment]
> Did you install lxqt-build-tools-git? A needed feature is not yet included in the latest stable version.
> 
No - I'm running the latest 0.8.0 release - I'll test that

> By the way, using AUR packages may be better. Most of LXQt packages on AUR are maintained by LXQt developers.
yes - it is just a balance between having a stable system for other uses and having a devel system :-)
I'll take a look at that...

Any plans on releasing the lxqt-build-tools soon ?

**Comment by yan12125** [comment]
> Any plans on releasing the lxqt-build-tools soon ?

Under the current convention, lxqt-build-tools is released along with other LXQt components, and I have not heard a plan about the next LXQt (most likely 0.17) yet.

**Comment by uffejakobsen** [comment]
Ok thanks - I think this issue can be closed.

I'll open a new one if other problems during build arises :-)

**Comment by tsujan** [comment]
> I have not heard a plan about the next LXQt (most likely 0.17) yet.

It'll be in the first week of April.
