### ISSUE TITLE
Coredump on opening new tab but only with wayland

### ISSUE THREAD

**Issue by FrederikLauber** [lxqt/qterminal#820]
Hello, 
experimenting with wayland and plasma atm.
I noticed that qterminal works but every time I want to open a new register, it coredumps.
This does not happen with X11+LXQT on the same machine, so my best guess is its an issue with wayland. 

#####Steps to reproduce:
open qterminal
try to open a new register card either via the menu or by double clicking the register bar

#####Expected behaviour:
New open qterminal in register card

#####StackTrace:
`Process 250842 (qterminal) of user 1000 dumped core.                                                
                                                Stack trace of thread 250842:
                                                #0  0x00007f479affe54f n/a (libqtermwidget5.so.0 + 0x4754f)
                                                #1  0x00007f479b00b08a n/a (libqtermwidget5.so.0 + 0x5408a)
                                                #2  0x00007f479a8f10cf _ZN7QWidget5eventEP6QEvent (libQt5Widgets.so.5 + 0x19c0cf)
                                                #3  0x00007f479a8af762 _ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent (libQt5Widgets.so.5 + 0x15a762)
                                                #4  0x00007f4799de363a _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5 + 0x2b663a)
                                                #5  0x00007f479670d9cc n/a (libQt5WaylandClient.so.5 + 0x859cc)
                                                #6  0x00007f479a1b46d9 _ZN22QGuiApplicationPrivate20_q_updateFocusObjectEP7QObject (libQt5Gui.so.5 + 0x12e6d9)
                                                #7  0x00007f4799e1a9d0 n/a (libQt5Core.so.5 + 0x2ed9d0)
                                                #8  0x00007f479a1c4273 _ZN7QWindow18focusObjectChangedEP7QObject (libQt5Gui.so.5 + 0x13e273)
                                                #9  0x00007f479a8ea7d3 _ZN7QWidget8setFocusEN2Qt11FocusReasonE (libQt5Widgets.so.5 + 0x1957d3)
                                                #10 0x00007f479aff11b2 _ZN11QTermWidget4initEi (libqtermwidget5.so.0 + 0x3a1b2)
                                                #11 0x0000560a260ca571 n/a (qterminal + 0x31571)
                                                #12 0x0000560a260cac19 n/a (qterminal + 0x31c19)
                                                #13 0x0000560a260cf417 n/a (qterminal + 0x36417)
                                                #14 0x0000560a260cf9ee n/a (qterminal + 0x369ee)
                                                #15 0x0000560a260c70de n/a (qterminal + 0x2e0de)
                                                #16 0x0000560a260ba559 n/a (qterminal + 0x21559)
                                                #17 0x00007f4799e1a9d0 n/a (libQt5Core.so.5 + 0x2ed9d0)
                                                #18 0x00007f479a8a8f73 _ZN7QAction9triggeredEb (libQt5Widgets.so.5 + 0x153f73)
                                                #19 0x00007f479a8ab855 _ZN7QAction8activateENS_11ActionEventE (libQt5Widgets.so.5 + 0x156855)
                                                #20 0x00007f479aa2d52b n/a (libQt5Widgets.so.5 + 0x2d852b)
                                                #21 0x00007f479aa34c62 n/a (libQt5Widgets.so.5 + 0x2dfc62)
`

##### System Information
* Distribution & Version:  Arch Linux (fully updated)
* Kernel:  5.11.14-arch1-1
* Qt Version: 5.15.2-1
* qtermwidget Version: 0.16.1-3 
* qterminal: qterminal 0.16.1-1

**Comment by tsujan** [comment]
What's "register card"? You probably mean https://github.com/lxqt/qterminal/issues/806

**Comment by FrederikLauber** [comment]
I guess it is the same underlying issue but I am not talking about splitting the existing console, I speak about what happens if you CTRL+Shift+T, in the German version that is called "Neue Registerkarte". I guess my English translation was incorrect, is it maybe "New Tab"?

I attached a screenshot (here from the X11 version but the menu point is the same)
![2](https://user-images.githubusercontent.com/17728264/115053128-13157100-9edf-11eb-821a-54b2d098d568.png)

**Comment by tsujan** [comment]
@FrederikLauber 
Thanks for the screenshot! Yes, it's "New Tab". Your report is opened to be investigated.

**Comment by tsujan** [comment]
I also saw this crash under Plasma Wayland, with a backtrace that was the same as in https://github.com/lxqt/qterminal/issues/806. But let's keep this open for the sake of testing.

The method `PlainTextDecoder::decodeLine()` seems very suspicious to me; I didn't find any guarantee that `characters[i]` exists.
