### ISSUE TITLE
Number and red cross

### ISSUE THREAD

**Issue by Moberaptor** [lxqt/qterminal#822]
Hello!
Could you please help me... I found a strange number and red cross in my terminal:
![index](https://user-images.githubusercontent.com/68503182/115239462-adabc500-a116-11eb-9aa2-f44222e0f0e2.jpg)
and I can't find what is it...
Could you explain it please? Is it normal?
Thank you!

**Comment by tsujan** [comment]
It can be related to your bash prompt. Not really related to QTerminal.

Please use [Discussion](https://github.com/lxqt/lxqt/discussions) → Q&A for questions.
