### ISSUE TITLE
[Bug] Incorrect lower case in some translations of the program name

### ISSUE THREAD

**Issue by libalis** [lxqt/qterminal#823]
The .desktop file looks like this in version 0.17 of QTerminal:

    [Desktop Entry]
    Type=Application
    Icon=utilities-terminal
    Exec=qterminal
    Terminal=false
    Categories=Qt;System;TerminalEmulator;
    Actions=Dropdown;
    
    Name=QTerminal
    GenericName=Terminal emulator
    Comment=Terminal emulator
    Name[bg]=Q**t**erminal
    GenericName[bg]=Терминал
    Comment[bg]=QTerminal
    Name[ca]=Q**t**erminal
    GenericName[ca]=Emulador de terminal
    Comment[ca]=Emulador de terminal
    Name[ca@valencia]=Q**t**erminal
    Name[cs]=QTerminal
    GenericName[cs]=Emulátor terminálu
    Comment[cs]=Emulátor terminálu
    Name[da]=Q**t**erminal
    GenericName[da]=Terminalemulator
    Comment[da]=Terminalemulator
    Name[de]=Q**t**erminal
    Comment[de]=Befehlszeile verwenden
    GenericName[de]=Terminalemulator
    [...]

You can see that many translations of the program name in the .desktop file have a small "t" instead of a capital "T".

Unfortunately, this is my first issue in this project and I don't exactly know where this one belongs.

I hope, however, that I can help and that this issue can be fixed in the next point release.

Many thanks to everyone who develops this great project and keeps it going.

**Comment by tsujan** [comment]
Translations are done at Weblate. @stefonarch knows everything about them. You're very welcome to complete/correct the translation into your native language through Weblate.

> ....that this issue can be fixed in the next point release.

Point releases are for fixes of serious bugs, while no new feature is added yet. Other fixes and new features will be in the next release. We release LXQt and its components twice a year, in April and November. Of course, users could also use git versions if their distros support them.

**Comment by libalis** [comment]
The problem would then be that almost all languages would have to be renamed in one go.

Unfortunately I don't know how to get to Weblate, how it works and how you can change them all at once.

Would be very grateful if @stefonarch could help me.

**Comment by stefonarch** [comment]
Thanks for reporting this. 
It happened when enabling translation of the .desktop files importing them as *.yaml files in weblate, QTerminal had a different build system as all other LXQt-components, one single file.

The original desktop file in 0.16 had no translations for Name=

```
[Desktop Entry]
Name=QTerminal
Type=Application
GenericName=Terminal emulator
GenericName[ca]=Emulador de terminal
GenericName[cs]=Emulátor terminálu
GenericName[es]=Emulador de terminal
GenericName[it]=Emulatore di terminale
GenericName[hu]=Terminál emulátor
GenericName[tr]=Uçbirim öykünücüsü


Comment=Terminal emulator
Comment[ca]=Emulador de terminal
Comment[cs]=Emulátor terminálu
Comment[de]=Befehlszeile verwenden
Comment[el]=Προσομοιωτής τερματικού
Comment[es]=Emulador de terminal
...

```
Usually no word starts with 2 capital letters so many translators just didn't noticed this. Me too, it's "[Qterminal](Usually no word starts with 2 capital letters so many translators didn't noticed this.)" in weblate. 

There is a search&replace function in weblate, I never used it before and will test it.

**Comment by stefonarch** [comment]
Done by https://github.com/lxqt/qterminal/pull/824/files
