### ISSUE TITLE
middle mouse paste suppressing EOL

### ISSUE THREAD

**Issue by J-Dunn** [lxqt/qterminal#829]
##### Expected Behavior
middle-mouse paste in linux seems to need a manual CR after paste. This is new in moving from 0.15  to 0.16

##### Current Behavior
If I select a complete line of text in terminal and paste it with mouse middle button , the cursor moves to the next line showing the end of line is there but it does not get executed. I need to add a keyboard Enter key stroke to execute the line. 
I do this all the time and this is clearly a change from 0.15. 

##### Possible Solution
Is this related to the new option making tab close on middle-clicking optional? 

##### Steps to Reproduce (for bugs)
1. open qterminal
2. type and run a command.
3. select the text with mouse, dragging far enough to get the EOL. 
4. middle click to paste: note text is pasted and cursor moves to next line but command not executed. 
5. press kb Enter: note command now executes.

##### System Information
Fedora 34

* Kernel:  5.11.18
* Qt Version:  Qt version 5.15.2.
* qtermwidget Version: 0.16.0
* lxqt-build-tools Version: 0.8.0
* Package version: 0.16.0

PS.
  * Made closing of tab on middle-clicking optional.
Many thanks for this mod. it's a life saver. Tabs spuriously closing and losing what I was doing was driving me crazy !!

**Comment by tsujan** [comment]
Not reproducible and 0.16.0 is outdated.

**Comment by J-Dunn** [comment]
I did an entire OS upgrade because you said 0.15 was outdated. Fed34 is the current release and it's up to date. 

Are you prepared to look at anything apart from current master builds?

**Comment by tsujan** [comment]
> Are you prepared to look at anything apart from current master builds?

The latest version (0.17.0, for now) isn't the current master build. You may want to report that to your distro.

If you had the latest version, I'd say to you to uncheck Terminal Settings → Behavior → Trim trailing newlines in pasted text. Whether that option exists in 0.16.0, we don't know and **we don't care**; old versions are forgotten.

> "not reproducible" does not sound like you tried that hard

"Not reproducible" means what it says.

**Comment by stefonarch** [comment]
Could well be that this issue was prior to https://github.com/lxqt/qterminal/commit/8c10c6ba8da8294c565a2be886da21205e693b1c
