### ISSUE TITLE
Double click on tab bar to create new tab, does not apply preset

### ISSUE THREAD

**Issue by mhd-jalilvand** [lxqt/qterminal#830]
I'm using version 0.14.1
when I open a new tab using File> New Tab then it loads as I expect
but when I create a new tab by double-click on tabs bar, it creates a single tab and presets does not apply

**Comment by stefonarch** [comment]
> t when I create a new tab by double-click on tabs bar

Don't understand this - I see no way to do this by double click anywhere.
This said 0.14 is way outdated.

**Comment by mhd-jalilvand** [comment]
![oie_kRH5C5MUvJkN](https://user-images.githubusercontent.com/14037860/118261319-9cad6400-b4c8-11eb-84e6-72cf0a1b7ac9.png)
0.14 version is latest version by installing debian 10

**Comment by stefonarch** [comment]
Thank you, I double clicked ten times  there already in current version and nothing happens. 
Looks like this was possible once.

**Comment by tsujan** [comment]
I can confirm that the preset (Terminal settings →  Appearance → Start with preset) won't be applied in the latest version of QTerminal if the tab is opened by double clicking the tab-bar. Reopening...

@stefonarch, it's strange that double clicking doesn't work for you. The code opens a new tab. Another bug that needs investigation?

**Comment by tsujan** [comment]
There's yet another problem related to this:

The option says, "Start with preset". Therefore, logically, *QTerminal itself* should also be started with the preset, not just its new tabs. If there's another option that neutralizes it, the behavior is counter-intuitive; if not, it's about the same bug.

**Comment by stefonarch** [comment]
> @stefonarch, it's strange that double clicking doesn't work for you. The code opens a new tab. Another bug that needs investigation?

No, the bug was inside me here, sorry. Related https://github.com/lxqt/qterminal/issues/351 ?

**Comment by tsujan** [comment]
> Related to #351 ?

Oh, yes, it's the second problem. I'll take a look at both when I find the time; hadn't used the preset before.

**Comment by tsujan** [comment]
A fix for both problems is here: https://github.com/lxqt/qterminal/pull/831

**Comment by mhd-jalilvand** [comment]
Thank you @tsujan , It work as expected

**Comment by tsujan** [comment]
Thanks for testing!
