### ISSUE TITLE
[]How to change some "hidden" key binding? For example, to change "scroll one line up" from shift-up to another

### ISSUE THREAD

**Issue by traditionalgithub** [lxqt/qterminal#845]
##### System Information

* Distribution & Version:  Ubuntu 20.04 LTS
* Kernel:  Linux  5.4.0-80-generic
* Qt Version: 5.12.8
* qtermwidget Version:  
* lxqt-build-tools Version:  x86_64 prebuilt from ubuntu
* Package version: QTerminal 0.14.1

##### Context
I am currently using QTerminal the version described as above (prebuilt from the Ubuntu repository) and  I wish to change the keybinding of "scrolling one line up" from shift-up to another one or disable this binding (this binding is a shortcut to change a task priority in org-mode), but i can't find this one in the preference setting, neither in ~/.config/qterminal.org/qterminal.ini. Is this binding described in somewhere else?

**Comment by tsujan** [comment]
Use [Discussions](https://github.com/lxqt/lxqt/discussions) for questions.
