### ISSUE TITLE
How to build for wayland without X11extra

### ISSUE THREAD

**Issue by jwzl** [lxqt/qterminal#853]
I build the qterminal, but it must dependcy to the x11extra!
how to build for wayland? thanks!

**Comment by yan12125** [comment]
Not possible for now. Patches are welcome.

Also, please follow the issue template.

**Comment by tsujan** [comment]
For the record, QTerminal works fine under Wayland; x11extra dependency has nothing to do with it.

**Comment by tsujan** [comment]
Closing, because in no app under LXQt, we clutter the code by adding conditions for compiling without X11 or without Wayland.
