### ISSUE TITLE
Single click to open bookmarks

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#857]
##### Expected Behavior

As in browser: one click to activate a bookmark
##### Current Behavior

Double click is needed.
 

##### Steps to Reproduce (for bugs)

1. Ctrl+shift+b to open bookmarks sidebar
2. Hit a bookmark

##### System Information

* QTerminal version: git, all

**Comment by tsujan** [comment]
Hadn't seen this report. I think it should follow the click behavior of DE. Will look into it.

**Comment by tsujan** [comment]
Elementary: https://github.com/lxqt/qterminal/pull/885

**Comment by stefonarch** [comment]
Thanks, working (didn't test with double click setting though). I'll save tons of seconds now :)

**Comment by tsujan** [comment]
Before seeing your reports, I didn't use bookmarks ;) I used a node in FeatherNotes for copying the commands I often needed. Now, I see how useful QTerminal's bookmarks can be.

**Comment by stefonarch** [comment]
Same for me, I started using them only a month ago. One downside is the manual textual editing, it lacks an simple editor mask: add command, name.

**Comment by tsujan** [comment]
IMHO, manual editing is good enough for an app that's about commands.

**Comment by stefonarch** [comment]
Wondering if we weren't to fast. Here I use single clickoverall, but I guess many users don't, and I cannot see any point in needing a doubleclick top open a bookmark, same as in browser or pcmanfm.

So better default single click and stop?

**Comment by tsujan** [comment]
Qt's platform variable is exactly about the click behavior in views. IMO, apps shouldn't contradict it. At most, an app can have an option for not following the DE behavior (as pcmanfm-qt does — because it may be used in Qt-unfriendly DEs and file clicking is important) but I think it would be an overkill here.
