### ISSUE TITLE
Backspace issues with zsh

### ISSUE THREAD

**Issue by m147** [lxqt/qterminal#859]
##### Expected Behavior
Backspace should delete the previous character.

##### Current Behavior
Backspace displays history

##### Steps to Reproduce (for bugs)
With  `bindkey -s "^h" "history 1\n"`  in .zshrc, backspace displays history, same action as CTRL-h.
With `bindkey -s "^h" "history 1\n"` removed backspace works fine.

##### System Information
 * QTerminal version: 0.17.0
* Distribution & Version: Arch 
* Kernel: Linux 5.10.69-1-lts
* Qt Version: 5.15.2

By the way, this issue does not exist with bash or fish.

**Comment by yan12125** [comment]
Whether the backspace key should produce `^H` or `^?` is an old issue. I didn't fix it as I'm not sure what is the correct behavior. Anyway, let's continue the discussion in https://github.com/lxqt/qtermwidget/issues/235.
