### ISSUE TITLE
QTerminal doesn't start

### ISSUE THREAD

**Issue by iamthesenate1** [lxqt/qterminal#868]
##### Expected Behavior

QTerminal should start
##### Current Behavior

It doesn't
##### Context

I was using lxqt on my arch instalation and when the 1.0.0 release was added to the arch repos, I updated only to realise qterminal doesn't start anymore. Here is the error: 
`qterminal: error while loading shared libraries: libqtermwidget5.so.1: cannot open shared object file: No such file or directory`  
Something worth mentioning is that qtermwidget is at it's latest version. 
I also tried removing all lxqt packaging and compiling from source with no succes.
##### System Information

* QTerminal version: 1.0.0; git
* Distribution & Version: Arch
* Kernel: 5.13
* Qt Version: 5.15.2

**Comment by tsujan** [comment]
By chance, the package maintainer is also the main developer of QTerminal; otherwise, the report should have been closed because these problems should be reported downstream, to the distro.

@yan12125, would you please investigate it?

**Comment by stefonarch** [comment]
>  I also tried removing all lxqt packaging and compiling from source with no succes.

I ran in a similar issue, as  `install_all.sh` installed in `/usr/local` as default.
Try `locate libqtermwidget5.so.1`, and maybe recompile with `LXQT_PREFIX=/usr/ install_all.sh`

**Comment by iamthesenate1** [comment]
> > I also tried removing all lxqt packaging and compiling from source with no succes.
> 
> I ran in a similar issue, as `install_all.sh` installed in `/usr/local` as default. Try `locate libqtermwidget5.so.1`, and maybe recompile with `LXQT_PREFIX=/usr/ install_all.sh`

Thanks for the suggestion. Recompiling with `LXQT_PREFIX=/usr/` did not help, but I have found libqtermwidget5.so.1 to be in /usr/local/lib so I moved it to /usr/lib and qterminal now works.

**Comment by tsujan** [comment]
> but I have found libqtermwidget5.so.1 to be in /usr/local/lib

Then, this can't be a packaging mistake either. The `so` files are in the correct place in Arch's `qtermwidget-1.0.0-1-x86_64.pkg.tar.zst`.

**Comment by stefonarch** [comment]
> Recompiling with `LXQT_PREFIX=/usr/` did not help

This variable is used in the install scripts here https://github.com/lxqt/lxqt/wiki/Building-from-source#scripts-to-build-in-one-step, otherwise it's `-DCMAKE_INSTALL_PREFIX=/usr`

**Comment by yan12125** [comment]
Yeah, for both Arch's [official package](https://github.com/archlinux/svntogit-community/blob/236be12a68efca5655db85ec7b6d8726b3564281/trunk/PKGBUILD#L35) and the AUR package [qtermwidget-git](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qterminal-git#n28) (also maintained by me), I use `-DCMAKE_INSTALL_PREFIX=/usr`, so `libqtermwidget5.so.1` is in /usr/lib as expected.
