### ISSUE TITLE
Crash when pasting in vim insert mode

### ISSUE THREAD

**Issue by jleclanche** [lxqt/qterminal#87]
I've gotten several crashes when pasting in vim insert mode when running qterminal in dropdown mode. Unfortunately I'm never running qterminal under gdb and its not 100% reproducible so I can't really test.

**Comment by yan12125** [comment]
I've never got such an issue in the past two years. I guess it's already fixed in qtermwidget/qterminal and/or vim. If this is still reproducible for you, please build qtermwidget/qterminal with debug symbols, enable systemd-coredump and use coredumpctl to get back traces.
