### ISSUE TITLE
[Feature request] Alternative for qterminal without "whistles and bells" / completely plain terminal.

### ISSUE THREAD

**Issue by ahmadraniri1994** [lxqt/qterminal#871]
Is it possible to trim or remove all stuffs / features,  whistles and bells,  and remain the basic functions, so qterminal will become simple terminal like xterm or for Wayland (foot terminal)? Thanks. Sorry if It sounds crazy.

**Comment by tsujan** [comment]
Please read the template before reporting. Thanks.

**Comment by tsujan** [comment]
QTerminal "without whistles and bells":

![qterminal](https://user-images.githubusercontent.com/981076/141956946-c6264402-4b32-4a1a-90d2-de99146b407e.png)

**Comment by ahmadraniri1994** [comment]
> QTerminal "without whistles and bells":
> 
> ![qterminal](https://user-images.githubusercontent.com/981076/141956946-c6264402-4b32-4a1a-90d2-de99146b407e.png)

Yeah I already did that, I just need to know if I can trim the features and dependencies so qterminal will behave like xterm or foot terminal.

**Comment by tsujan** [comment]
You can't remove features from an app; you can just not ignore them. QTerminal is already a lightweight app.

**Comment by ahmadraniri1994** [comment]
Alright, Thanks.
