### ISSUE TITLE
dropdown qterminal width

### ISSUE THREAD

**Issue by onesimply** [lxqt/qterminal#874]
##### Expected Behavior

Keep the width of the dropdown terminal at 100% 

##### Current Behavior

If you change the width to 100% the next time you open the preferences is set to 99%.

##### Steps to Reproduce (for bugs)

1. Set the width of the terminal to 100% and exit the preferences window.
2. Open again the preferences window and the width is set to 99%

##### System Information

* Distribution & Version: Devuan
* Kernel: 5.10
* Qt Version: 5.15.2
* liblxqt Version: 0.16.0-1
* Package version: 1.0.0

**Comment by tsujan** [comment]
Thanks for reporting! It was caused by a small mistake in the code: https://github.com/lxqt/qterminal/pull/875
