### ISSUE TITLE
Liberation font isn't recognized

### ISSUE THREAD

**Issue by z0rti** [lxqt/qterminal#891]
##### Expected Behavior
Liberation MONO should be selectable

##### Current Behavior
It doesn't show up

##### Possible Solution
Fix qterminal or fix QT or fix liberation font?

##### Steps to Reproduce (for bugs)
Install [https://github.com/liberationfonts/liberation-fonts](https://github.com/liberationfonts/liberation-fonts) into ~/.fonts
Start qterminal
Try to find Liberation mono

##### Context
Trying to use Liberation mono in qterminal like i used to in LXDE/LXterminal

##### System Information
Ubuntu 20.04.3 LTS
Qterminal 0.14.1
Kernel 5.4.0
QT 5.12.8

**Comment by tsujan** [comment]
Qt has no problem in detecting real mono fonts. See https://github.com/liberationfonts/liberation-fonts/issues/14
