### ISSUE TITLE
Closing last tab with "confirm exit" and answer "no" results in blank window

### ISSUE THREAD

**Issue by stefonarch** [lxqt/qterminal#897]
File > quit works well, with answer "no", closing last tab with  exit, ctrl+d or  x button 
and answering "no" results in blank window:

![schermata-01-31-19-26](https://user-images.githubusercontent.com/10681413/151851374-1169ef23-6b4c-4c20-af22-e00448a50906.png)

##### Expected Behavior

Never close terminal when answering "no" at confirmation dialog.
##### Current Behavior

It closes terminal but not window.
##### Steps to Reproduce (for bugs)

1. Preferences, behaviour, check "ask for confirmation when closing
2.Close tab with either cltr-d, x button or `exit`
3. Answer "no" in the dialog

##### System Information

* QTerminal version: git, 1.0.0.
* Distribution & Version: manjaro, arch

**Comment by stefonarch** [comment]
cltr+shift+t doesn't reopen tab, file > new tab does.

**Comment by tsujan** [comment]
Confirming. I don't use confirmation before closing. That's why I didn't see it.

**Comment by stefonarch** [comment]
Neither me, activated it only while checking old issues.
Related https://github.com/lxqt/qterminal/issues/746

**Comment by stefonarch** [comment]
A clean approach should be: "confirm close tab" for all tabs. It makes no sense just ask if it's the last one, it should be similar ti browser.
Would fix also https://github.com/lxqt/qterminal/issues/509 and https://github.com/lxqt/qterminal/issues/496

**Comment by tsujan** [comment]
The situation was worse. See the PR's comment: https://github.com/lxqt/qterminal/pull/898

> A clean approach should be: "Confirm tab closing" for all tabs with all 

That's a separate functionality. Here, we're talking about the *exit* prompt, which can be triggered by closing the window or its last tab.
