### ISSUE TITLE
Wonky progress bar presentation

### ISSUE THREAD

**Issue by MisileLab** [lxqt/qterminal#926]
##### Expected Behavior
Display without overlap

##### Current Behavior
progress bar isn't connect each other and overlap with other components.

##### Possible Solution
I don't know

##### Steps to Reproduce (for bugs)
install package that need install so long using pip (I installed pytorch)

##### Context
This is maybe not important, but It's bug.

##### System Information
* QTerminal version: 0.17.0
* Distribution & Version: lubuntu 21.10
* Kernel: 5.13.0-35-generic
* Qt Version: 5.15.2

Image
![a](https://user-images.githubusercontent.com/74066467/157175467-7242a9dc-d210-426e-9a42-323df2b3fdd8.jpg)

**Comment by MisileLab** [comment]
Original issue : https://github.com/pypa/pip/issues/10947

**Comment by stefonarch** [comment]
Could you include the screenshot here too?

**Comment by MisileLab** [comment]
> Could you include the screenshot here too?
https://user-images.githubusercontent.com/74066467/157175467-7242a9dc-d210-426e-9a42-323df2b3fdd8.jpg

**Comment by MisileLab** [comment]
![a](https://user-images.githubusercontent.com/74066467/157175467-7242a9dc-d210-426e-9a42-323df2b3fdd8.jpg)

**Comment by MisileLab** [comment]
How can I update qterminal, I'm using lubuntu and qterminal does not updated.

**Comment by yan12125** [comment]
Hmm, just downgraded qterminal/qtermwidget on my machine to 0.17 and pip's progress bar still works fine. Maybe old qterminal is not the major issue.

What's your terminal font?

**Comment by MisileLab** [comment]
[MesloLGS NF](https://github.com/romkatv/powerlevel10k-media/raw/master/MesloLGS%20NF%20Regular.ttf)

**Comment by MisileLab** [comment]
I tried pip install torch with other terminal (Konsole), but the terminal does not happens bug.

**Comment by tsujan** [comment]
Not reproducible here either.

**Comment by yan12125** [comment]
Thanks, with MesloLGS NF Regular things are still fine for me.

> I tried pip install torch with other terminal (Konsole), but the terminal does not happens bug.

Could you try to select the smallest line segment of the progress bar to see if its width is the same as an English letter or not? If  it appears like this figure (note the segment below `n`), qterminal handles the progress bar correctly.

![圖片](https://user-images.githubusercontent.com/1937689/159002386-bd152cf3-ac34-40c3-a7c4-0c34130d8ff8.png)

How qterminal handles width of special characters is indeed quite different from Konsole, while I don't think that makes a difference. Characters used in the progress bar `━` (U+2501), `╸` (U+2578) and `╺` (U+257A) are ["ambiguous width"](https://www.unicode.org/Public/14.0.0/ucd/EastAsianWidth.txt), and they are [treated like half width characters](https://github.com/lxqt/qtermwidget/blob/master/lib/konsole_wcwidth.cpp) for now.

**Comment by MisileLab** [comment]
![image](https://user-images.githubusercontent.com/74066467/159034258-bb328aba-860d-42b9-9365-e0ceef4a91d2.png)
Konsole does not have blank with U+2501 but qterminal does, but qterminal without zsh (shell) does not have blank, but still wonky.

**Comment by MisileLab** [comment]
![image](https://user-images.githubusercontent.com/74066467/159035108-b905a4cc-acb5-48e3-9905-da9d422a83e1.png)
Konsole does not have blank with U+2501 but qterminal does, but qterminal without zsh (shell) does not have blank, but still wonky.

**Comment by yan12125** [comment]
The last screenshot looks like a font issue again, but MesloLGS NF should be OK. I have no more ideas. I don't have time to setup Lubuntu for testing, either.
