### ISSUE TITLE
DropDown focus

### ISSUE THREAD

**Issue by joharei** [lxqt/qterminal#94]
When I hit the shortcut to show the DropDown terminal, the cursor in the dropdown terminal indicates -- seemingly at random -- that the terminal is not in focus. Sometimes, however, it accepts input although it's not in focus. Clicking the terminal does not change the cursor to "focused", but Alt+Tab-ing back and forth ensures the terminal is in focus.

EDIT: Actually, Alt+Tab-ing doesn't seem to ensure focus every time.

**Comment by ghosthoughts** [comment]
I confirm this behavior. At times, it doesn't even accept input. I haven't been able to observe a pattern on this though. As said, the behavior is random.

**Comment by goetzc** [comment]
Sometimes pressing F12 once, shows and hides the terminal very fast. I have observed that at times when the cursor is active or inactive, a `~` character is inserted before the cursor. 

Tested with the latest git code 56043ba

**Comment by Arnaudv6** [comment]
confirmed here : cursor does not get the focus when terminal gets back
and ~ character appear as if to print the shortcut key press

**Comment by ghosthoughts** [comment]
Any progress on this? This bug is killing this app for me as I frequently and reliably need to keep switching windows for work.
I tried fiddling with the source code, using various focus-related Qt APIs of the related drop-down window widgets on a trail-and-error basis, but could not make things work.

**Comment by stefonarch** [comment]
Actually only way not to have focus is  opening "View" or "File" and press F12 or move pointer to close it.
