### ISSUE TITLE
unable to execute command in new UI window

### ISSUE THREAD

**Issue by jredfox** [lxqt/qterminal#958]
##### Expected Behavior
`-e` or `-x` executes command in a new UI window

##### Current Behavior
executes in the background

##### Possible Solution
open `-e` in a new UI window likes most linux terminals do. have a `--background` option to run in the background
I did figure out that using `-de` but not `-d` and `-e` forces a new UI window but I think it's caused by a bug

##### Steps to Reproduce (for bugs)

1.run `qterminal -e java` in a terminal of your choice
2. it executes in the same ui or in the background

##### Context

effected my java library open terminal being unable to support you

providing a programmatic solution to start a command in a new UI window for the user to see.

##### System Information

* QTerminal version: 0.14.1
Linux mint amd64

**Comment by tsujan** [comment]
Not reproducible here:

![java](https://user-images.githubusercontent.com/981076/172068170-7a15f50d-c9bd-4e1d-be38-301974e3ef3b.png)

I can't say anything about QTerminal 0.14.1; it's outdated.

**Comment by jredfox** [comment]
@tsujan I used `sudo apt-get install qterminal` and that's what showed up

**Comment by tsujan** [comment]
@jredfox 
0.14.1 was outdated in 2020. You might want to report that to your distro.

The latest release is 1.1.0.

**Comment by jredfox** [comment]
@tsujan I think it's the programmer's job to keep it up to date with apt-get install at the very least. maybe not the specific app stores like ubuntu's snap store idk new to linux but in every other platform seems to be the case

**Comment by tsujan** [comment]
> I think it's the programmer's job to keep it up to date with apt-get install at the very least

Incorrect idea. Programmers have nothing to do with making binaries. Distros have their "package maintainers".
