### ISSUE TITLE
improper argument parsing

### ISSUE THREAD

**Issue by jredfox** [lxqt/qterminal#959]
##### Expected Behavior

executes a command with spaces that is quotes with either `'` or `"`

##### Current Behavior

parses every space into a new argument regardless of quotes

##### Steps to Reproduce (for bugs)

1.` java -jar 'my spaced java app.jar'`
output:
```
jredfox@jredfox-lm:~$ qterminal -de java -jar '/home/jredfox/Desktop/red sands.jar'
qt5ct: using qt5ct plugin
Properties constructor called
TRANSLATIONS_DIR: Loading translation file "qterminal_en_US.qm" from dir /usr/share/qterminal/translations
load success: false
qt5ct: D-Bus global menu: no
Canot open file "/home/jredfox/.config/qterminal.org/qterminal_bookmarks.xml"
"Press \"F12\" to see the terminal."
Trying to load translation file from dir "/usr/share/cinnamon"
Trying to load translation file from dir "/usr/share/gnome"
Trying to load translation file from dir "/home/jredfox/.local/share/flatpak/exports/share"
Trying to load translation file from dir "/var/lib/flatpak/exports/share"
Trying to load translation file from dir "/usr/local/share"
Trying to load translation file from dir "/usr/share"
Trying to load translation file from dir "/usr/share/qtermwidget5/translations"
default KB_LAYOUT_DIR:  "/usr/share/qtermwidget5/kb-layouts"
loadAllColorSchemes
Shell program: "java -jar /home/jredfox/Desktop/red sands.jar"
("java", "-jar", "/home/jredfox/Desktop/red", "sands.jar")
Properties destructor called
```

##### Context

unable to support your terminal due to it being broken

##### System Information

* QTerminal version: 0.14.1
* Distribution & Version:  linux mint amd 64

**Comment by tsujan** [comment]
Definitely not the case in the latest release.

**Comment by yan12125** [comment]
Ancient qterminal version aside, this is indeed a bug.
```
$ LANG=en_US.UTF-8 strace -e trace=execve -f qterminal -e java -jar '/home/jredfox/Desktop/red sands.jar' |& grep execve
execve("/usr/bin/qterminal", ["qterminal", "-e", "java", "-jar", "/home/jredfox/Desktop/red sands."...], 0x7fff778fc398 /* 103 vars */) = 0
[pid  4139] execve("", ["", "-jar", "/home/jredfox/Desktop/red", "sands.jar"], 0x55aad9adb920 /* 103 vars */) = -1 ENOENT (No such file or directory)
```
See https://github.com/lxqt/qterminal/issues/335.

**Comment by tsujan** [comment]
With `-e` yes. Without `-e`, it's OK:

![spaces](https://user-images.githubusercontent.com/981076/172151684-f12e3b53-993f-4f71-87e8-61ef149abb88.png)

**Comment by yan12125** [comment]
yep

**Comment by tsujan** [comment]
I found a "solution":

I used of  '\x1' (`QChar(01)`) instead of space (`QLatin1Char(' ')`) when getting `shell_command` in "main.cpp". Then, I got its parts by:

```c++
QStringList parts = shell.split(QChar(01), Qt::SkipEmptyParts);
```
Instead of
```c++
QStringList parts = shell.split(QRegExp(QStringLiteral("\\s+")), Qt::SkipEmptyParts);
```
In "termwidget.cpp".

It worked here.

However, I think a proper solution may be using of `QStringList` instead of `QString`. That requires many changes to the code, for which I don't have time today.

**Comment by yan12125** [comment]
> However, I think a proper solution may be using of `QStringList` instead of `QString`

Yeah, I have the same feeling https://github.com/lxqt/qterminal/issues/335#issuecomment-304437802, but I cannot finish it after 5 years :(

**Comment by tsujan** [comment]
> Yeah, I have the same feeling https://github.com/lxqt/qterminal/issues/335#issuecomment-304437802, but I cannot finish it after 5 years :(

I understand. Lack of time has also made me overestimate the amount of the required changes and, as a result, I've delayed implementations.

After taking a look at the code, I think the changes are simple in this case. Will make a PR tonight or tomorrow and will request your review.
