### ISSUE TITLE
can't compile or install binaries

### ISSUE THREAD

**Issue by jredfox** [lxqt/qterminal#960]
downloaded the release source 1.1
ran `cd /home/jredfox/Downloads/qterminal-1.1.0`
ran `make install '/home/jredfox/Downloads/qterminal-1.1.0/build'`
and then it says can't find `install`

I tried running:
`apt-get install qterminal` and then it downloads the outdated 0.14. you need to fix your installation either in your github or ubuntu like distros with apt-get or both

**Comment by stefonarch** [comment]
https://github.com/lxqt/lxqt/wiki/Building-from-source

There is nothing to fix on our side. Consider learning soime basics about compiling and binary precompiled packages provided by your distro.

**Comment by jredfox** [comment]
then enjoy nobody using the app how stupid are linux devs

**Comment by stefonarch** [comment]
Yeah, stupidity is a real problem.
