### ISSUE TITLE
Multi-line confirmation has no effect with text DND

### ISSUE THREAD

**Issue by abrikos110** [lxqt/qterminal#970]
I use touch pad, and sometimes when i select some text in qterminal and accidentally move my mouse while still holding mouse button pressed, the terminal pastes selected text in terminal. This (in most cases) unwanted (for me) pastes are so annoying and cause so much mess because they are often multiline and this causes bash to try to execute this.
Even if "confirm multiline paste" setting is turned on, drag'n'dropped text pastes without usual confirmation.

[Video of drag'n'drop](https://drive.google.com/file/d/1rHIRamxHUnYrPcMvEkFgdBk3fd9FTvkp/view?usp=sharing)

It will be better to add possibility to turn off drag and drop feature. Or make drag and dropped multiline text paste show a confirmation before pasting (ideally both)

**Comment by tsujan** [comment]
Oh, sorry! Yes, DNDed text doesn't follow the confirmation setting. I change the title and add the bug label....
