### ISSUE TITLE
behavior option to copy on selection

### ISSUE THREAD

**Issue by mc36** [lxqt/qterminal#974]
**Is your feature request related to a problem? Please describe.**
some find it convenient that selecting the text implicitly copy it to the clipboad

**Describe the solution you'd like**
once the selection is finished, and the option is enabled, it should copy immediately to the clipboard

**Comment by tsujan** [comment]
In all apps, the text selection is copied to the selection clipboard.

**Comment by mc36** [comment]
hmmm.... you were right, i just checked it a bit closer, and here is what i see:
selection copies the text somewhere, and that can be pasted back with the middle button click...
but, it does not help when switching to a different app, i cannot paste the text to somewhere else...
i set up the copy selection hotkey, this one works between different apps...

**Comment by tsujan** [comment]
> i cannot paste the text to somewhere else...

You should be able to do that, unless you don't use Linux or have changed some clipboard setting (outside QTerminal). This isn't specific to QTerminal; Linux has "selection clipboard".

**Comment by mc36** [comment]
i'm on linux, specifically, debian sid, and qterminal from experimental... they ship 1.1.0 now there...
the thing is, added a fresh user, logged in to lxqt, and the issue is there... i ctrl+shift+t, ls -lsa /, select some lines...
then opening nedit, edit/paste, and nothing happens....

**Comment by tsujan** [comment]
> then opening nedit, edit/paste, and nothing happens....

The selection clipboard is pasted by middle clicking; "Paste" is for pasting the main clipboard.

If you want to paste the selection clipboard with "Paste" menu-item or its shortcut, you need a "clipboard manager" that's capable of giving the contents of selection clipboard to the primary clipboard.

Again, this isn't specific to QTerminal or any other app.

**Comment by mc36** [comment]
my bad, and thanks for pointing to the right direction!
(i'm very nooob to these gui things, sorry!)
finally it was the solution here, if someone finds this thread:
autocutsel -fork -selection CLIPBOARD
autocutsel -fork -selection PRIMARY

**Comment by tsujan** [comment]
The advantage of having two clipboards is that the user can paste two different texts. But yes, the two clipboards can also be synchronized by using clipboard managers.
