### ISSUE TITLE
[Feature request] Dropdown mode with hiding on launch

### ISSUE THREAD

**Issue by ianfarrell47** [lxqt/qterminal#984]
**Is your feature request related to a problem? Please describe.**
When setting `qterminal --drop` to autostart with the session, I would like qterminal to open in the background.

**Describe the solution you'd like**
To add another option like, `-l    --lower` to `-d    --drop`.

##### Context
Some people may want to launch `--drop` on session autostart without seeing the terminal.

**Comment by tsujan** [comment]
Terminal settings → Dropdown → Show on start (uncheck)

**Comment by stefonarch** [comment]
And me who thought this is a good idea - ignored that option...

**Comment by tsujan** [comment]
This option was in an appropriate place — some others are too — but I think QTerminal's preferences dialog isn't tidy. I can't find some options quickly. It reminds me of KDE config dialogs.

**Comment by stefonarch** [comment]
I think often it's just kind of blindness - you won't see it until somebody puts your nose on it.
I rarely restart session or machine, so it wasn't that disturbing and if I remember well other opening windows in autostart closed the dropdown terminal.

**Comment by ianfarrell47** [comment]
>but I think QTerminal's preferences dialog isn't tidy.
`lxqt-config-appearance` and other places (?) in LXQt, use the "big" style side panel style.
For most icon sizes and font sizes, changing the QTerminal preferences dialog to "big" style could improve navigation.

**Comment by ianfarrell47** [comment]
>but I think QTerminal's preferences dialog isn't tidy.

`lxqt-config-appearance` and other places (?) in LXQt, use the "big" side-panel buttons.
Changing the preferences side-panel to "big" side-panel style might improve navigation.

Also, the subsections "Appearance" and "Behavior" could use more group boxes.
