### ISSUE TITLE
Compiling not working

### ISSUE THREAD

**Issue by Linux-Gamer** [lxqt/qterminal#986]
##### Expected Behavior

```make``` should build the project.

##### Current Behavior

```make``` fails saying makefile isn't found, which it isn't in the repo anywhere.

##### Possible Solution

Maybe add a make file, rather than just telling us to run make, have a more detailed documentation for building from source

##### Steps to Reproduce (for bugs)

1. git clone the repo (with --recurse)
2. cd into the directory
3. run ```make```
4. error will appear

##### Context

I am trying to see how the app is put together to help me understand (as I might try to contribute to the project soon).

##### System Information

* QTerminal version: Git Repo with latest commits
* Distribution & Version: Fedora 36
* Kernel: 5.18.17-200.fc36.x86_64  
* Qt Version: 5.15.5

**Comment by Chiitoo** [comment]
See: https://github.com/lxqt/qterminal#compiling-sources

In particular the 'Code configuration is handled by CMake' is kind of important.  : )
